### ISSUE TITLE
Receiving error when attempting simple request

### ISSUE THREAD

**Issue by sabre1041** [microsoftgraph/msgraph-sdk-go#102]
I am attempting to leverage the library and have not been successful retrieving content from the Graph API

```golang
package main

import (
	"fmt"

	azidentity "github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	a "github.com/microsoft/kiota/authentication/go/azure"
	msgraphsdk "github.com/microsoftgraph/msgraph-sdk-go"
)

	cred, err := azidentity.NewClientSecretCredential(
		"<TENANT_ID>",
		"<CLIENT_ID>",
		"<CLIENT_SECRET>",
		nil)

	auth, err := a.NewAzureIdentityAuthenticationProviderWithScopes(cred)

	if err != nil {
		panic(err)
	}

	adapter, err := msgraphsdk.NewGraphRequestAdapter(auth, , []string{})
	if err != nil {
		panic(err)
	}

	client := msgraphsdk.NewGraphServiceClient(adapter)

	_, err = client.Me().Get(nil)

	if err != nil {
		fmt.Println(err)
	}
```

All attempts have resulted in the following error

```
error status code received from the API
```

**Comment by baywet** [comment]
Hi @sabre1041,
Thanks for trying out the Go SDK and for reaching out.

What scopes/roles (app permissions) have you registered for your application?

Also `/me` is a shorthand to `/users/user@company.com` on the service side. The way the service gets the current user is by extracting it from the access token. But in an application context scenario the access token only carries the application identity, as opposed to delegated when it carries the information of a user using the application. [more information](https://docs.microsoft.com/en-us/graph/auth/auth-concepts#delegated-and-application-permissions)

As the code showcases an app only context (client id/secret with no user claim), it can't use any me paths on the API. You either need to update your authentication setup depending on the scenario you're trying to implement, or switch the API path from me to users.

**Comment by baywet** [comment]
Thanks for sharing this additional information. These permissions are not the correct ones according to the authentication configuration of your application.
In the type column it should say application instead of delegated.
Removes the delegated ones. Add the corresponding application ones and don't forget to click on grant administrator consent after that. It should then work.

**Comment by sabre1041** [comment]
@baywet thank you so much for the guidance. Updating to an application type worked successfully.

Closing issue
