### ISSUE TITLE
Clarify how to check for a specific error code

### ISSUE THREAD

**Issue by mbarnes** [microsoftgraph/msgraph-sdk-go#110]
Can you please include an example in `README.md` of how to check a failed client request for a specific error code?

I've read through [Microsoft Graph error responses and resource types](https://docs.microsoft.com/en-us/graph/errors?context=graph%2Fapi%2F1.0&view=graph-rest-1.0) but in the Go SDK it's not clear how to convert a returned `error` type to an [ODataError](https://github.com/microsoftgraph/msgraph-sdk-go/blob/6d963f6a366205968c2126aa11a7e3b41b108319/models/microsoft/graph/odataerrors/o_data_error.go#L8-L14) (if that's even what you're supposed to do).

If I try a simple type cast the compiler produces:
```
odataerrors.ODataError does not implement error (Error method has pointer receiver)
```

**Comment by mbarnes** [comment]
Figured it out, or at least got something that compiles.

My use case was something like this.  Assuming I'm doing it right, perhaps this would lend itself to an example.
```
import (
    msgraph_errors "github.com/microsoftgraph/msgraph-sdk-go/models/microsoft/graph/odataerrors"
)

...

result, err := graph.ServicePrincipals.Post(options)

if oDataError, ok := err.(*msgraph_errors.ODataError); ok &&
    *oDataError.GetError().GetCode() == "accessDenied" {
        ...
    }
```

**Comment by baywet** [comment]
Hi @mbarnes 
Thanks for using the Go SDK and for reaching out.

## The short version

- Transient errors (network connectivity, 429's...) are handled and retried but the http client and the middleware handlers the SDK uses.
- Any 4XX and 5XX status code that's non-transient will result in an OData error (more on how to deal with them later)
- Errors in the request adapter logic will be [API errors](https://github.com/microsoft/kiota/blob/468a319ac5ba3ce2b7f09962e2402b1df276df07/abstractions/go/api_error.go#L6)
- Errors in the serialization/deserialization logic will be generic errors
- Errors in the authentication provider will either be generic or custom errors returned by Azure Identity

### How to handle non-transient service errors

Each model (errors from the service are models) get a reflective interface to ease up casting operations, ending up in `able` by convention.

```Golang
import (
    msgraph_errors "github.com/microsoftgraph/msgraph-sdk-go/models/microsoft/graph/odataerrors"
)

result, err := graph.ServicePrincipals().Post(options)

if oDataError, ok := err.(msgraph_errors.ODataErrorable); ok &&
    oDataError.GetError().GetCode() == "accessDenied" {
        ...
    }
```

## The long version

Observability is still a [known gap](https://github.com/microsoftgraph/msgraph-sdk-go-core/issues/31) in this preview version of the SDK. Multiple things need to happen, first our architect needs to spec out the desired behaviour (across all languages), then the behaviour needs to be implemented in the [kiota](https://github.com/microsoft/kiota) core libraries, and finally some of that might need to be reflected in msgraph-sdk-go-core and/or the generation logic.

Besides this aspect, it might be beneficial to align the error types (and of course document some of the behaviour so people know what they are supposed to do when they run into one). Here is my question to you: Do you think it'd be beneficial to sdk users (you and others) to have all the errors generated from the client layers itself inherit from a common type and have specialized types? e.g.:
- We already have a generic API error, and you can catch everything with that, it might need an interface though.
- Or model errors (coming from the service) for 4XX, 5XX "inherit" from it.
- Request adapter logic errors would have a specialized "request adapter error", inherits from API error.
- Serialization logic errors would have a specialized "serialization error", inherits from API error.
- Authentication provider logic error would have a specialized "authentication error", inherits from API error.
- Any error from dependencies of those last three layers would be wrapped in one of the specialized type.

**Comment by mbarnes** [comment]
Thanks for the detailed response!

> Here is my question to you: Do you think it'd be beneficial to sdk users (you and others) to have all the errors generated from the client layers itself inherit from a common type and have specialized types?

I don't have much experience with this particular SDK, but a common base error type beyond the built-in `error` sounds good as long as it's utilized better by subtypes.

One suggestion that might help newcomers is the [default `ApiError` message](https://github.com/microsoft/kiota/blob/468a319ac5ba3ce2b7f09962e2402b1df276df07/abstractions/go/api_error.go#L14) should include some hints to help developers identify and catch that specific error type.  Right now it's too generic.  I suggest at least including the error type (`%T`) in the message.

Or better yet, make sure each of the subtypes sets the `ApiError`'s `Message` string.  I haven't checked the others, but it doesn't look like `ODataError` sets it (unless it happens somewhere in [kiota](https://github.com/microsoft/kiota)).  I'd like to see it identify itself as an `ODataError` and include the top-level code and maybe message.  Perhaps do this as part of [`SetError()`](https://github.com/microsoftgraph/msgraph-sdk-go/blob/6d963f6a366205968c2126aa11a7e3b41b108319/models/microsoft/graph/odataerrors/o_data_error.go#L84-L89). e.g.
```
// SetError sets the error property value. 
func (m *ODataError) SetError(value MainErrorable)() {
    if m != nil {
        m.error = value
        if m.error != nil {
            m.Message = fmt.Sprintf("%T: %s: %s", m, m.error.GetCode(), m.error.GetMessage())
        } else {
            m.Message = ""
        }
    }
```

**Comment by baywet** [comment]
Thanks for all that valuable information!

Setting things in ODataError is tedious since this type is generated from the OpenAPI description of the API. The generator _doesn't know_ the message property is "special" and should get a different Setter.

However doing this in the API error for **both** the default error message and the provided message makes a lot of sense.

Would you be willing to submit a pull request over there?
