### ISSUE TITLE
How do I get the delegated API permissions for an application from the graph API?

### ISSUE THREAD

**Issue by praetorian-thendrickson** [microsoftgraph/msgraph-sdk-go#113]
I'm not able to figure out how to use the API to retrieve the api permissions assigned to my application. This is the page of permissions I want to retrieve via the graph api. I'm using the API listed here: https://docs.microsoft.com/en-us/graph/api/serviceprincipal-list-delegatedpermissionclassifications?view=graph-rest-1.0&tabs=http. However, it doesn't seem to return any delegated permissions. The error is probably on my end, and I'm likely using the wrong API. Would someone be able to point me in the right direction for retrieving the "API Permissions" through the graph api? Thanks!

```golang
// setup client *msgraphsdk.GraphServiceClient (clipped for brevity)
permissions, er := client.ServicePrincipalsById(id).DelegatedPermissionClassifications().Get(nil)
if er != nil {
	fmt.Printf("error: %s %v\n", er, permissions)
	return er
}

piterator, er := msgraphcore.NewPageIterator(permissions, adapter.GraphRequestAdapterBase, graph.CreateDelegatedPermissionClassificationCollectionResponseFromDiscriminatorValue)
if er != nil {
	fmt.Printf("error: %s %v\n", er, permissions)
	return er
}

er = piterator.Iterate(func(pageItem interface{}) bool {
	p := pageItem.(*graph.DelegatedPermissionClassification)
	fmt.Printf("permission grant for id: %s -> %s %s\n", foundId, *p.GetId(), *p.GetPermissionName())
	return true
})
```
<img width="1516" alt="permissions-2" src="https://user-images.githubusercontent.com/69640071/159540477-731d5ce8-1e76-4212-87f1-1d7ebb54fb85.png">

**Comment by praetorian-thendrickson** [comment]
Thanks for the quick response, I was trying that API as well but it was not returning anything. I will try again and post some code/results here

**Comment by praetorian-thendrickson** [comment]
Hey @baywet,

Thanks again for all the help. With the oauthPermissionsGrants API I get the following:
```golang
er = pr.Iterate(func(pageItem interface{}) bool {
		p := pageItem.(*graph.OAuth2PermissionGrant)
		fmt.Printf("Identified OAuth2PermissionGrant ConsentType: %s ClientId: %s Scope: %s\n", *p.GetConsentType(), *p.GetClientId(), *p.GetScope())
		return true
	})
```
Output:
```bash
Identified OAuth2PermissionGrant ConsentType: AllPrincipals ClientId: 01234-CLIENT-ID-1234 Scope: User.Read Directory.AccessAsUser.All
```

These are the two Delegated permissions associated with the enterprise application, but I'm looking for the other 6 "Application" type permissions. Do you know which API that might be?

<img width="1516" alt="permissions-2-2" src="https://user-images.githubusercontent.com/69640071/159573571-7494f552-5683-4044-b312-419560cc6239.png">

**Comment by baywet** [comment]
These? https://docs.microsoft.com/en-us/graph/api/serviceprincipal-list-approleassignments

**Comment by praetorian-thendrickson** [comment]
I think this might be it, because using that I get 6 assignments:
```golang
fmt.Printf("permission grant for id: %s -> %s %s %s\n", appId, *p.GetAppRoleId(), *p.GetResourceDisplayName(), *p.GetPrincipalType())
```
```
permission grant for id: ObjId -> 9e640839-a198-48fb-8b9a-013fd6f6cbcd Microsoft Graph ServicePrincipal
permission grant for id: ObjId -> 483bed4a-2ad3-4361-a73b-c83ccdbdc53c Microsoft Graph ServicePrincipal
permission grant for id: ObjId -> 5b567255-7703-4780-807c-7be8301ae99b Microsoft Graph ServicePrincipal
permission grant for id: ObjId -> 7ab1d382-f21e-4acd-a863-ba3e13f7da61 Microsoft Graph ServicePrincipal
permission grant for id: ObjId -> c7fbd983-d9aa-4fa7-84b8-17382c103bc4 Microsoft Graph ServicePrincipal
permission grant for id: ObjId -> df021288-bdef-4463-88db-98f22de89214 Microsoft Graph ServicePrincipal
```

I suppose my last question is how do I get the claim value from the `AppRoleAssignment`? I don't see in the assignment definition https://github.com/microsoftgraph/msgraph-sdk-go/blob/main/models/microsoft/graph/app_role_assignment.go how to obtain that information from the object

**Comment by baywet** [comment]
You should be able to match those with the appRole property from the Microsoft Graph application:
- Use the resourceId as the applicationId
- Match the appRoleId with the appRole.Id in the collection
https://docs.microsoft.com/en-us/graph/api/application-get?view=graph-rest-1.0&tabs=http

**Comment by praetorian-thendrickson** [comment]
I spent some time testing and using the `resourceId` from the `AppRoleAssignment` object as the `applicationId` to the get applications graph API endpoint (https://docs.microsoft.com/en-us/graph/api/application-get?view=graph-rest-1.0&tabs=go) did not return anything (apart from an API error and empty response)

Through the Azure graph explorer UI I used the GetApplications API endpoint (`GET /applications/{id}`) to retrieve the application Object and noticed that the application had an empty appRoles response object (I verified the `appId` in the explorer response matches the Application Id in the Overview tab of the Azure Portal UI:
```
"appRoles": [],
```
<img width="353" alt="graph-explorer" src="https://user-images.githubusercontent.com/69640071/159751459-f955ea89-f011-4b8e-9c2e-c8b3dae5665c.png">



But in the UI, I can see permissions assigned to that application. 

<img width="1557" alt="permissions" src="https://user-images.githubusercontent.com/69640071/159751108-cc7a6077-a93e-4b5a-aab3-b20f8ceb88ae.png">

So, with the https://docs.microsoft.com/en-us/graph/api/serviceprincipal-list-approleassignments?view=graph-rest-1.0&tabs=http API it seems possible to get the app role assignments but I don't know how to view any information on what the app role assignment is except for the fields defined in the `AppRoleAssignment` object. But none of these have the information on what the claim value or permission actually is. I think my question still remains on how to actually view the claim values or permissions for the app role assignments.
```golang
type AppRoleAssignment struct {
    DirectoryObject
    // The identifier (id) for the app role which is assigned to the principal. This app role must be exposed in the appRoles property on the resource application's service principal (resourceId). If the resource application has not declared any app roles, a default app role ID of 00000000-0000-0000-0000-000000000000 can be specified to signal that the principal is assigned to the resource app without any specific app roles. Required on create.
    appRoleId *string;
    // The time when the app role assignment was created. The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z. Read-only.
    createdDateTime *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time;
    // The display name of the user, group, or service principal that was granted the app role assignment. Read-only. Supports $filter (eq and startswith).
    principalDisplayName *string;
    // The unique identifier (id) for the user, group, or service principal being granted the app role. Required on create.
    principalId *string;
    // The type of the assigned principal. This can either be User, Group, or ServicePrincipal. Read-only.
    principalType *string;
    // The display name of the resource app's service principal to which the assignment is made.
    resourceDisplayName *string;
    // The unique identifier (id) for the resource service principal for which the assignment is made. Required on create. Supports $filter (eq only).
    resourceId *string;
}
```

**Comment by baywet** [comment]
Sorry, I don't know those APIs that well and I had to dig deeper to get the specifics.

1. Get the required resource access from your app registration
    ```
    GET https://graph.microsoft.com/v1.0/applications/ea04687b-dfd8-49bb-a7bb-648c6150d4ea
    ```
   
    ```json
    "requiredResourceAccess": [
        {
            "resourceAppId": "00000003-0000-0000-c000-000000000000",
            "resourceAccess": [
                {
                    "id": "e1fe6dd8-ba31-4d61-89e7-88639da4683d",
                    "type": "Scope"
                },
                {
                    "id": "5f8c59db-677d-491f-a6b8-5f174b11ec1d",
                    "type": "Scope"
                }
            ]
        }
    ],
   ```
   > Note: the id here is the object ID of the application, not the client id, which you can get from the portal
1. Take the resource app id from there (this is the client id for Microsoft Graph)
1. Take the resource access ids from there (scope ids)
1. Query the service principal endpoints to get their definition
    ```
    GET https://graph.microsoft.com/v1.0/servicePrincipals?$filter=appid eq '00000003-0000-0000-c000-000000000000'&$select=oauth2PermissionScopes
   ```
   > Where the id value is the one we obtained from the previous payload, and the select statement is here to make the payload smaller as it's a rather large object
   ```json
    // truncated for brievety
    "oauth2PermissionScopes": [
        {
                    "adminConsentDescription": "Allows the app to list groups, and to read their properties and all group memberships on behalf of the signed-in user.  Also allows the app to read calendar, conversations, files, and other group content for all groups the signed-in user can access. ",
                    "adminConsentDisplayName": "Read all groups",
                    "id": "5f8c59db-677d-491f-a6b8-5f174b11ec1d",
                    "isEnabled": true,
                    "type": "Admin",
                    "userConsentDescription": "Allows the app to list groups, and to read their properties and all group memberships on your behalf.  Also allows the app to read calendar, conversations, files, and other group content for all groups you can access.  ",
                    "userConsentDisplayName": "Read all groups",
                    "value": "Group.Read.All"
                },
     ]
    ```
1. Match the scope id here with the resource access id from the previous call

Hopefully this should be fairly easy to translate to Go calls with something like

```Golang
application, er := client.ApplicationsById(id).Get(nil)
if er != nil {
	fmt.Printf("error: %s %v\n", er, permissions)
	return er
}
resourceAppId := application.GetRequiredResourceAccess()[0].GetResourceAppId();

graphServicePrincipals, er := client.ServicePrincipals().Get(&ServicePrincipalGetOptions{
  Q: &ServicePrincipalGetQueryParameters {
    Select: "oauth2PermissionScopes",
    Filter: "appid eq '"+resourceAppId+"'",
})
if er != nil {
	fmt.Printf("error: %s %v\n", er, permissions)
	return er
}
graphServicePrincipal := graphServicePrincipals[0]
// put the oauth2PermissionScopes into a map per id for a faster lookup
graphScopes := make(map[string]string)

for(resourceAccess in application.GetRequiredResourceAccess()[0].GetResourceAccess()) {
    fmt.Printf("permission grant for id: %s -> %s %s\n", foundId, *p.GetId(), graphScopes[*p.GetId()])
}
```

(I haven't run that code and it's probably mixed with other languages because I'm continuously changing languages lately)

**Comment by praetorian-thendrickson** [comment]
@baywet Thanks! That approach worked. 
I did have to slightly modify it by adding the app roles to the lookup table:
```golang
	for _, a := range principal.GetAppRoles() {
		graphScopes[*a.GetId()] = *a.GetValue()
	}

```
The lookup table needs the AppRoles to identify the "Application" type permissions, without it the "delegated" (oauth2) permissions are the only ones found.

<img width="817" alt="Screen Shot 2022-03-23 at 4 39 43 PM" src="https://user-images.githubusercontent.com/69640071/159797677-8739c633-8ee8-483b-a2e1-fcfd8afc085b.png">

(with the additional data in the lookup table)
<img width="796" alt="Screen Shot 2022-03-23 at 4 58 32 PM" src="https://user-images.githubusercontent.com/69640071/159797745-e3e121e2-9019-4e03-bf4e-ad81747899fe.png">

**Comment by baywet** [comment]
great news! can I go ahead and close this issue?

**Comment by praetorian-thendrickson** [comment]
yes, thanks for all the help!
