### ISSUE TITLE
Cannot paginate through users collection

### ISSUE THREAD

**Issue by henry739** [microsoftgraph/msgraph-sdk-go#118]
Encountered on msgraph-sdk-go v0.15.0 when attempting to support client-side pagination in a service using the SDK.

It is unclear how to paginate through the users collection using the SDK. `UsersRequestBuilderGetQueryParameters` takes an integer `Skip` value but according to [the docs](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http#optional-query-parameters) this is not supported. If I supply `$top` then a `nextLink` is returned but I cannot see a way to supply a `skipToken` query parameter.

Loving the SDK so far, but unsure how to progress on this one!

**Comment by baywet** [comment]
Hi @henry739 
Thanks for trying out the Go SDK and for reaching out.
I was wondering whether you saw [this page of documentation](https://docs.microsoft.com/en-us/graph/sdks/paging?context=graph%2Fapi%2F1.0&view=graph-rest-1.0&tabs=Go) ?

**Comment by henry739** [comment]
Hi @baywet and thanks for your response :)

I read through that page and I understand how I'd use it to iterate over all of the results in one go. I want to facade the MS Graph API for listing users, so that it matches our internal APIs (which allow pagination via a page size int, and an opaque token to retrieve the next chunk of results.) So I want to be able to resume pagination, as I would with the `oData.nextPage` token that gets returned. Is this possible?

**Comment by baywet** [comment]
Yep, it's exposed through the nextLink property on the response object.
https://github.com/microsoftgraph/msgraph-sdk-go/blob/e19065cdadffb3df0571564a4a512e098ed1b7d4/models/microsoft/graph/user_collection_response.go#L12

**Comment by henry739** [comment]
@baywet With the `nextLink` in hand, how would you use the SDK to obtain the next page of data?

**Comment by henry739** [comment]
That works perfectly @baywet - Thanks for taking the time to explain it, and apologies if this should have been obvious from the documentation.

**Comment by baywet** [comment]
Thanks for the feedback.
CC @jasonjoh on documenting how to use request builders with raw URLs to get serialization/deserialization/authentication/request execution for free... This pattern is across kiota SDKs and would be super valuable for something like delta where people need to store the deltalink
