### ISSUE TITLE
Cannot use "create user" example - missing functions

### ISSUE THREAD

**Issue by justDabuK** [microsoftgraph/msgraph-sdk-go#119]
## Context
Hi I'm trying to run the "create user" example from the [ms graph docs](https://docs.microsoft.com/en-us/graph/api/user-post-users?view=graph-rest-1.0&tabs=go#example-1-create-a-user)

The code is
```go
graphClient := msgraphsdk.NewGraphServiceClient(requestAdapter)

requestBody := msgraphsdk.NewUser()
accountEnabled := true
requestBody.SetAccountEnabled(&accountEnabled)
displayName := "Adele Vance"
requestBody.SetDisplayName(&displayName)
mailNickname := "AdeleV"
requestBody.SetMailNickname(&mailNickname)
userPrincipalName := "AdeleV@contoso.onmicrosoft.com"
requestBody.SetUserPrincipalName(&userPrincipalName)
passwordProfile := msgraphsdk.NewPasswordProfile()
requestBody.SetPasswordProfile(passwordProfile)
forceChangePasswordNextSignIn := true
passwordProfile.SetForceChangePasswordNextSignIn(&forceChangePasswordNextSignIn)
password := "xWwvJ]6NMw+bWH-d"
passwordProfile.SetPassword(&password)
options := &msgraphsdk.UsersRequestBuilderPostOptions{
	Body: requestBody,
}
result, err := graphClient.Users().Post(options)
```

the `msgraphsdk` import looks like

```go
import msgraphsdk "github.com/microsoftgraph/msgraph-sdk-go"
```

currently I'm using version `v0.16.0`

## My problem
I can't get the example running. The functions `NewUser`, `NewPasswordProfile` & `UserRequestBuilderPostOptions` are undefined. 

Is there maybe some import I'm missing or are these function maybe not a part of `msgraphsdk` but part of another package? 
Would be nice to get some help on this, especially since it feels like the fix will be trivial.

**Comment by baywet** [comment]
Hi @justDabuK ,
Thanks for trying the Go SDK and for reaching out.
You are right, the snippet generation process doesn't include accurate imports and this is something we should fix. (I'll log an issue in the snippets generation repo after this)
NewUser and NewPasswordProfile both come from `github.com/microsoftgraph/msgraph-sdk-go/models/microsoft/graph`
UserRequestBuilderPostOptions  comes from `github.com/microsoftgraph/msgraph-sdk-go/users`

I hope this helps, let us know if you have further questions.

**Comment by justDabuK** [comment]
Hi @baywet,

That helped 👍🏽 
Thanks for answering that quick 🙏🏽

**Comment by baywet** [comment]
no worries, closing since your question is answered.
