### ISSUE TITLE
Example in the README doesn't work

### ISSUE THREAD

**Issue by elliotpeele** [microsoftgraph/msgraph-sdk-go#121]
The auth module mentioned in the example in the README doesn't appear to exist:

github.com/microsoft/kiota/authentication/go/azure

Looking at the [README](https://github.com/microsoft/kiota/tree/main/authentication) in that repository, points to:

https://github.com/microsoft/kiota-authentication-azure-go/

**Comment by elliotpeele** [comment]
Looks like the code was migrated to a different repository a few days ago. I was able to make progress by specifying  an older rev of the kiota project.

go get github.com/microsoft/kiota@6ddd035d04bc9135c26ae733c19798acf71f5fe7

**Comment by baywet** [comment]
Hi @elliotpeele 
Thanks for trying out the Go SDK and for reaching out.
You are correct, the sample was out of date. We're in the process of moving the kiota dependencies to their own repository in preparation for the general availability of this SDK. And unfortunately you got caught in between the move.

#122 fixes this issue by updating the references and the documentation, once it'll be merged it'll close this issue.
Don't hesitate to reach out again if you have further suggestions.
