### ISSUE TITLE
Query Parameters are not working due to missing $ prefix in logic

### ISSUE THREAD

**Issue by tommed** [microsoftgraph/msgraph-sdk-go#130]
As mentioned in #114, `AddQueryParameters` which sets the $search, $expand, $top, $skip etc. in `github.com/microsoft/kiota-abstractions-go@v0.3.0/request_information.go` is using reflection to name the parameters which you are adding to your URLs in all API calls (e.g. `(m *UsersRequestBuilder) CreateGetRequestInformation(options *UsersRequestBuilderGetOptions)`).

Unfortunately you need to inject some additional logic as the MS Graph query parameters require the `$` ODATA prefix.

This means no API calls work as soon as you supply query parameters (so no paging, no filtering, no field fetching) otherwise you get an error like:

> Request_BadRequest: Unrecognized query argument specified: 'top,skip'.: error status code received from the API

I believe you should be able to fix this inside this library - the logic in `microsoft/kiota-abstractions-go` isn't wrong, you just can't use the final results in this library because of MS graph API / OData requirements for the $ prefix.

**Comment by tommed** [comment]
Example of braking code:

```golang
var offset int32 = 0
var pageSize int32 = 1
res, err := c.graph.Users().Get(&users.UsersRequestBuilderGetOptions{
  QueryParameters: &users.UsersRequestBuilderGetQueryParameters{
    Select: models.AzureADSelectFields,
    Expand: models.AzureADExpandFields,
    Skip: &offset,
    Top:  &pageSize,
  },
})
```

**Comment by baywet** [comment]
Hi @tommed 
Thanks for reaching out and for trying the Go SDK.
You are correct, we made some changes to the way special characters are handled in parameter names and it seems that during the last generation a misalignment happened.
https://github.com/microsoftgraph/msgraph-sdk-go/blob/8bfa602837fa40bb4c46f92a57e6271682ccaf1e/users/users_request_builder.go#L47

Should have a tag like this `uriparametername:"%24select"`.

I've just triggered a new generation to try and remediate this issue.

**Comment by baywet** [comment]
Update: just merged the pull request that addresses the issue. Running `go get github.com/microsoftgraph/msgraph-sdk-go@v0.19.0` should resolve the issue for you.

**Comment by tommed** [comment]
I think this has broken something else now.. just collecting details, but are there not any unit tests to validate the builds before release?

**Comment by tommed** [comment]
Same code as above now breaks internally:

> code = "InternalServerError" message = "Unable to find target address"

using v0.19.0

**Comment by tommed** [comment]
Sorry, the subsequent test took out the `$skip` (though it seems odd the API to list all users cannot be paged and only a maximum of 999?).

```golang
var pageSize int32 = 999
var expandFields = []string {
  "manager",
  "memberOf",
  "photo",
}
var selectFields = []string {
  "id",
  "businessPhones",
  "city",
  "companyName",
  "country",
  "department",
  "employeeId",
  "employeeType",
  "displayName",
  "givenName",
  "jobTitle",
  "mail",
  "officeLocation",
  "surname",
  "userPrincipalName",
  "accountEnabled",
}
apiResp, err := c.graph.Users().Get(&users.UsersRequestBuilderGetOptions{
  QueryParameters: &users.UsersRequestBuilderGetQueryParameters{
    Expand:  expandFields,
    Select:  selectFields,
    Orderby: []string{"userPrincipalName"},
    Top:     &pageSize,
    //Skip:   &offset, // <~ not supported?!?!
  },
})
```

Yields the error:

> InternalServerError: Unable to find target address: error status code received from the API

**Comment by baywet** [comment]
Paging for those APIs can be achieved through the nextLink/skip token paradigm. Instead of implementing it yourself, you can [leverage the page iterator the SDK provides](https://docs.microsoft.com/en-us/graph/sdks/paging?tabs=Go)

The error message you're getting still indicates you're signing in with a personal account. Can you double check this aspect please?

**Comment by tommed** [comment]
I'm using an Application's identity (Client ID and certificate/private key) via:

```golang
// parse certs manually as SDK does not support ENCRYPTED PRIVATE KEY:
cert, key, err := parseCertificates(cfg.CertificatePEM, cfg.PrivateKeyPEM, cfg.CertificatePassword)

// build credential using client ID and cert against this tenant
cred, err := azidentity.NewClientCertificateCredential(cfg.TenantID, cfg.ClientID, cert, key, nil)

// now we need various adapters
authAdapter, err = a.NewAzureIdentityAuthenticationProvider(cred)
graphAdapter, err := msgraph.NewGraphRequestAdapter(authAdapter)

// now create graph client
graph := msgraph.NewGraphServiceClient(graphAdapter)
```

**Comment by tommed** [comment]
> Paging for those APIs can be achieved through the nextLink/skip token paradigm. Instead of implementing it yourself, you can [leverage the page iterator the SDK provides](https://docs.microsoft.com/en-us/graph/sdks/paging?tabs=Go)
> 
> The error message you're getting still indicates you're signing in with a personal account. Can you double check this aspect please?

Thanks. Re. your paging suggestion, I managed to get this working with the code from [here](https://github.com/microsoftgraph/msgraph-sdk-go/issues/106#issuecomment-1068330761) as the documentation doesn't work atm, it shows `graph.CreateMessageCollectionResponseFromDiscriminatorValue` coming from `"github.com/microsoftgraph/msgraph-sdk-go/models/microsoft/graph"` whereas it should actually be `models.CreateUserCollectionResponseFromDiscriminatorValue` coming from `models "github.com/microsoftgraph/msgraph-sdk-go-core"`.

**Comment by tommed** [comment]
Perfect thanks. I'll be able to test this out once I'm not getting the main error anymore.

> > InternalServerError: Unable to find target address: error status code received from the API

**Comment by tommed** [comment]
I've also tried this with the following auth. mechanism and it does the same:

```golang
cred, err := azidentity.NewClientSecretCredential(cfg.TenantID, cfg.ClientID, cfg.ClientSecret, nil)
authAdapter, err = a.NewAzureIdentityAuthenticationProvider(cred)
```

**Comment by baywet** [comment]
which one did you check while registering your app?
![image](https://user-images.githubusercontent.com/7905502/163434246-b29e5350-8bf0-4a88-8f19-ecae854f3795.png)

**Comment by tommed** [comment]
> which one did you check while registering your app?
> 
> ![image](https://user-images.githubusercontent.com/7905502/163434246-b29e5350-8bf0-4a88-8f19-ecae854f3795.png)
> 
> 

The top option. Only want to access the single tenant.

**Comment by baywet** [comment]
just double checking you're using the client id and the tenant id, not the object id.

![image](https://user-images.githubusercontent.com/7905502/163436197-3f211e3e-db91-4122-ae0d-b248cc3a29b9.png)

**Comment by tommed** [comment]
I will check tomorrow morning.

**Comment by tommed** [comment]
Just to confirm, this was authenticating until I pulled the 0.19.0 update, which is the first occurrence of this error.

I can also confirm the correct Client ID and Tenant ID are being used:

![Screenshot 2022-04-19 at 09 44 59](https://user-images.githubusercontent.com/13066/163963267-4821189b-3281-4443-83b9-52f961bc0e20.png)

From our system:

![Screenshot 2022-04-19 at 09 47 55](https://user-images.githubusercontent.com/13066/163963443-bdcc4f44-1153-4738-b913-60729de43155.png)

So I suspect the problem is related to something changed by the 0.18.0 ~> 0.19.0 release.

**Comment by tommed** [comment]
What is `nativeClient` for? You don't appear to be using it in the example

**Comment by baywet** [comment]
sorry, I meant this

```diff
-resp, err := http.Get(targetUrl.String())
+resp, err := nativeClient.Get(targetUrl.String())
```

**Comment by tommed** [comment]
Regardless, I've traced the request templating in the higher order code (see my example) and can confirm the request is being generated as follows:

```
HTTP/1.1
GET https://graph.microsoft.com/v1.0/users
```

You can also see the parameters are being generated correctly:

![Screenshot 2022-04-19 at 14 49 43](https://user-images.githubusercontent.com/13066/164018673-3b25055f-0cff-41d4-8604-259fd6bb0edb.png)

This is then passed into `return (*a.httpClient).Do(request)` so effectively using the standard `http` library.

The response is as I have described:

![Screenshot 2022-04-19 at 14 51 04](https://user-images.githubusercontent.com/13066/164019003-481e6f46-5642-4fca-ae03-aeb4cb60c24e.png)

Given the `a.authenticationProvider.AuthenticateRequest(requestInfo)` is not returning an error as a pre-guard, does anything in the `http.Request` information provided show the cause?

**Comment by tommed** [comment]
`%24top=999&%24orderby=userPrincipalName&%24select=id%2CbusinessPhones%2Ccity%2CcompanyName%2Ccountry%2Cdepartment%2CemployeeId%2CemployeeType%2CdisplayName%2CgivenName%2CjobTitle%2Cmail%2CofficeLocation%2Csurname%2CuserPrincipalName%2CaccountEnabled&%24expand=manager%2CmemberOf%2Cphoto`

**Comment by tommed** [comment]
Interestingly, a call to `c.graph.Applications().Get(nil)` with `Application.Read.All` permission granted and approved works fine. So it's related specifically to the `c.graph.Users().Get(...)` call despite the error message suggesting this is some kind of addressing issue. Wonder if it's just a badly worded error?

**Comment by baywet** [comment]
removing photo and memberOf in the expand clause make the call work.

## Photo

This property is effectively store on SharePoint or Exchange on the backend where the rest of the user object is in AAD if I remember right, even though it's not [called out this way](https://docs.microsoft.com/en-us/graph/known-issues#query-parameters) cross service expands don't always work in Microsoft Graph. The error message from the API should have been more explicit though.

## MemberOf

Apparently identity services limit queries to one expand field, I wasn't aware of that.

So effectively the SDK is "doing the right thing", those are service side limitations.

**Comment by tommed** [comment]
So if I want to get `company` and `memberOf` for all matching results, it just can't do this?

**Comment by tommed** [comment]
Also, documents are still wrong as you're casting to the model and not a pointer to the model:

```golang
message := pageItem.(graph.Message)

// should be a pointer cast
if message, ok := pageItem.(*graph.Message); ok {
   // ...
}
```

**Comment by baywet** [comment]
I'm not sure, at this point the best course of actions for you would be to post in the [Microsoft Graph identity Q&A forum](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-identity.html) the service team will be able to assist you.
When asking questions there, it's better to simply ask about the URL/request, not to mention any language.

For the sample, do you have a link? We've recently updated those (see #135), see the updated version https://github.com/microsoftgraph/msgraph-sdk-go#41-get-all-the-users-in-an-environment

(it now uses interfaces to support upcast)

**Comment by tommed** [comment]
In your link you are using `models.CreateUserCollectionResponseFromDiscriminatorValue` but you aren't casting to `models.User` anymore, you're casting to `models.Userable`?

The previous documentation you linked for me (above) case to `models.Message` etc. I tried to use `models.User` in my example but realised this didn't work because it's actually a `*models.User` (obviously to conform to the interface).

If the documentation is using the more abstract version, it will work too - just surprising!

Generally, if you don't mind me saying, this library seems to be incredibly complex and not at all `golang`-y. Seems like an awful lot of dependencies and time taken to build when it's a fairly straight forward odata http RESTful service. Would be nice to see a proper go-first implementation rather than something code-generated and similar across all languages regardless of their own language paradigms. Just a thought, feel free to close this ticket. Thanks for all the attention.

**Comment by baywet** [comment]
> In your link you are using models.CreateUserCollectionResponseFromDiscriminatorValue but you aren't casting to models.User anymore, you're casting to models.Userable?

Correct. Is your concern about the User part of the method name and the Userable cast? This is expected by conventions.


> If the documentation is using the more abstract version, it will work too - just surprising!

[the public docs](https://docs.microsoft.com/en-us/graph/sdks/paging?context=graph%2Fapi%2F1.0&view=graph-rest-1.0&tabs=Go) also have been updated, unless I'm missing something in this comment?

> Generally, if you don't mind me saying, this library seems to be incredibly complex and not at all golang-y. Seems like an awful lot of dependencies and time taken to build when it's a fairly straight forward odata http RESTful service. Would be nice to see a proper go-first implementation rather than something code-generated and similar across all languages regardless of their own language paradigms

This kind of feedback is precious for us to "get it right". It's not specific enough though. Do you have specific examples about what doesn't feel idiomatic and what you'd expect instead?

**Comment by tommed** [comment]
I've written something instead internally which calls the msgraph api, and another package for specifics relating to Azure AD - so feel free to close this ticket. It was only half a day's work because the API is so simple - so appreciate that! 🙏  thanks

**Comment by meain** [comment]
This seems like a related issue. Not sure if it a problem with just the client though. I am trying to pull files from OneDrive with a select query. From the logs, this looks like the query that is being fired:

```
https://graph.microsoft.com/v1.0/drives/<drive-id>/root/microsoft.graph.delta()?$select=id%2C%40content.downloadUrl
```

This gives me just the `id` (plus `@odata.type` and `@odata.etag`), but the `content.downloadUrl` is not available. With the `$` removed from `$select` it works as expected.
