### ISSUE TITLE
Page Iteration Example call for Graph Model Package

### ISSUE THREAD

**Issue by dadams39** [microsoftgraph/msgraph-sdk-go#135]
In the tutorial found at: https://docs.microsoft.com/en-gb/graph/sdks/paging?tabs=Go, the example gives instructions for printing out parts of a message. 

When running the command: `go get github.com/microsoftgraph/msgraph-sdk-go/models/microsoft/graph`, this is the result:

> go: module github.com/microsoftgraph/msgraph-sdk-go@upgrade found (v0.19.1), but does not contain package github.com/microsoftgraph/msgraph-sdk-go/models/microsoft/graph

The outcome is consistent with the current state of the repository. However, the current documentation does not provide insight on how to save a full struct effectively. (e.g. Mail: How to create a message object, Calendar: How to create a calendar appointment object)

**Comment by baywet** [comment]
Hi @dadams39 
Thanks for trying the Go SDK and for reaching out.

For the first part of the question, we're not expecting you to have to install anything else for paging as long as you have installed `github.com/microsoftgraph/msgraph-sdk-go`, then it's just a matter of import paths in the code. Did something in the current documentation lead you to think you needed to install additional packages?

As for the second part of the question, I'm not sure I understand it, can you elaborate please?

**Comment by dadams39** [comment]
@baywet,

Thanks for getting back so quickly. The Paging code:
```go=
import (
    msgraphcore "github.com/microsoftgraph/msgraph-sdk-go-core"
    "github.com/microsoftgraph/msgraph-sdk-go/me/messages"
    "github.com/microsoftgraph/msgraph-sdk-go/models/microsoft/graph"
)

query := messages.MessagesRequestBuilderGetQueryParameters{
    Select: []string{"body", "sender", "subject"},
}

options := messages.MessagesRequestBuilderGetOptions{
    Headers: map[string]string{
        "Prefer": "outlook.body-content-type=\"text\"",
    },
    QueryParameters: &query,
}

result, err := client.Me().Messages().Get(&options)

// Initialize iterator
pageIterator, err := msgraphcore.NewPageIterator(result, adapter, graph.CreateMessageCollectionResponseFromDiscriminatorValue)

// Any custom headers sent in original request should also be added
// to the iterator
pageIterator.SetHeaders(options.Headers)

// Iterate over all pages
iterateErr := pageIterator.Iterate(func(pageItem interface{}) bool {
    message := pageItem.(graph.Message)
    fmt.Printf("%s\n", *message.GetSubject())
    // Return true to continue the iteration
    return true
})
```
The message assignment, `message:=` is not possible because `"github.com/microsoftgraph/msgraph-sdk-go/models/microsoft/graph"` does NOT exist. 
My question -> What is the working code to be able to perform the above?

**Comment by baywet** [comment]
Right, sorry, we've made a couple of improvements and forgot to update the documentation

the import should be
`github.com/microsoftgraph/msgraph-sdk-go/models/`

and this line should be

**Comment by dadams39** [comment]
@baywet ,
The above was helpful, but incorrect. The code snippet should show that all references to `graph` should be moved to `models`.

I've verified that the code works as of today's date.

```
 pageIterator, err := msgraphcore.NewPageIterator(result, adapter, models.CreateMessageCollectionResponseFromDiscriminatorValue)

    // Any custom headers sent in original request should also be added
    // to the iterator
    pageIterator.SetHeaders(options.Headers)

    // Iterate over all pages
    iterateErr := pageIterator.Iterate(func(pageItem interface{}) bool {
        message := pageItem.(models.Messageable)
        fmt.Printf("%s\n", *message.GetSubject())
        // Return true to continue the iteration
        return true
    })
 ```

**Comment by baywet** [comment]
@dadams39 thanks for pointing this out. Would you mind submitting a pull request for the snippet on the readme of this repo please? I'll then replicate to the beta and public docs repos.

**Comment by dadams39** [comment]
Complete:
https://github.com/microsoftgraph/microsoft-graph-docs/pull/16555

**Comment by baywet** [comment]
thank you so much for putting this pull request together. Reviewed it so it moves along in the pipeline. Also reflected the changes in the readme for this and the beta repo.
