### ISSUE TITLE
Serialization Method requires clarification

### ISSUE THREAD

**Issue by dadams39** [microsoftgraph/msgraph-sdk-go#140]
# How can SDK be used to write retrieved items? 
In the code example: https://docs.microsoft.com/en-gb/graph/sdks/paging?tabs=Go

The snippet highlights how to receive each Message from the Mailbox. Messages are defined [here][]

The [SerializationWriter Interface](https://github.com/microsoft/kiota-abstractions-go/blob/main/serialization/serialization_writer.go) is defined within Kiota abstractions, but it is unclear which how to save a particular message to an app.
Code is adapted from provided code above:
```
target := "My Message"
// Iterate over all pages (e.g. Messages)
iterateErr := pageIterator.Iterate(func(pageItem interface{}) bool {
    message := pageItem.(models.Messageable)
    fmt.Printf("%s\n", *message.GetSubject())
    if target == *message.GetSubject() {
        entries := message.GetFieldDeserializers(). // MAP Key: <string> Type: func(serialization.ParseNode) error
        for key, value := in range entries{
            // NEED CODE FOR HERE
            val() // NOT VALID     
    // Return true to continue the iteration
    return true
})
```
How do you get the value out of the value?
Golang produces the following error:
```
not enough arguments in call to val
        have ()
        want (serialization.ParseNode)
```

This item can be considered closed when the following items have been completed:
- [x] Instruction on serialization has been verified
- [x] Instruction on importing objects has been verified
Documentation will have to wait until the design team specifies where the code snippets should live.

**Comment by dadams39** [comment]
I was unable to get a satisfactory answer for using the map[string] interface() shown here:
```
message := pageItem.(models.Messageable)
    fmt.Printf("%s\n", *message.GetSubject())
    if target == *message.GetSubject() {
        entries := message.GetFieldDeserializers(). // MAP Key: <string> Type: func(serialization.ParseNode) error
        for key, value := in range entries{
            // NEED CODE FOR HERE
            val() // NOT VALID     
    // Return true to continue the iteration that I was able to turn up. 
```
I include a snippet on how to use the SerializationWriter. However, I will post in the Serialization Library as the documentation is actually incorrect. 
```
 writerRegistry := adapter.GetSerializationWriterFactory() // Returns SerializationWriterFactoryRegistry
    myWriter, err := writerRegistry.GetSerializationWriter("application/json")
    if err != nil{
        fmt.Printf("Unable to retrieve writer: %v\n", err)
    }
    iterateErr := pageIterator.Iterate(func(pageItem interface{}) bool {
        message := pageItem.(models.Messageable)
        fmt.Printf("%s\n", *message.GetSubject())
        message.Serialize( myWriter )
        return true
    })
    if iterateErr != nil{
        fmt.Println("Iterator failed")
    }

    mailBytes, _ := myWriter.GetSerializedContent() // ([]byte, error)
    fmt.Println( string( mailBytes ) )
```

**Comment by dadams39** [comment]
The adapter implements RequestAdapter interface which contains the `GetSerializationWriterFactory`
```
type RequestAdapter interface {
	// SendAsync executes the HTTP request specified by the given RequestInformation and returns the deserialized response model.
...
	// GetSerializationWriterFactory returns the serialization writer factory currently in use for the request adapter service.
	GetSerializationWriterFactory() s.SerializationWriterFactory
```
The call should return a WriterFactory. However, the SDK's version is a SerializationWriterFactoryRegistry containing two types of writers.  I'm not sure how you would address the documentation in this regard.

**Comment by baywet** [comment]
Hi @dadams39,
Thanks for reaching out and for trying the go sdk.
If I understand things correctly, you're trying to serialize a model object into a Json formated value, correct?
If so you're on the right track, I'm just not understating the comment about the two types of factories?

**Comment by dadams39** [comment]
@baywet 
The two types of factories are in regards to the `s.SerializationWriterFactory` that exists as a value of the RequestAdapter. When a request adapter is created with the following method, ` NewGraphRequestAdapter(auth)`, the MSGraph_API returns with an adapter with not a factory, but a Registry. I find this to be true, because if you call adapter.GetSerializationWriterFactory().GetValidContentType() The return is 
 ```"the registry supports multiple content types. Get the registered factory instead"```
 
 The adapter when called has an `application/json` and a `plain/text` writer.  If the return was a single SerializationWriter within the adapter, it would have received 
 ```
 GetValidContentType() (string, error)
	// GetSerializationWriter returns the relevant SerializationWriter instance for the given content type
```
There would have been a single string returned. I am pointing out that the documentation does not match the reality. However, I think that receiving multiple writers is probably a good thing.

**Comment by dadams39** [comment]
@baywet 
> If I understand things correctly, you're trying to serialize a model object into a Json formated value, correct?
If so you're on the right track
In Issue #148, I was trying to bring an object from a file into my app utilizing the Parseable interface into a Message Item. However, I get a failure during this process. Being that I had saved the object with the provided writer, it is unclear why the process failed. Do you think we should reopen this issue?

**Comment by baywet** [comment]
Thanks for clarifying.

It's actually the client that registers the factories to the registry when it's instantiated. So if you're trying to access those before newing the client, this is why you aren't getting anything.

https://github.com/microsoftgraph/msgraph-sdk-go/blob/0b6b364c2747bf9190f5b2dc2a5417ac5eaeb0c1/graph_service_client.go#L282

Alternatively you can pass your own factory/registry when creating the request adapter.
https://github.com/microsoft/kiota-http-go/blob/334b4e5a8df84ba1a646dff2e02a47fb31a1b5cb/nethttp_request_adapter.go#L48

**Comment by baywet** [comment]
As per your latest comment (we were writing at the same time), if you want to persist objects to storage and re-hydrate them using the serialization writer/parse node infrastructure, it should be supported and symmetric.
When running into issues with those, try to narrow down the behaviour to the code that belongs to https://github.com/microsoft/kiota-serialization-json-go as this is where the fix is most likely to be needed.

**Comment by dadams39** [comment]
I think the description and answer provided in the Discussion https://github.com/microsoftgraph/msgraph-sdk-go/discussions/141 thread addresses the correct way to direct objects to storage and re-hydrate them. I'm not exactly sure what part of the ParseNode factory is failing during the steps. 

The description of the SerializationWriter Factory Interface may not align with my expectations of it; however, I do believe that if the example provided is placed somewhere in the documentation, this would clarify any misunderstandings.

**Comment by baywet** [comment]
are you referring to an example specific to this scenario? or on how to use the different types?

**Comment by dadams39** [comment]
@baywet 
Are you referring to this statement:
>  I'm not exactly sure what part of the ParseNode factory is failing during the steps.


Yes, I am not sure exactly how the ParseNode is failing during the statement as I posted in https://github.com/microsoftgraph/msgraph-sdk-go/discussions/141, but I will create an Issue in https://github.com/microsoft/kiota-serialization-json-go.

**Comment by dadams39** [comment]
Serialization and Hydration steps described in Discussion https://github.com/microsoftgraph/msgraph-sdk-go/discussions/141. The failure for the importation step is caused by the SerializationWriter see: https://github.com/microsoft/kiota-serialization-json-go/issues/11

Tasks complete and thread closed.
