### ISSUE TITLE
Parse Node Failure from Original Serialized Bytes

### ISSUE THREAD

**Issue by dadams39** [microsoftgraph/msgraph-sdk-go#148]
In my investigation into Issue https://github.com/microsoftgraph/msgraph-sdk-go/issues/140, I have found acceptable SerializationWriter and ParseNode implementations reside in the following [repository](https://github.com/microsoft/kiota-serialization-json-go).

My general understanding of the two abstractions is that the writer should transform a msgraph object into readable bytes and the parse node should be able to take the said bytes and read them back into objects that msgraph-API
can understand. The process of that relationship I will describe below to
highlight the errors I am receiving:

- If the writer is calls `GetSerializedContent()` after an _Outlook_Itemable_
  has called `serialize(<writer>)`, this returns a byte array.
- A Parse Node can be created using the returned byte array, `NewJsonParseNode(
  returnedArray )`
- At this point, the ParseNode should have all of the values in the original
  values stored within it. To verify, the call
  `aNode.GetByteArrayValue()` will return `([]byte, error)`.
- This results in an error of: `illegal base64 data at input byte 0`.

As there are no concrete examples of how to leverage the relationships between the parse node and the writer, it is possible that I have misunderstood their implementation. I used this conversion using the following code:

```go
   myWriter := js.NewJsonSerializationWriter()
   count := 0
    iterateErr := pageIterator.Iterate(func(pageItem interface{}) bool {
        message := pageItem.(models.Messageable)
        fmt.Printf("%s\n", *message.GetSubject())
        if count == 7 {
            message.Serialize( myWriter )
        }
        count ++
        return true
    })
    if iterateErr != nil{
        fmt.Println("Iterator failed")
    }

    mailBytes, _ := myWriter.GetSerializedContent() // ([]byte, error)
    aMessage, err := js.NewJsonParseNode(mailBytes)
    if err != nil{
        fmt.Printf("Describe ParseNode Fail: %v\n", err)
    }
    verifyArray, err :=  aMessage.GetByteArrayValue() //Err:  illegal base64 data at input byte 0
    if err != nil{
        fmt.Printf("Describe Byte Parse Fail: %v\n", err)
    }
```

Please advise if this is indeed an error within the implementation or if the steps
are lacking.

**Comment by baywet** [comment]
Closing this one as this is the third issue for the same question and I believe spreading the conversation over multiple issues is adding to the confusion at this point.
If you could clarify the intent of what you're trying to achieve, it would help understand the scenario. Thanks
