### ISSUE TITLE
Importing msgraph-sdk-go/models causes `go mod tidy` to fail

### ISSUE THREAD

**Issue by henry739** [microsoftgraph/msgraph-sdk-go#152]
Given a package with the following imports:

```
msgraph "github.com/microsoftgraph/msgraph-sdk-go"
"github.com/microsoftgraph/msgraph-sdk-go/models/microsoft/graph"
msgraph_errors "github.com/microsoftgraph/msgraph-sdk-go/models/microsoft/graph/odataerrors"
msusers "github.com/microsoftgraph/msgraph-sdk-go/users"
msusersitem "github.com/microsoftgraph/msgraph-sdk-go/users/item"
```

I currently have my version of msgraph-sdk-go pinned at v0.15.0 and `go mod tidy` succeeds.

But when I add imports for the following packages:
```
msgraphcore "github.com/microsoftgraph/msgraph-sdk-go-core"
"github.com/microsoftgraph/msgraph-sdk-go/models"
```

Running `go mod tidy` fails, complaining about two of the existing packages not existing in an unpinned version of msgraph-sdk-go that it downloaded.
```
go: downloading github.com/microsoftgraph/msgraph-sdk-go v0.21.0
go: found github.com/microsoftgraph/msgraph-sdk-go/models in github.com/microsoftgraph/msgraph-sdk-go v0.21.0
go: downloading github.com/microsoftgraph/msgraph-sdk-go-core v0.23.0
go: downloading github.com/microsoft/kiota-abstractions-go v0.4.0
go: downloading github.com/microsoft/kiota-serialization-json-go v0.3.0
go: downloading github.com/microsoft/kiota-serialization-text-go v0.2.0
go: downloading github.com/microsoft/kiota-http-go v0.3.0
go: downloading github.com/yosida95/uritemplate/v3 v3.0.2
go: downloading github.com/cjlapao/common-go v0.0.19
go: finding module for package github.com/microsoftgraph/msgraph-sdk-go/models/microsoft/graph
go: finding module for package github.com/microsoftgraph/msgraph-sdk-go/models/microsoft/graph/odataerrors
me.com/our/package imports
        github.com/microsoftgraph/msgraph-sdk-go/models/microsoft/graph: module github.com/microsoftgraph/msgraph-sdk-go@latest found (v0.21.0), but does not contain package github.com/microsoftgraph/msgraph-sdk-go/models/microsoft/graph
me.com/our/package imports
        github.com/microsoftgraph/msgraph-sdk-go/models/microsoft/graph/odataerrors: module github.com/microsoftgraph/msgraph-sdk-go@latest found (v0.21.0), but does not contain package github.com/microsoftgraph/msgraph-sdk-go/models/microsoft/graph/odataerrors
```

I have tried this with both Go 1.17 and Go 1.18. Please can you advise how to resolve this issue, or if its a known issue with the package versioning?

**Comment by baywet** [comment]
Hi @henry739,
Thanks for reaching out and for trying the Go SDK.
A couple of weeks ago, we've made a change where most of the models are now directly under /models and not /models/something to simplify the experience.
It seems that it was missed in the release notes [which I just updated](https://github.com/microsoftgraph/msgraph-sdk-go/releases/tag/v0.19.0)

Updating your code import from:
- "github.com/microsoftgraph/msgraph-sdk-go/models/microsoft/graph" to "github.com/microsoftgraph/msgraph-sdk-go/models"
- "github.com/microsoftgraph/msgraph-sdk-go/models/microsoft/graph/odataerrors" to "github.com/microsoftgraph/msgraph-sdk-go/models/odataerrors"

Then updating the SDK reference to latest
And finally running go mod tidy.
Should solve the issue.

Let us know if you have any further question.
