### ISSUE TITLE
Delete method missing for `applications`, `serviceprincipals`

### ISSUE THREAD

**Issue by aramase** [microsoftgraph/msgraph-sdk-go#16]
Support [Delete Application](https://docs.microsoft.com/en-us/graph/api/application-delete?view=graph-rest-1.0&tabs=http) and [Delete ServicePrincipal](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-delete?view=graph-rest-1.0&tabs=http) with the sdk.

**Comment by baywet** [comment]
Can you share the fluent Api path you're trying to locate the method under?

**Comment by aramase** [comment]
I'm looking for the method here: https://pkg.go.dev/github.com/microsoftgraph/msgraph-sdk-go@v0.1.1/applications?utm_source=gopls#pkg-functions but didn't find any.

**Comment by baywet** [comment]
Sorry my question wasn't clear.
It should be under

Client.ApplicationsById(id).Delete()

**Comment by aramase** [comment]
Ah, I see it! thank you.

**Comment by baywet** [comment]
FYI we're working on getting snippets in the documentation, you can check what we have here https://github.com/microsoftgraph/microsoft-graph-docs/pull/14859
