### ISSUE TITLE
Cast DirectoryObjectable to User

### ISSUE THREAD

**Issue by Mattes83** [microsoftgraph/msgraph-sdk-go#161]
Hi,

I am currently trying to use this library to get all members of a group.

As I did not find any documentation on how to use the results of the queries I looked into the issues and found a snippet in #79:

> ```go
> // response is a directory object response like for client.GroupsById("id").Members.Get(nil), where the value array is an array of directory objects
> // m is the import for the models package
> for _, do := range response.GetValue() {
> 		user := do.(m.Userable)
> 		upn := user.GetUserPrincipalName()
> 		fmt.Printf("UPN: %v\n", *upn)
> 	}
> ```

Should this work by now? When I try 

```go
if result, err := r.GraphServiceClient.GroupsById(objectID.String()).TransitiveMembers().Get(); err == nil {
  for _, do := range result.GetValue() {
    user := do.(models.Userable)
    upn := user.GetUserPrincipalName()
    logger.Info(*upn)
}
```

I get a panic because do cannot be cast to models.Userable

Best regards

**Comment by baywet** [comment]
Hi @Mattes83 ,
Thanks for reaching out and for trying the Go SDK.
Groups can technically contain other object types than just Users (hence why the collection is of type directory object).
Checking the type assertion completed successfully would allow your application to avoid a panic,

```golang
if result, err := r.GraphServiceClient.GroupsById(objectID.String()).TransitiveMembers().Get(); err == nil {
  for _, do := range result.GetValue() {
    user, ok := do.(models.Userable)
    if ok {
       upn := user.GetUserPrincipalName()
       logger.Info(*upn)
    } else {
       logger.Info("found a " + do.GetAdditionalData()["@odata.type"] + " object")
    }
}
```

Also, which version of the SDK are you using? the automatically downcast of values based on their odata type was implemented recently, you might want to upgrade if you're not on latest.

**Comment by Mattes83** [comment]
Hi, 
thanks for your response. I am using v0.22.0.
Yes, there is a mix of users and groups in the directory.
I changed the code to 

```go
func extractUsers(dos []models.DirectoryObjectable, logger logr.Logger) Users {
	users := make([]User, 0, len(dos))
	for _, do := range dos {
		user, ok := do.(models.Userable)
		if ok {
			upn := user.GetUserPrincipalName()
			logger.Info(*upn)
		} else {
			t, ok := do.GetAdditionalData()["@odata.type"].(*string)
			if ok {
				logger.Info(fmt.Sprintf("found a %v object", *t))
			}
		}
	}
}
```

It returns
    client.go:138: "level"=0 "msg"="found a #microsoft.graph.group object" "objectID"="65534408-fb98-43a2-84ca-a9ad5ebbccc6"
    client.go:138: "level"=0 "msg"="found a #microsoft.graph.user object" "objectID"="65534408-fb98-43a2-84ca-a9ad5ebbccc6"
    client.go:138: "level"=0 "msg"="found a #microsoft.graph.user object" "objectID"="65534408-fb98-43a2-84ca-a9ad5ebbccc6"
    client.go:138: "level"=0 "msg"="found a #microsoft.graph.user object" "objectID"="65534408-fb98-43a2-84ca-a9ad5ebbccc6"
    client.go:138: "level"=0 "msg"="found a #microsoft.graph.group object" "objectID"="65534408-fb98-43a2-84ca-a9ad5ebbccc6"
    client.go:138: "level"=0 "msg"="found a #microsoft.graph.user object" "objectID"="65534408-fb98-43a2-84ca-a9ad5ebbccc6"
    client.go:138: "level"=0 "msg"="found a #microsoft.graph.user object" "objectID"="65534408-fb98-43a2-84ca-a9ad5ebbccc6"
    client.go:138: "level"=0 "msg"="found a #microsoft.graph.user object" "objectID"="65534408-fb98-43a2-84ca-a9ad5ebbccc6"
    client.go:138: "level"=0 "msg"="found a #microsoft.graph.user object" "objectID"="65534408-fb98-43a2-84ca-a9ad5ebbccc6"
    client.go:138: "level"=0 "msg"="found a #microsoft.graph.user object" "objectID"="65534408-fb98-43a2-84ca-a9ad5ebbccc6"
    client.go:138: "level"=0 "msg"="found a #microsoft.graph.group object" "objectID"="65534408-fb98-43a2-84ca-a9ad5ebbccc6"
    client.go:138: "level"=0 "msg"="found a #microsoft.graph.user object" "objectID"="65534408-fb98-43a2-84ca-a9ad5ebbccc6"
    client.go:138: "level"=0 "msg"="found a #microsoft.graph.user object" "objectID"="65534408-fb98-43a2-84ca-a9ad5ebbccc6"
    client.go:138: "level"=0 "msg"="found a #microsoft.graph.user object" "objectID"="65534408-fb98-43a2-84ca-a9ad5ebbccc6"
    client.go:138: "level"=0 "msg"="found a #microsoft.graph.user object" "objectID"="65534408-fb98-43a2-84ca-a9ad5ebbccc6"
    client.go:138: "level"=0 "msg"="found a #microsoft.graph.group object" "objectID"="65534408-fb98-43a2-84ca-a9ad5ebbccc6"
    client.go:138: "level"=0 "msg"="found a #microsoft.graph.user object" "objectID"="65534408-fb98-43a2-84ca-a9ad5ebbccc6"
    client.go:138: "level"=0 "msg"="found a #microsoft.graph.user object" "objectID"="65534408-fb98-43a2-84ca-a9ad5ebbccc6"

and the breakpoint at GetUserPrincipalName is not hit.

I have no clue whats wrong here :(

Best regards

**Comment by baywet** [comment]
thanks for the additional information.
The code of your application is correct, after digging a little further it seems the SDK is missing code.
The following method should contain a switch case to instantiate the right object depending on the odata type.
https://github.com/microsoftgraph/msgraph-sdk-go/blob/0bb5af57a5d7c910cafe5cf5ebac8aa6337b07aa/models/directory_object.go#L23

I've [authored a pull request](https://github.com/microsoft/OpenAPI.NET/pull/864) in the metadata conversion library to fix the missing information we depend on for the generation of this SDK.
After the PR gets merged and published, the SDK will need to be generated (which happens weekly on tuesdays), after that, you'll only need to upgrade the version of the library in your application to get things to work.

**Comment by baywet** [comment]
as an update, the metadata and the generated go SDK were just updated. But the metadata is still inaccurate because of a bug in the conversion process. I just [logged an issue in the conversion library](https://github.com/microsoft/OpenAPI.NET.OData/issues/219)

**Comment by Mattes83** [comment]
Thanks for the update!

**Comment by baywet** [comment]
Update: the cast method is now part of the SDK (for a couple of weeks actually, but I was out)

https://github.com/microsoftgraph/msgraph-sdk-go/blob/e26ee4114d4b449b8e2f387b2dee47d2bacc930c/groups/item/transitivemembers/user/user_request_builder.go#L92

```golang
result, err := r.GraphServiceClient.GroupsById(objectID.String()).TransitiveMembers().User().Get()
// result is a collection of users
```

Thanks for your patience on this one. Let us know if you need anything else. Closing.
