### ISSUE TITLE
Access token validation failure. Invalid audience.

### ISSUE THREAD

**Issue by WTIGER001** [microsoftgraph/msgraph-sdk-go#162]
Hello... I am trying move from a different msgraph go library to the offical one... but I am getting an error of  "Access token validation failure. Invalid audience." in my calls.. Here is the code I am trying to call. I have verified that the tenantID, ClientID and ClientSecret still work with the previous library. (BTW: I am using Azure Gov)

```golang
package azure

import (
	"context"
	"fmt"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore/cloud"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	azidentity "github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	a "github.com/microsoft/kiota-authentication-azure-go"
	msgraphsdk "github.com/microsoftgraph/msgraph-sdk-go"
)

func NewGraphClient(ctx context.Context, tenantID string, clientID string, clientSecret string) {

	scopes := []string{"https://graph.microsoft.us/.default"}

	cred, err := azidentity.NewClientSecretCredential(tenantID, clientID, clientSecret,
		&azidentity.ClientSecretCredentialOptions{
			ClientOptions: policy.ClientOptions{
				Cloud: cloud.AzureGovernment,
			},
		})

	if err != nil {
		fmt.Printf("Error authentication provider: %v\n", err)
		return
	}
	auth, err := a.NewAzureIdentityAuthenticationProviderWithScopes(cred, scopes)
	if err != nil {
		fmt.Printf("Error authentication provider: %v\n", err)
		return
	}
	adapter, err := msgraphsdk.NewGraphRequestAdapter(auth)
	if err != nil {
		fmt.Printf("Error creating adapter: %v\n", err)
		return
	}
	client := msgraphsdk.NewGraphServiceClient(adapter)

	result, err := client.Me().Get()
	fmt.Printf("%+v\n", result)
	if err != nil {
		fmt.Printf("Error getting users: %v\n", err)
		return
	}

}
```

My Go mod file
```
module playground

go 1.18

require (
	github.com/Azure/azure-sdk-for-go/sdk/azcore v1.0.0 // indirect
	github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.0.0 // indirect
	github.com/Azure/azure-sdk-for-go/sdk/internal v1.0.0 // indirect
	github.com/AzureAD/microsoft-authentication-library-for-go v0.4.0 // indirect
	github.com/cjlapao/common-go v0.0.19 // indirect
	github.com/golang-jwt/jwt v3.2.1+incompatible // indirect
	github.com/google/uuid v1.3.0 // indirect
	github.com/kylelemons/godebug v1.1.0 // indirect
	github.com/microsoft/kiota-abstractions-go v0.5.0 // indirect
	github.com/microsoft/kiota-authentication-azure-go v0.2.1 // indirect
	github.com/microsoft/kiota-http-go v0.3.0 // indirect
	github.com/microsoft/kiota-serialization-json-go v0.3.1 // indirect
	github.com/microsoft/kiota-serialization-text-go v0.2.0 // indirect
	github.com/microsoftgraph/msgraph-sdk-go v0.23.0 // indirect
	github.com/microsoftgraph/msgraph-sdk-go-core v0.24.0 // indirect
	github.com/pkg/browser v0.0.0-20210115035449-ce105d075bb4 // indirect
	github.com/yosida95/uritemplate/v3 v3.0.2 // indirect
	golang.org/x/crypto v0.0.0-20220511200225-c6db032c6c88 // indirect
	golang.org/x/net v0.0.0-20220425223048-2871e0cb64e4 // indirect
	golang.org/x/sys v0.0.0-20211216021012-1d35b9e2eb4e // indirect
	golang.org/x/text v0.3.7 // indirect
)
```

My main fuction is simple

```
package main

import (
	"context"
	"playground/azure"
)

func main() {
	clientSecret := ****
	clientID := ****
	tenantID := ****

	azure.NewGraphClient(context.Background(), tenantID, clientID, clientSecret)
}

```

the code above results in 
```
<nil>
Error getting users: error status code received from the API
```

when I dbug it I find an error in the me_request_builder.go line 503. The Error object contains "data.code":"InvalidAuthenticationToken" and the data.message is "Access token validation failure. Invalid audience."

Please help... I am not sure what I am doing incorrectly.

I have also included a screen shot of the scope config.
![azure_client_scope_config](https://user-images.githubusercontent.com/4420898/168617500-012fad1d-d996-43f8-acaf-01ea1df1fe56.PNG)

Thanks

**Comment by baywet** [comment]
Hi @WTIGER001 
Thanks for reaching out and for trying the Go SDK.

First, a couple of things I can see from the code you shared and the screenshot:

Some of the permissions type and the authentication flow don't match.
Your application is using an application only context (client/secret, no proof from a user context).
Some of the permissions present in the screenshot are delegated and won't work until you either: change the authentication flow in the code, or replace them by their equivalent (if any) for application context.

Apps cannot use /me in an application only context. You either need to change the code to implement a delegated context or change the code to call endpoints that support app only context.
Eg

```diff
-result, err := client.Me().Get()
+result, err := client.UsersById("jane@contoso.com").Get()
```

Aside from that, the most evident issue from the code is the base URL not being set.

Please make the following modification to your code

```diff
client := msgraphsdk.NewGraphServiceClient(adapter)
+adapter.SetBaseUrl("https://graph.microsoft.us/v1.0")
```

(as you can see, the default base url, [is the public cloud](https://github.com/microsoftgraph/msgraph-sdk-go/blob/80186093e26af8b4046b4eb89a342c4a8af0641c/graph_service_client.go#L287)

**Comment by WTIGER001** [comment]
Perfect.. that worked.. I tried a bunch of methods beforehand.. the 
`adapter.SetBaseUrl("https://graph.microsoft.us/v1.0")`
did if for me
