### ISSUE TITLE
filter query param not being added to the request

### ISSUE THREAD

**Issue by aramase** [microsoftgraph/msgraph-sdk-go#17]
Trying to filter applications based on `displayName` and I see the filter value is not being honored. This is the sample function:

```go
func (c *client) GetApplication(ctx context.Context, displayName string) (*graph.Application, error) {
	appGetOptions := &applications.ApplicationsRequestBuilderGetOptions{
		Q: &applications.ApplicationsRequestBuilderGetQueryParameters{
			Filter: to.StringPtr(getDisplayNameFilter(displayName)),
		},
	}

	resp, err := client.Applications().Get(appGetOptions)
	if err != nil {
		return nil, err
	}
	if len(resp.GetValue()) == 0 {
		return nil, errors.Errorf("application with display name '%s' not found", displayName)
	}
	return &resp.GetValue()[0], nil
}

func getDisplayNameFilter(displayName string) string {
	return fmt.Sprintf("startswith(displayName, '%s')", displayName)
}
```

The response contains all the applications in my tenant. Tried to debug this a little more and found [AddQueryParameters](https://github.com/microsoft/kiota/blob/main/abstractions/go/query_parameters_base.go) isn't actually adding the query parameters to the request info.

**Comment by baywet** [comment]
Hi @aramase 
Thanks for all the great feedback you've provided so far.
I was able to reproduce and fix the bug, (see the multiple PRs in the history).
Once all those PRs get merged, this issue will be closed, just update your project and it should start working.

**Comment by aramase** [comment]
Thanks @baywet! Really appreciate the quick turnaround ❤️
