### ISSUE TITLE
cannot use NewTextParseNode(content)

### ISSUE THREAD

**Issue by hajsf** [microsoftgraph/msgraph-sdk-go#182]
Hi, I got this error:
```bash
D:\Development\gopath\pkg\mod\github.com\microsoft\kiota-serialization-text-go@v0.3.0\text_parse_node_factory.go:33:10: cannot use NewTextParseNode(content) (value of type *TextParseNode) as type serialization.ParseNode in return statement:
        *TextParseNode does not implement serialization.ParseNode (wrong type for GetCollectionOfEnumValues method)
                have GetCollectionOfEnumValues(parser func(string) (interface{}, error)) ([]interface{}, error)
                want GetCollectionOfEnumValues(parser serialization.EnumFactory) ([]interface{}, error)
```

With this code:
```go
package main

import (
	"context"
	"fmt"

	azidentity "github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	a "github.com/microsoft/kiota-authentication-azure-go"
	msgraphsdk "github.com/microsoftgraph/msgraph-sdk-go"
)

func main() {
	cred, err := azidentity.NewDeviceCodeCredential(&azidentity.DeviceCodeCredentialOptions{
		TenantID: "f8cdef31-a31e-4b4a-93e4-5f571e91255a",
		ClientID: "8206ae2c-8e14-493e-88f7-19ebf7f2c3ca",
		UserPrompt: func(ctx context.Context, message azidentity.DeviceCodeMessage) error {
			fmt.Println(message.Message)
			return nil
		},
	})

	if err != nil {
		fmt.Printf("Error creating credentials: %v\n", err)
	}

	_, err = a.NewAzureIdentityAuthenticationProviderWithScopes(cred, []string{"Files.Read"})
	if err != nil {
		fmt.Printf("Error authentication provider: %v\n", err)
		return
	}

	adapter, err := msgraphsdk.NewGraphRequestAdapter(auth)
	if err != nil {
		fmt.Printf("Error creating adapter: %v\n", err)
		return
	}
	client := msgraphsdk.NewGraphServiceClient(adapter)

	result, err := client.Users().Get(nil)
	if err != nil {
		fmt.Printf("Error getting users: %v\n", err)
		return err
	}

	result, err = client.Me().Drive().Get()
	if err != nil {
		fmt.Printf("Error getting the drive: %v\n", err)
	}
	fmt.Printf("Found Drive : %v\n", *result.GetId())
}
```

**Comment by baywet** [comment]
Hi @hajsf ,
Thanks for reaching out and for trying the Go SDK.
We've just published a set of breaking changes to better handle enums parsing.
As we don't semver just yet (still in public preview), my guess is that you caught misaligned versions.
Can you share all the versions you have for kiota and msgraph packages here please?

**Comment by hajsf** [comment]
> Hi @hajsf ,
> Thanks for reaching out and for trying the Go SDK.
> We've just published a set of breaking changes to better handle enums parsing.
> As we don't semver just yet (still in public preview), my guess is that you caught misaligned versions.
> Can you share all the versions you have for kiota and msgraph packages here please?

Hi, I just got the latest version of each.
If you have a simple workable example, I would appreciate sharing it with me, so I will test and start with it. Thanks

**Comment by baywet** [comment]
0.4.0 of serialization text is in facts the latest at the moment of writing.
my guess it that it's being pulled because we haven't released a new version of the go SDK and it still refers to older versions of the kiota libraries.


I just released a patch (we were hoping to release those changed with the weekly generation by the end of the week)

```shell
go get github.com/microsoftgraph/msgraph-sdk-go@v0.24.2
go mod tidy
```

Should get you sorted.
