### ISSUE TITLE
Trying to add member to group

### ISSUE THREAD

**Issue by amarbut24** [microsoftgraph/msgraph-sdk-go#197]
Hello,

Using this [example ](https://docs.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=go) to attempt to add a member to an azure ad group.

I have this bit of code
```
graphClient := msgraphsdk.NewGraphServiceClient(requestAdapter)

requestBody := msgraphsdk.New()
requestBody.SetAdditionalData(map[string]interface{}{
	"@odata.id": "https://graph.microsoft.com/v1.0/directoryObjects/<userid>",
}
groupId := "<objectid for group>"
add, err := graphClient .GroupsById(&groupId).Members().Ref().Post(requestBody)
```

I get below error

```
Exception has occurred: panic
"interface conversion: interface is nil, not ref.Refable"
Stack:
	3  0x0000000000c73d37 in github.com/microsoftgraph/msgraph-sdk-go/groups/item/members/ref.(*RefRequestBuilder).PostWithRequestConfigurationAndResponseHandler
	    at /home/anthony/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.25.0/groups/item/members/ref/ref_request_builder.go:142
	4  0x0000000000c73977 in github.com/microsoftgraph/msgraph-sdk-go/groups/item/members/ref.(*RefRequestBuilder).Post
	    at /home/anthony/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.25.0/groups/item/members/ref/ref_request_builder.go:126
```

It seems to be this line specifically that is panicking
https://github.com/microsoftgraph/msgraph-sdk-go/blob/main/groups/item/members/ref/ref_request_builder.go#L144

When debugging things I notice that the value for `res` [Here](https://github.com/microsoftgraph/msgraph-sdk-go/blob/main/groups/item/members/ref/ref_request_builder.go#L140) is `github.com/microsoft/kiota-abstractions-go/serialization.Parsable nil` which I believe explains the error I'm getting

Its possible I'm doing something horrible wrong, namely the add line
`add, err := graphClient .GroupsById(&groupId).Members().Ref().Post(requestBody)`
Am I using the `.Ref()` portion properly? 

Oddly enough the user is being added to the group successfully. So the add is working minus the fatal panic 😄

**Comment by amarbut24** [comment]
Hey @baywet 

Thanks for the super quick response and all the work on this SDK. Apologies for not catching the other post/answer.

I've given it a try and am running into another error

Code
```
graphClient.GroupsById(group.ObjectID).Members().Post(reference)
```

```

graphClient.GroupsById(group.ObjectID).Members().Post undefined (type *"github.com/microsoftgraph/msgraph-sdk-go/groups/item/members".MembersRequestBuilder has no field or method Post)

```

I made sure I ran `go get github.com/microsoftgraph/msgraph-sdk-go@v0.26.0` and updated my .mod file
```
require (
	github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.1.0
	github.com/microsoft/kiota-authentication-azure-go v0.3.1
	github.com/microsoftgraph/msgraph-sdk-go v0.26.0
	github.com/microsoftgraph/msgraph-sdk-go-core v0.26.1
)
```

**Comment by amarbut24** [comment]
Hey @baywet 

Please disregard my previous comment. I mistakenly read your comment in the previous thread and wasn't including the `.Ref()` method in my call

Everything is working now

**Comment by amarbut24** [comment]
I take that back 😞 

If I use `r, err := graphClient.GroupsById(group.ObjectID).Members().Ref().Post(reference)`
I get the interface error

If I _try_ and use 	r, err := graphClient.GroupsById(group.ObjectID).Members().Post(reference)
I'm told that `graphClient.GroupsById(group.ObjectID).Members().Post undefined (type *"github.com/microsoftgraph/msgraph-sdk-go/groups/item/members".MembersRequestBuilder has no field or method Post)`

Sorry if I'm doing something dumb

**Comment by abjoseph** [comment]
@baywet despite #155 been closed and marked as resolved this is still very much an issue and not working as of release 0.26.0

To recap, I have the following code (similar to @amarbut24) and I continue to get the error below:

```
	requestBody := ref.NewRef()
	oDataLink := fmt.Sprintf("https://graph.microsoft.com/v1.0/directoryObjects/{%s}", userId)
	requestBody.GetAdditionalData()["@odata.id"] = oDataLink

	log.Info("Adding user to Group with odata.link: %s", oDataLink)

	_, err := graphClient.GroupsById(group.Id).Members().Ref().Post(requestBody)
```
where `ref.NewRef()` is imported from `"github.com/microsoftgraph/msgraph-sdk-go/groups/item/members/ref"`

Error from invoking the above code snippet:

```
panic: interface conversion: interface is nil, not ref.Refable

goroutine 1 [running]:
github.com/microsoftgraph/msgraph-sdk-go/groups/item/members/ref.(*RefRequestBuilder).PostWithRequestConfigurationAndResponseHandler(0xc00055a5e8, {0x37e3b48?, 0xc000006058?}, 0xa?, 0x2?)
        C:/Users/bjoseph/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.26.0/groups/item/members/ref/ref_request_builder.go:144 +0x11e
github.com/microsoftgraph/msgraph-sdk-go/groups/item/members/ref.(*RefRequestBuilder).Post(...)
        C:/Users/bjoseph/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.26.0/groups/item/members/ref/ref_request_builder.go:128
```

**Comment by abjoseph** [comment]
### Update

I also tried the workaround of using the RequestBuilder directly and that also failed with a go panic error, code snippet and error below:

```
	url := fmt.Sprintf("https://graph.microsoft.com/v1.0/groups/%s/members/$ref", group.Id)
	requestBuilder := groups.NewGroupsRequestBuilder(url, graphClient.requestAdapter)
	objectToAdd := models.NewGroup()
	objectToAdd.GetAdditionalData()["@odata.id"] = oDataLink
	_, err := requestBuilder.Post(objectToAdd)
```
Error from invoking the above code snippet:

```
panic: interface conversion: interface is nil, not models.Groupable

goroutine 1 [running]:
github.com/microsoftgraph/msgraph-sdk-go/groups.(*GroupsRequestBuilder).PostWithRequestConfigurationAndResponseHandler(0xc00081e5e8, {0x398aed0?, 0xc000261400?}, 0x9?, 0x1?)
        C:/Users/bjoseph/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.26.0/groups/groups_request_builder.go:169 +0x11e
github.com/microsoftgraph/msgraph-sdk-go/groups.(*GroupsRequestBuilder).Post(...)
        C:/Users/bjoseph/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.26.0/groups/groups_request_builder.go:153
```

**Comment by abjoseph** [comment]
[#https://github.com/microsoftgraph/msgraph-sdk-go/issues/155#issuecomment-1156264835](https://github.com/microsoftgraph/msgraph-sdk-go/issues/155#issuecomment-1156264835)

**Comment by abjoseph** [comment]
@baywet Is it possible to get an ETA on this issue and #155, which I believe are affected by the same underlying bug. This is an _**Active**_ blocker preventing us from making further progress.

**Comment by baywet** [comment]
Hey everyone,
Thanks for your patience on this matter, I was out all of last week being sick.

I've provided a reply to #155 [here](https://github.com/microsoftgraph/msgraph-sdk-go/issues/155#issuecomment-1160471158) for the details. I'll circle back with the dev who owns the conversion library to get things pushed forward. No ETA to share at the moment.

**Comment by amarbut24** [comment]
Hey @baywet 

thanks for the follow up and I hope you are feeling better.
I've gone ahead and subscribed to https://github.com/microsoft/OpenAPI.NET.OData/issues/228 in the meantime

**Comment by abjoseph** [comment]
Thanks for the update @baywet, and hope you're feeling better. I will also keep an eye on the progress of https://github.com/microsoft/OpenAPI.NET.OData/issues/228

**Comment by baywet** [comment]
yep, it's progress in the right direction.
Now the conversion library still needs to be released, then hidi, the tool we're using for the conversion needs to grab this new release, and get released itself. And finally we'll be able to generate a new version of the Go SDK, which should include those fixes. Hopefully by next Tuesday, otherwise by the next one.

**Comment by amarbut24** [comment]
🎉

**Comment by baywet** [comment]
Hi everyone!
Thanks for your patience on this one.
#211 fixed that issue and was just released a couple of minutes ago as v0.29.0
As you can see the post operation on the ref node under members now accepts a proper model.
https://github.com/microsoftgraph/msgraph-sdk-go/blob/32e95517554481b1846846df8198fdab79909f76/groups/item/members/ref/ref_request_builder.go#L126

Let us know if you need anything else.

**Comment by amarbut24** [comment]
awesome! Thanks for your help @baywet 
Going to do some testing this weekend and let you know if I notice anything

**Comment by abjoseph** [comment]
@baywet , I hope I'm just missing the obvious but I can't seem to find the method to create a struct of type ReferenceCreateable to pass to the Post method...can you help me out here.

**Comment by baywet** [comment]
models.NewReferenceCreate() ?

**Comment by baywet** [comment]
https://github.com/microsoftgraph/msgraph-sdk-go/blob/32e95517554481b1846846df8198fdab79909f76/models/reference_create.go#L15

**Comment by abjoseph** [comment]
@baywet Thanks! It's been almost a month and apparently I already forgot the convention, I was searching the repo for `ReferenceCreateable` and didn't find anything. Just tried for `ReferenceCreate` and no results either, I suspect GitHub hasn't indexed the new files/types as yet.

**Comment by baywet** [comment]
file search is usually much faster in my experience. (t on the repo main page, then reference_create)

**Comment by abjoseph** [comment]
Yup, that works much better, but I would need to know the file name but at least it's something.

**Comment by baywet** [comment]
for this repo, the file names match the type name with the difference that types are UpperCamelCased and the file names snake_cased for future reference :)
