### ISSUE TITLE
Support token cache or MSAL connection

### ISSUE THREAD

**Issue by gestrada-kr** [microsoftgraph/msgraph-sdk-go#198]
Working on writing a CLI to manage user operations. Our current implementation on node.js uses the Graph SDK for node, which supports passing your own custom Auth Provider (which is simply built on top of MSAL for node). MSAL supports token caching strategies out of the box and apparently it is the same case for [MSAL for Go](https://github.com/AzureAD/microsoft-authentication-library-for-go), via serialization mechanisms (Marshal/Unmarshal).

Working with the examples in the docs and after inspecting the code for `azure-sdk-for-go/azidentity` I don't see a way to inject token caching into the client pipeline. Is there a way to support custom AuthProvider here the way the node.js version does, so we can build one on top of MSAL? Or is this better raised at the `azure-sdk-for-go` repo in regards of `azidentity`?

The idea is to be able to run the CLI commands, login once using device code flow, and continue running commands for as long as it's needed until the token expires. Then, silently authenticate using `refresh_token` mechanisms to continue to run commands uninterrupted on the developer machine. 

One thing to note is that when using MSAL on node I can request for the `offline_access` claim to get a `refresh_token`. But when using the `kiota-authentication-azure-go` as the provider with `NewAzureIdentityAuthenticationProviderWithScopes` I get the following error when requesting the `offline_access` scope:

`DeviceCodeCredential: token response failed because declined scopes are present: offline_access`

Is there a more straightforward way to do this? or I just have to implement my own provider for Kiota abstracts repo here:

https://github.com/microsoft/kiota-abstractions-go/blob/main/authentication/access_token_provider.go

and bypass the Kiota authentication all together?

**Comment by baywet** [comment]
Hey @gestrada-kr 
Thanks for reaching our and for trying the Go SDK.
Sorry for the delayed response, I was out sick last week.

First and foremost, I want to encourage you to try our [preview CLI](https://github.com/microsoftgraph/msgraph-cli).

Now, focusing on the Go SDK, kiota gives you a choice, you can either use the provided azure identity authentication provider if it fulfills your scenario, or you can reimplement Authentication Provider as you rightfully pointed out. You can even derive from Base Bearer authentication provider which will save you implementation time.

Before you dive into implementation details though, you should know that azure identity uses MSAL under the covers and exposes some of its configuration. I'd encourage you to reach out on [their repository first](https://github.com/Azure/azure-sdk-for-go/) with questions you might have.
