### ISSUE TITLE
contentBytes not in GetAdditionalData()

### ISSUE THREAD

**Issue by vivlis** [microsoftgraph/msgraph-sdk-go#219]
Hello

retrieving attachment from message like
```golang
atts, err := g.appClient.UsersById(mailbox.Mailbox).MailFoldersById(mailbox.IncommingMailboxDirectoryID).MessagesById(messageID).Attachments().Get()
```
v0.26 result:
AditionalDAta map[@odata.mediaContentType:0xc00048db90 @odata.type:0xc00048db30 **contentBytes:0xc0002fa010** contentId:0xc00048ddf0]
v030 result:
AditionalDAta map[@odata.mediaContentType:0xc0004062c0]

has contentBytes been decommissioned?

**Comment by vivlis** [comment]
that works 
thank you

**Comment by FabianTe** [comment]
Just curious, how comes that `contentBytes` is not part of `models.Attachmentable` ?

**Comment by baywet** [comment]
@FabianTe That's because it's defined on a derived type https://github.com/microsoftgraph/msgraph-sdk-go/blob/30ffc604140c6e100d4478b25e6095a021f27b53/models/file_attachment.go#L25
