### ISSUE TITLE
How to handle inconsistency caused by DNS round robin balancing across regions

### ISSUE THREAD

**Issue by manicminer** [microsoftgraph/msgraph-sdk-go#221]
Hi, I've been looking at how this SDK composes requests and have not been able to figure out how the issue of DNS based load balancing across regions has been approached?

Specifically, when making related requests in quick succession, according to the MS Graph team, these requests have to be sent to the same IP address to qualify for a consistency guarantee. Otherwise, subsequent requests start to fail whilst replication takes place.

For example, say I create some groups and some users, and then start to add those users to some of the groups. If some of the requests for adding group members happen to be sent to a different backend IP than the requests that created the user or the group being referenced, and this requests happens quickly, it's likely to fail with a 404 on either the user or the group.

How is this handled in the SDK? Both in terms of controlling which backend requests are sent to, and in terms of retrying consistency/replication related failed requests? Thanks!

**Comment by baywet** [comment]
Hi,
Thanks for reaching out and for trying the sdk.
Even if the sdk guaranteed a sticky connection to the same host (which it might or might not do depending on the settings of the native client), Microsoft Graph is just a proxy to the different services and it doesn't guarantee instance affinity end to end for the client.
This means, as you outlined, that your application can create a group for example with one request and the next query to add members to it can return a 404.
Usually this replication is handled almost instantly, but under certain conditions it can take up to 15 minutes (for identity services).
Your application code should account for this (retry, queuing, etc...)
Let us know if you have any additional question.

**Comment by baywet** [comment]
Even if your application lands on the same exact gateway instance (graph.microsoft.com) by locking the resolution to a single IP (don't do it, the instance might get recycled and your application would be in trouble), nothing guarantees the gateway will reach the same service instance on the backend for two subsequent requests. It is true that the routing is configured to avoid crossing regions internally to avoid additional latency and so on under normal operating conditions.
If you see long replication times, log the request ID and timestamp and contact support.

**Comment by manicminer** [comment]
@msftbot _4 days_, is that a joke??

@baywet Thanks, unfortunately the advice on _not_ applying stickiness by IP in client code for MS Graph, contradicts what I've been told in other channels, so I will have to follow up separately to clarify this.

To be honest, we regularly see long replication times. It's worse for some operations, like adding a client credential to an application or managing groups with a large member base, but also appears to rack up on a per tenant basis when lots of operations are sent in quick succession. I'm sure some of this is unavoidable, but I am looking for ways to reduce these where possible.

This isn't so much a feature request, more of a "how do you handle this" question, so I'm happy to close this. Appreciate the feedback, thanks again!
