### ISSUE TITLE
Incorrect identity provider request URL

### ISSUE THREAD

**Issue by Subhajit97** [microsoftgraph/msgraph-sdk-go#223]
Hi, I am trying to list the identity providers but getting zero results.
It seems like the template to build the request URL is incorrect?
https://github.com/microsoftgraph/msgraph-sdk-go/blob/main/identityproviders/identity_providers_request_builder.go#L63
It should be `{+baseurl}/identity/identityProviders`, not `{+baseurl}/identityProviders`
```
 m.urlTemplate = "{+baseurl}/identity/identityProviders{?%24top,%24skip,%24search,%24filter,%24count,%24orderby,%24select,%24expand}";
```

I have also found https://github.com/microsoftgraph/msgraph-sdk-go/blob/main/identity/identityproviders/identity_providers_request_builder.go#L63
Using this I'm able to get the list, but it only returns `ID` and `DisplayName`.
https://github.com/microsoftgraph/msgraph-sdk-go/blob/193c8c637cf543f2223d3d5647ef1cf1338d3928/models/identity_provider_baseable.go#L8
Is there any way to get the `Type`, `ClientId` and `ClientSecret` also (like https://github.com/microsoftgraph/msgraph-sdk-go/blob/193c8c637cf543f2223d3d5647ef1cf1338d3928/models/identity_providerable.go#L8)?

**Comment by andrueastman** [comment]
Thanks for raising this issues @Subhajit97 

The request builder will return instances of `IdentityProviderBaseable` and its derived types as well.  However, `IdentityProviderable` is not a derived type of it.

https://github.com/microsoftgraph/msgraph-sdk-go/blob/main/identity/identityproviders/identity_providers_request_builder.go#L63

If you know the derived type you wish to access properties from from, any chance you can try out something similar to the example provided by at the link here and see if it works out? https://github.com/microsoftgraph/msgraph-sdk-go/issues/219#issuecomment-1185539884
