### ISSUE TITLE
Missing `refreshTokensValidFromDateTime` in `User` response

### ISSUE THREAD

**Issue by Subhajit97** [microsoftgraph/msgraph-sdk-go#227]
Hi, I'm trying to list all users in my organization.
But in the response, I didn't see any method defined to get the value for `refreshTokensValidFromDateTime`.
https://github.com/microsoftgraph/msgraph-sdk-go/blob/2d3e4f1d94cf75bb5a722f555993907ced137aab/models/userable.go#L9
![image](https://user-images.githubusercontent.com/38218418/181026582-d420cc96-e636-432b-a50b-5bc26cb30906.png)

https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0

**Comment by baywet** [comment]
Hi @Subhajit97,
Thanks for reaching out and for trying the Go SDK.
This looks like an inaccuracy with the metadata and [I've logged an issue](https://github.com/microsoftgraph/msgraph-metadata/issues/194)

In the meantime you should be able to get the value from the additional data manager as raw JSON. Let us know if you need anything else.

**Comment by Subhajit97** [comment]
Thanks, @baywet, for looking into it.
For this, `In the meantime, you should be able to get the value from the additional data manager as raw JSON.` is there any documentation or example I can refer to?

**Comment by baywet** [comment]
`value := myUser.GetAdditionalData()["refreshTokensValidFromDateTime"]`

**Comment by baywet** [comment]
I received a response from the service team. The `refreshTokensValidFromDateTime` should not be present anymore and they are working to fix that. The new property name is `signInSessionsValidFromDateTime` which you should be able to retrieve using [the getter](https://github.com/microsoftgraph/msgraph-sdk-go/blob/c3791903c5e7a6d4ade03b54224445f7d63345d7/models/user.go#L2451) (you need to select the property in the query first).
Let us know if you need anything else.

**Comment by Subhajit97** [comment]
Thanks, @baywet, for confirming this. Yes, I'm able to access `signInSessionsValidFromDateTime` using the getter. We will update our code to use this instead of `refreshTokensValidFromDateTime`.
