### ISSUE TITLE
Missing `verifiedPublisher` in `ServicePrincipal` response

### ISSUE THREAD

**Issue by Subhajit97** [microsoftgraph/msgraph-sdk-go#228]
Hi, I'm trying to list all service principals.
But in the response, I didn't see any method defined to get the value for `verifiedPublisher`.
https://github.com/microsoftgraph/msgraph-sdk-go/blob/2d3e4f1d94cf75bb5a722f555993907ced137aab/models/service_principalable.go#L8
![image](https://user-images.githubusercontent.com/38218418/181035152-5bb5b58e-c6fb-47b4-819a-094393db37e1.png)

https://docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0

**Comment by baywet** [comment]
Hi @Subhajit97,
Thanks for reaching out and for trying the Go SDK.
This looks like an inaccuracy with the metadata and [I've logged an issue](https://github.com/microsoftgraph/msgraph-metadata/issues/193)

In the meantime you should be able to get the value from the additional data manager as raw JSON. Let us know if you need anything else.

**Comment by baywet** [comment]
Update: I've received information from the service team on this one. Although the property is present and documented, it's not supposed to work just yet. Verified publishers only works on the application object at the moment (which you might or not have depending on whether your tenant owns the application).

**Comment by Subhajit97** [comment]
Thanks, @baywet, for confirming this. Is there any chance you will support this property for service principal in future, or is this property only valid for the application object?

**Comment by baywet** [comment]
They are working on adding the support for service principal as we speak but have not shared any timeline at the moment. So we could be talking weeks or months.

**Comment by baywet** [comment]
Closing this one since there's no more action to take on the SDK itself.
