### ISSUE TITLE
Example in README does not work

### ISSUE THREAD

**Issue by ken5scal** [microsoftgraph/msgraph-sdk-go#23]
Changing scope from `[]string{"Mail.Read", "Mail.Send"}` to `[]string{"User.Read"}`, the example returned the following error when executing `client.Me().Get(nil)`. 

```
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XXXXXXXXX to authenticate.
2021/11/21 00:01:43 Error getting user: (invalid_client) AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: b2f2fc4f-9734-4001-91a3-2165e3ac1100
Correlation ID: 64c27318-e30e-4d62-9a33-949b045b9bf8
Timestamp: 2021-11-20 15:01:43Z
```

Here is what permissions I have granted to the app.

![image](https://user-images.githubusercontent.com/9734362/142731384-753befe8-431b-4188-adb2-8be263fd0dce.png)

Here is my environment

```
go 1.17

require (
	github.com/Azure/azure-sdk-for-go/sdk/azidentity v0.12.0
	github.com/microsoft/kiota/authentication/go/azure v0.0.0-20211119142553-1ee6842528d6
	github.com/microsoftgraph/msgraph-sdk-go v0.2.0
)
```

**Comment by baywet** [comment]
Hi @ken5scal ,
Thanks for reaching out.

There are a couple of things happening here. First, you're right, the scope for the sample for the readme is wrong, it should be Files.Read.
Would you be willing to put a pull request together to fix that for this repo and https://github.com/microsoftgraph/msgraph-beta-sdk-go ?


Second, how have you configured your app registration in the authentication pane? I believe it is setup as a secret client when it should be setup as a public one.

**Comment by ken5scal** [comment]
Thanks @baywet 

> Would you be willing to put a pull request together to fix that for this repo and https://github.com/microsoftgraph/msgraph-beta-sdk-go ?

I believe you are mentioning about `README.md`, right? Here are PRs.

* https://github.com/microsoftgraph/msgraph-sdk-go/pull/25
* https://github.com/microsoftgraph/msgraph-beta-sdk-go/pull/17

> Second, how have you configured your app registration in the authentication pane? I believe it is setup as a secret client when it should be setup as a public one.

You are right about that.

**Comment by baywet** [comment]
Thanks for the pull requests! So everything is working on your side now?

**Comment by ken5scal** [comment]
@baywet Yes, thanks!
