### ISSUE TITLE
Compilation takes minutes when using graph sdk

### ISSUE THREAD

**Issue by FabianTe** [microsoftgraph/msgraph-sdk-go#243]
Hi,

maybe I am missing something, but when using this SDK, compilation of my application takes minutes. This makes development effectively impossible. Compared to other applications ans services I am building, my build piplines would take anywhere between 5 and 10 minutes compared to 20 seconds on other projects using "typical" web service libraries.

I am sure I miss something here. Is this a problem for anyone else?

**Comment by baywet** [comment]
Hi @FabianTe 
Thanks for using the Go SDK and for reaching out.
This is something we're aware of and working to solve, you can review the discussions we've had with the other community members in #129.
Closing this one as duplicate.

**Comment by FabianTe** [comment]
Jup, sorry for opening this. You were lightning-fast with closing this, I was just on my way after discovering the know limitations section. Sorry for that and thank you for your time :)
