### ISSUE TITLE
Ambiguous error when authenticating as Service Principal

### ISSUE THREAD

**Issue by dpowley** [microsoftgraph/msgraph-sdk-go#247]
We are authenticating as a service principal using the `NewDefaultAzureCredential` and we are trying to interact with AzureAD in general (specifically list groups, but we are getting this error across multiple calls).

The code we are running is as follows:
```
        cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		return err
	}

	auth, err := a.NewAzureIdentityAuthenticationProviderWithScopes(cred, []string{
		"https://graph.microsoft.com/.default",
	})
	if err != nil {
		return err
	}

	adapter, err := msgraphsdk.NewGraphRequestAdapter(auth)
	if err != nil {
		return err
	}

	client := msgraphsdk.NewGraphServiceClient(adapter)

	result, err := client.Groups().Count().Get()
	if err != nil {
		return err
	}
```

The output error is `error status code received from the API` when calling `client.Groups().Count().Get()`. We have the credentials for the SP set in environment variables. Any thoughts on what the issue is?

**Comment by dpowley** [comment]
For reference, this is a permissions issue with a really vague error

**Comment by baywet** [comment]
Hi @dpowley 
Thanks for using the SDK and for reaching out.
Yes, sometimes the errors returned by the service are not explicit.
I just wanted to make sure you saw the "printODataError" part of the [getting started snippets](https://github.com/microsoftgraph/msgraph-sdk-go#3-make-requests-against-the-service) so you know how to access all the details?
Also wanted to make sure you're on a recent version of the SDK, support for errors deserialization was only added after version 0.25.0 if my memory serves me right.
