### ISSUE TITLE
Latest version of kiota-abstractions-go and kiota-http-go makes API calls fail with context cancelled

### ISSUE THREAD

**Issue by abezzub** [microsoftgraph/msgraph-sdk-go#251]
After upgrading `kiota-abstractions-go` to `v0.8.2` and `github.com/microsoft/kiota-http-go` to `v0.6.2` the following code fails with `context cancelled` error:
```
auth, _ := azure.NewAzureIdentityAuthenticationProviderWithScopes(
    azureTokenCredential{token: tok},
    linkScopes)
adapter, _ := msgraphsdk.NewGraphRequestAdapter(auth)
client =  msgraphsdk.NewGraphServiceClient(adapter)

_, err = client.Me().Get()
```
<img width="390" alt="Screen Shot 2022-08-31 at 1 51 31 PM" src="https://user-images.githubusercontent.com/3282823/187803814-641a399b-fab6-4346-be3f-afb06c835ed7.png">

When using versions `kiota-abstractions-go v0.8.1` and `kiota-http-go v0.5.2` the code executes successfully and I can get information about the user. I also verified I can make the API call successfully using the token from outside of SDK.

**Comment by baywet** [comment]
Hi @abezzub 
Thanks for using the Go SDK and for reaching out.
You are correct, we ran into a few bumps working on #176 and version 0.8.2 contains a bug, for now, please revert to 8.6.1.
We'll be pushing new versions fairly soon to implement the new feature which will address this issue as well.
Related #253
