### ISSUE TITLE
Failed to get user with the graph service client

### ISSUE THREAD

**Issue by NikaidouShinkus** [microsoftgraph/msgraph-sdk-go#26]
I'm trying to get user with the graph service client:
```
import (
	"bytes"
	"encoding/json"
	"fmt"

	azure "github.com/microsoft/kiota/authentication/go/azure"
	msgraphsdkgo "github.com/microsoftgraph/msgraph-sdk-go"

	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
)

cred, _ := azidentity.NewClientSecretCredential(
		"<my-tenant-id>",
		"<my-client-id>",
		"<my-client-secret>",
		&azidentity.ClientSecretCredentialOptions{
			AuthorityHost: azidentity.AzureChina,
		})

auth, _ := azure.NewAzureIdentityAuthenticationProviderWithScopes(cred, []string{
	"https://microsoftgraph.chinacloudapi.cn/.default",
})


adapter, _ := msgraphsdkgo.NewGraphRequestAdapter(auth)

client := msgraphsdkgo.NewGraphServiceClient(adapter)
users, _ := client.Users().Get(nil)
fmt.Println(users)
```
it got nil:
```
<nil>
```
but the config worked when I user Postman:
![image](https://user-images.githubusercontent.com/43268985/142829276-0050df65-27c4-400c-86d0-8444881bcb7e.png)

So I read code and see in `msgraphsdkgo.NewGraphServiceClient`:
![image](https://user-images.githubusercontent.com/43268985/142829579-906c4222-b84e-460d-b5af-527ee9a2e3b3.png)
it's https://microsoftgraph.chinacloudapi.cn/v1.0 for Azure AD of China, and it seems that I can't change this value:
![image](https://user-images.githubusercontent.com/43268985/142830018-dbe70726-b405-4c72-b2ce-0b7454962d24.png)

Thanks for your attention.

**Comment by baywet** [comment]
Hi @NikaidouShinkus,
Thanks for reaching out.
Yes you should be able to change that value.
Just after the line where you define the client add the following line.
adapter.SetBaseUrl("https://microsoftgraph.chinaclouapi.cn/v1.0")

**Comment by NikaidouShinkus** [comment]
Hi @baywet 
Thanks again for your help. I misread `NewGraphServiceClient`
