### ISSUE TITLE
API support for mailbox

### ISSUE THREAD

**Issue by rajlearner17** [microsoftgraph/msgraph-sdk-go#260]
We have the following Powershell command to check if the mailbox is enabled with audit or not

`Get-mailbox | Where AuditEnabled -Match 'False' | select UserPrincipalName, auditenabled`

We are looking exact API for this. Is this supported?

**Comment by rkodev** [comment]
@rajlearner17 thanks for trying out the beta sdk.
Currently this is a [list ](https://docs.microsoft.com/en-us/graph/migrate-exchange-web-services-api-mapping)of all the mappings from EWS to Graph SDK.

Currently, this sdk does not have an equivalent to `Get-mailbox` command

**Comment by rajlearner17** [comment]
@baywet, I Appreciate your quick response. I raised the same in the above forum, and I am looking forward to some response to continue our journey of automation in Azure. Thank you!
