### ISSUE TITLE
API Support for checking add-ins properties

### ISSUE THREAD

**Issue by rajlearner17** [microsoftgraph/msgraph-sdk-go#263]
Wondering to know, if anybody can help to guide the required API link for the below feature?

![image](https://user-images.githubusercontent.com/26873346/188631534-92280f85-50c4-49e7-a594-d65863dbfd62.png)

![image](https://user-images.githubusercontent.com/26873346/188632544-7113081c-fd58-48e7-94d2-729b6e2cf7af.png)

**Comment by baywet** [comment]
Hi @rajlearner17 
Thanks for reaching out.
This repository (and associated issues) is dedicated to the SDK itself.
For questions about the Mail APIs, [please reach out on the Microsoft Q&A forum](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-mail.html)
For questions about the admin center, I couldn't find a dedicated tag, you can [post a general question](https://docs.microsoft.com/en-us/answers/index.html).
In both cases you'll get answers from the service team that knows the specific APIs much better.
Closing.
