### ISSUE TITLE
azidentity - issue with import cycles

### ISSUE THREAD

**Issue by jeruly** [microsoftgraph/msgraph-sdk-go#267]
I follow the manual and get error: 
`package command-line-arguments
        imports github.com/Azure/azure-sdk-for-go/sdk/azidentity
        imports github.com/Azure/azure-sdk-for-go/sdk/azidentity: import cycle not allowed`

What may help me to fix this? 

Code: 
`
package main
import (
	"context"
	"fmt"
	azidentity "github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	a "github.com/microsoft/kiota-authentication-azure-go"
)
`

**Comment by baywet** [comment]
Hi @jeruly 
Thanks for using the Go SDK and for reaching out.
If you remove any Graph SDK and kiota dependency from your project, and just add the azure identity one (and try to import something from it), do you run into the same error?

**Comment by jeruly** [comment]
Yep, the issue happens even if i run only these code lines about importing
of azidentity as i show below

пт, 9 сент. 2022 г., 15:36 Vincent Biret ***@***.***>:

**Comment by baywet** [comment]
Thanks for confirming. The best thing to do then is to [contact the azure identity SDK team](https://github.com/azure/azure-sdk-for-go/issues/new), they'll be in a better position to support you. Closing.
