### ISSUE TITLE
Using delta queries with the Go SDK?

### ISSUE THREAD

**Issue by einarnn** [microsoftgraph/msgraph-sdk-go#272]
Are there any good examples of how to use delta queries with the Go SDK for MS Graph? It feels like I've been bashing my head against a brick wall, and I always end up with the error below from `msgraphcore.NewPageIterator`:

```
*errors.errorString > error: &errors.errorString{s:"response does not have next link accessor"}
```

...when I can clearly see that the initial response does have an `@odata.nextLink` field populated.

A full example of how to use a delta query against `https://graph.microsoft.com/v1.0/users` would be very helpful!

Cheers,

Einar

**Comment by baywet** [comment]
Hi @einarnn 
Thanks for using the Go SDK and for reaching out.
Can you share with us which version of msgraph-sdk-go and msgraph-sdk-go-core you're using please? We've made some changes to the properties names and I wanted to make sure you're using the latest versions.
Also, could you share your code snippet please?

**Comment by einarnn** [comment]
Extract from `go.mod`:

```
github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.1.0
github.com/microsoft/kiota-authentication-azure-go v0.4.1
github.com/microsoftgraph/msgraph-sdk-go v0.38.1
github.com/microsoftgraph/msgraph-sdk-go-core v0.28.1
```

Code currently is:

```
	requestConfiguration := delta.DeltaRequestBuilderGetRequestConfiguration{
		// ??? not sure if anything needed here
	}

	result, err := client.Users().Delta().Get(
		context.Background(),
		&requestConfiguration,
	)
	if err != nil {
		printOdataError(err)
		log.Fatalf("Error getting users: %v\n", err)
	}
	log.Printf("@odata.context  = %v\n", *result.GetAdditionalData()["@odata.context"].(*string))
	log.Printf("@odata.nextLink = %v\n", *result.GetAdditionalData()["@odata.nextLink"].(*string))
	log.Printf("result.GetValue()[0] = %v", *result.GetValue()[0].GetDisplayName())

	pageIterator, err := msgraphcore.NewPageIterator(result, adapter, delta.CreateDeltaResponseFromDiscriminatorValue)
	if err != nil {
		printOdataError(err)
		log.Fatalf("Error getting page iterator: %v", err)
	}
```

Fails currently where I try to create the `pageIterator` with the error message given at the start of this thread.

**Comment by baywet** [comment]
I'll update the issue here :)

**Comment by baywet** [comment]
unfortunately, it seems there's still another bug impacting the conversion process, I've just logged an issue over there. https://github.com/microsoft/OpenAPI.NET.OData/issues/285

Thanks for the patience on the matter.

**Comment by baywet** [comment]
update: the bug was fixed in the conversion library and the conversion tool was released in time. #300 addresses this issue.
