### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by jbdazn** [microsoftgraph/msgraph-sdk-go#288]
Hello,

In the readme of the repo, you mention a function called "NewGraphServiceClientWithCredentials" but it doesn't seem to exist in the current version of the package.

I tried the 1.41.0 and the latest (@main), none of the versions have a reference to `NewGraphServiceClientWithCredentials`. Could you either make the function accessible or update the README accordingly?

Thanks !

**Comment by baywet** [comment]
Hi @jbdazn 
Thanks for using the Go SDK and for reaching out. We had a PR addressing that which was not out yet. #286.
upgrading to v0.41.1 should solve your problem.

**Comment by jbdazn** [comment]
Hi @baywet, thanks a lot for the answer. Any idea about when will it be published?

**Comment by baywet** [comment]
it was [two hours ago](https://github.com/microsoftgraph/msgraph-sdk-go/releases/tag/v0.41.2)

**Comment by jbdazn** [comment]
Super ! Closing the issue. Thanks for your answers
