### ISSUE TITLE
List Child Folders Not working in the SDK 

### ISSUE THREAD

**Issue by dadams39** [microsoftgraph/msgraph-sdk-go#297]
As defined [here](https://learn.microsoft.com/en-us/graph/api/mailfolder-list-childfolders?view=graph-rest-1.0&tabs=http), When calling the List ChildFolders with the ParentFolder ID the result is not correct. For example,
![Screen Shot 2022-10-06 at 1 23 02 PM](https://user-images.githubusercontent.com/8600618/194378656-3a4c108e-d820-4e1a-b558-55f9dd8388a2.png)

Should return: 
![Screen Shot 2022-10-06 at 1 28 39 PM](https://user-images.githubusercontent.com/8600618/194379622-7a17263f-d28d-4fed-8512-7d5b115260e8.png)
However, it returns all of the folders in the directory.
I also noticed that this is also happening on the Graph Explorer. Is this a known issue? 

```http
https://graph.microsoft.com/v1.0/me/mailFolders/{M365FolderID}/childFolders
```

**Comment by baywet** [comment]
Hi @dadams39 
I don't believe this is an issue with the documentation or the service, but rather it's working as expected.
The documentation doesn't state this endpoint would only return the folders that are immediately under the queried one. This is probably done to save applications from having to query recursively the API which would take a long time for directory structures that are deeply nested.

**Comment by dadams39** [comment]
@baywet, I'm curious then what would be the difference in the `ListMailFolders` [API](https://learn.microsoft.com/en-us/graph/api/user-list-mailfolders?view=graph-rest-1.0&tabs=http). The list API doesn't the folder M365 ID where the childFolder call does. Either it is a wasted call or I am missing something.

**Comment by baywet** [comment]
As strange as it might "sound" we, the SDK team, don't know that much about the APIs themselves. There are thousands of those doing very various things. And the service teams are not watching the SDKs repos. The best thing to do is to [ask you question on the dedicated Microsoft Q&A forum](https://learn.microsoft.com/en-us/answers/topics/microsoft-graph-mail.html) to get attention from the service team.
Closing.
