### ISSUE TITLE
Problem of get token with ClientSecret

### ISSUE THREAD

**Issue by wilsonwu** [microsoftgraph/msgraph-sdk-go#299]
When I use ClientSecret request a token, it response can't find Files.Read.All in my user account, but I have already added the permission, scope is: https://graph.microsoft.com/Files.Read.All/.default, anything wrong? I get token with password grant type, and popup sigin web page way, both fine.
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/1269496/194695127-c472ec8e-8aec-4726-a202-3e4c583b9def.png">

**Comment by baywet** [comment]
Hi @wilsonwu,
Thank you for using the go SDK.
Can you share the code without the secret or id please?
The scope should only be Files.Read.All

**Comment by wilsonwu** [comment]
Thanks for your reply, the code in below:
`package main

import (
	"context"
	"fmt"
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	msgraphsdk "github.com/microsoftgraph/msgraph-sdk-go"
)

func main() {
	clientId := "hide"
	tenantId := "hide"
	clientSecret := "hide"
	cred, err := azidentity.NewClientSecretCredential(tenantId, clientId, clientSecret, nil)
	if err != nil {
		return
	}

	if err != nil {
		fmt.Printf("Error creating credentials: %v\n", err)
	}

	client, err := msgraphsdk.NewGraphServiceClientWithCredentials(cred, []string{"Files.Read.All"})
	if err != nil {
		fmt.Printf("Error creating client: %v\n", err)
		return
	}

	drive, err := client.Me().Drive().Get(context.Background(), nil)
	if err != nil {
		fmt.Printf("Error: %v\n", err)
		return
	}
	println(drive.GetName())
}
`

When I run it, it shown below result:
POST https://login.microsoftonline.com/hidetenantid/oauth2/v2.0/token
--------------------------------------------------------------------------------
RESPONSE 400 Bad Request
--------------------------------------------------------------------------------
{
  "error": "invalid_scope",
  "error_description": "AADSTS1002012: The provided value for scope Files.Read.All openid offline_access profile is not valid. Client credential flows must have a scope value with /.default suffixed to the resource identifier (ap
plication ID URI).\r\nTrace ID: 7c1c0005-125b-4037-9eef-b46d1a625800\r\nCorrelation ID: f3d90e55-76ca-47c9-ae83-9d5f81234465\r\nTimestamp: 2022-10-09 12:16:47Z",
  "error_codes": [
    1002012
  ],
  "timestamp": "2022-10-09 12:16:47Z",
  "trace_id": "7c1c0005-125b-4037-9eef-b46d1a625800",
  "correlation_id": "f3d90e55-76ca-47c9-ae83-9d5f81234465"
}
--------------------------------------------------------------------------------



And I also use Postman to test get token by client_credentials grant_type:
![image](https://user-images.githubusercontent.com/1269496/194756235-29edf804-e19d-4835-8788-68e2eeb8d5f6.png)

Not sure what is wrong with this Postman request, works fine in password grant_type.

**Comment by wilsonwu** [comment]
Add for the go code error, I changed Files.Read.All to https://graph.microsoft.com/Files.Read.All/.default
![image](https://user-images.githubusercontent.com/1269496/194756912-bcc9d292-f1a9-4e73-ae9d-14fd9103b117.png)
The result as same as Postman response:
      POST https://login.microsoftonline.com/hide/oauth2/v2.0/token
      --------------------------------------------------------------------------------
      RESPONSE 400 Bad Request
      --------------------------------------------------------------------------------
      {
        "error": "invalid_resource",
        "error_description": "AADSTS500011: The resource principal named https://graph.microsoft.com/Files.Read.All was not found in the tenant named WilsonWu. This can happen if the application has not been installed by the administra
      tor of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.\r\nTrace ID: 08cebd7e-9b28-48e3-94a1-f8c679bf4100\r\nCorrelation ID: 33eec6c9-23d4-4a0a-b1dd-c77a28
      dd84ff\r\nTimestamp: 2022-10-09 12:30:25Z",
        "error_codes": [
          500011
        ],
        "timestamp": "2022-10-09 12:30:25Z",
        "trace_id": "08cebd7e-9b28-48e3-94a1-f8c679bf4100",
        "correlation_id": "33eec6c9-23d4-4a0a-b1dd-c77a28dd84ff",
        "error_uri": "https://login.microsoftonline.com/error?code=500011"
      }
      --------------------------------------------------------------------------------
      
I guess the problem comes from my app settings, not sure, maybe other problems.

Thanks for help.

**Comment by baywet** [comment]
Thanks for the additional information. Client credentials doesn't support gradual consent (passing the scopes).
You need to pass https://graph.microsoft.com/.default instead or use the overload of the constructor that doesn't accept scopes.
You also need to make sure your application registration has the scope (application type) added to its permissions.

**Comment by wilsonwu** [comment]
Thanks for your answer, I tried to solve it, it my application registration I added Files.Read.All as Application type:
![image](https://user-images.githubusercontent.com/1269496/194766710-9a0afe4c-77aa-4d79-8177-41b63552c41d.png)

And change my code to:
![image](https://user-images.githubusercontent.com/1269496/194766744-ff4e941a-d93a-4745-80fe-053fd3549f4a.png)

I read the code, set nil or set https://graph.microsoft.com/.default are same, it will use https://graph.microsoft.com/.default as default value, but the result still with error:
Error: error status code received from the API

No more details.

Anything I need to do? I think I can contribute a code sample of client credential after I fix it.

**Comment by baywet** [comment]
The error object should contain the inner error from the API if you cast it to odataerrorable (see the readme) and give you more detailed information.

**Comment by wilsonwu** [comment]
Got it, the error is:
/me request is only valid with delegated authentication flow.

It is a bad news for me.

**Comment by baywet** [comment]
I'm not sure which profile page you're referring to?
When you list users (via /users) the user objects you get have an id property, that's the id I'm referring to.

**Comment by wilsonwu** [comment]
That is right I mean that you said, and thank you so much for your answers, we can close this issue now.
