### ISSUE TITLE
Question about NextLink

### ISSUE THREAD

**Issue by DmitriyVTitov** [microsoftgraph/msgraph-sdk-go#30]
Hi!
I'm trying to use Go Graph SDK and I'm stuck! I am able to request AD users but I get only first 100 users with NextLink property which contains link to additional data.
How should I use this link to fetch next 100 users with Go SDK?
Example of my code:
```
	...
	client := msgraphsdk.NewGraphServiceClient(adapter)
	result, err := client.Users().Get(&opts)
	if err != nil {
		log.Fatal(err)
	}
	var users []graph.User
	users = append(users, result.GetValue()...)
	fmt.Println(*result.GetNextLink())
```

**Comment by baywet** [comment]
Hi @DmitriyVTitov 
Thanks for reaching out, and for trying the new SDK!

```Golang
        client := msgraphsdk.NewGraphServiceClient(adapter)
	result, err := client.Users().Get(&opts)
	if err != nil {
		log.Fatal(err)
	}
	var users []graph.User
	users = append(users, result.GetValue()...)

        page2, err := users.NewUsersRequestBuilder(*result.GetNextLink(), adapter).Get(nil)
```

Would give you page 2.
Alternatively, if you want all the pages, you can look as long as the next link is not nil.

We also have [a feature on the roadmap](https://github.com/microsoftgraph/msgraph-sdk-go-core/issues/13) to iterate automatically over the pages and call a function you'd provide. Please go upvote the item if you think that'd be useful to you.

Let us know if you have any additional question.

**Comment by DmitriyVTitov** [comment]
Thanks @baywet!
Is the SDK production ready or it's goping to change significantly?
Close this issue please.

**Comment by baywet** [comment]
This really depends on you (the broader community), the more people we get to try the SDK, and the more positive feedback we get, the faster this SDK will reach GA in its current shape.
If on the contrary we don't get a lot of people to try the SDK, or get a lot of feedback that things need to change, it'll take longer to reach GA and/or we'll need to make significant changes before it does.

At this very moment, assuming the feedback is on the positive side, the only major change we anticipate is the move of the kiota dependencies to their own repository, this should be a quick change for most people, a reference update. (github.com/microsoft/kiota/abstractions/go, github.com/microsoft/kiota/serialization/go/json, github.com/microsoft/kiota/http/go/nethttp, github.com/microsoft/kiota/authentication/go/azure).

The other dependency we have that's currently in preview is azure identity.
