### ISSUE TITLE
Context deadline exceeded errors when calling API

### ISSUE THREAD

**Issue by abezzub** [microsoftgraph/msgraph-sdk-go#302]
I am getting occasional `context deadline exceeded (Client.Timeout exceeded while awaiting headers)` when calling Graph API using the SDK. This happens on different resources (events, todo tasks, calendar view, etc). I am using default context without timeout set. Is it possible to configure the timeout used by the SDK?

**Comment by baywet** [comment]
Hi @abezzub 
Thanks for using the Go SDK and for reaching out.
[the default timeout is 100s](https://github.com/microsoft/kiota-http-go/blob/b495300240ccab5cc60c08b03fbf6bca3681b4b9/nethttp_request_adapter.go#L195) if your context doesn't already contain a deadline.

You can perfectly pass in a [context with a deadline](https://github.com/microsoft/kiota-http-go/blob/b495300240ccab5cc60c08b03fbf6bca3681b4b9/nethttp_request_adapter.go#L202) to the chained API surface and the SDK should respect the new deadline.

**Comment by abezzub** [comment]
🤔 I verified our code does not set timeout on context before it is passed into SDK's functions. We call SDK functions in backend jobs, I see an example where timeout happened 37 seconds after the job started:
```
fields.causeType | *url.Error
fields.duration | 37.879397846
fields.errorString | failed to fetch calendar view page: Get "https://graph.microsoft.com/v1.0/me/calendar/calendarView?startDateTime=2022-10-17T10%3a12%3a02Z&endDateTime=2022-11-01T10%3a12%3a02Z&$top=10&$skip=70": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
Based on the presence of `top` and `skip` in the URL I see that the failed request is one of the subsequent paging requests. This job loops through the calendar view and previous 6 requests succeeded before the last request timed out, all in 37 seconds.

Do you have any ideas on what I can try to debug this further? It does look like the timeout is not applied or handled correctly by the SDK.

**Comment by abezzub** [comment]
Thanks, I will update the code to use the iterator and I will add retries around the API calls.

When digging in the logs I found a similar looking error, but it says `request canceled` and not deadline exceeded:

> Get "https://graph.microsoft.com/v1.0/me/calendar/calendarView?startDateTime=2022-10-18T10%3a12%3a09Z&endDateTime=2022-11-02T10%3a12%3a09Z&$top=10&$skip=10": net/http: request canceled (Client.Timeout exceeded while awaiting headers)

Do you think this is a different issue?

**Comment by abezzub** [comment]
I switched the code to use page iterator and retry when timeout error happens, but now it is failing with `fetching next page failed`:
https://github.com/microsoftgraph/msgraph-sdk-go-core/blob/main/page_iterator.go#L155

It looks like page iterator does not return the original error, so I'll have to roll back the code to the previous version, where paging was done manually and it was possible to see the actual error that was happening. Is it possible to update the page iterator to include the original error?

**Comment by baywet** [comment]
@rkodev do you think it'd be possible to include the inner error here? https://github.com/microsoftgraph/msgraph-sdk-go-core/blob/f0ae2b652111c67dbeb0c400a975353dfb39c934/page_iterator.go#L155

**Comment by abezzub** [comment]
Regarding the original issue, I can confirm adding retries reduced the number of `context deadline exceeded` errors, so this is no longer an issue for me. Thanks for your help.
