### ISSUE TITLE
Delete API for Calendar not working at present

### ISSUE THREAD

**Issue by dadams39** [microsoftgraph/msgraph-sdk-go#304]
Prior to October 14, the [Delete API](https://learn.microsoft.com/en-us/graph/api/calendar-delete?view=graph-rest-1.0&tabs=go) for calendars worked every time. 

Now, I am experiencing a strange situation. I delete several calendars that match a `regex` based off the calendar name.
The API will run no error. Refreshing the screen causes all of the deleted calendars to repopulate. 

Function call
```go
Client().UsersById(user).CalendarsById(calendarID).Delete(ctx, nil)
```

Any help on this would be greatly appreciated.

**Comment by baywet** [comment]
Hey @dadams39 
I'm guessing there's some kind of confusion since the call should something like

```go
graphClient.Me().CalendarsById(calendarId).Delete(context.Background(), nil)
```

Can you double check your application code please?

**Comment by dadams39** [comment]
That is correct. The interesting thing is that the calendars in question were created like, "TestCalendar: 19-Oct"
It seems that either the space or the colon is causing the command not to stick.

**Comment by dadams39** [comment]
@baywet , I'm not so sure. It appears that the calendar is `deleted` but GraphAPI still discovers the calendar when it is queried.
