### ISSUE TITLE
Location of GraphClient leads to very long build times

### ISSUE THREAD

**Issue by Andrei-Predoiu** [microsoftgraph/msgraph-sdk-go#311]
Right now the code generation places Graph client generation code in the root of the SDK in the `msgraphsdkgo` package.
I'm talking specifically about these following files:

```
msgraph-sdk-go@v0.44.0
graph_base_service_client.go
graph_request_adapter.go
graph_service_client.go
```
## Problem

Most of the time devs only need to import a few packages that they are working with Fx: `github.com/microsoftgraph/msgraph-sdk-go/users`. Unfortunately, to create a graph client, we have to import `github.com/microsoftgraph/msgraph-sdk-go`, which will download the whole sdk
Golang, afterwards, during build/install, has to work extra hard to remove the unnecessary symbols from the binary.

## Proposed solution

Why not refactor the files in their own folder and package. This way we can import and download them to generate a client without importing the whole sdk: fx ` import "github.com/microsoftgraph/msgraph-sdk-go/graphclient"`

This one change would mean big improvements to most of the build time related issues.

This is tangentially related to the following issue: https://github.com/microsoftgraph/msgraph-sdk-go/issues/129

**Comment by baywet** [comment]
Hi @Andrei-Predoiu 
Thanks for using the Go SDK and for reaching out.

I'd like to understand your suggestion better before providing an answer.
Are you suggesting keeping a single client for the SDK, but to deport it to its own sub package? in #129 it sounded a bit like your suggestion was to generate one client per package (/users, /me, etc...) instead of the whole SDK.

Assuming the former, how would this make a difference in build time/size? you'd still have to pull the graph client which in turns pulls the tree representation of the API.
Assuming the later, it'd break some design requirements for the discovery of the API, and would force the app developer to "handle" multiple clients, that'd be a serious experience degradation.

Thanks for the additional context.

**Comment by Andrei-Predoiu** [comment]
Hi @baywet, Sorry if my comment was unclear. My suggestion is to continue using one Client for the sdk but put it in a separate package.

I didn't really think the suggestion through to the end, it's not such a simple change.

You are right, that with the current design, would pull the whole graph anyway,  it's what allows us to do 
Fx: `Client.Users().Get()`. 
Unfortunately it's not possible to define receivers on structs from outside the package they are defined. The only solution would be a major redesign.

Maybe this is a discussion for kiota at this point
Quick, off the top of my head options would be:
1. Pass the client to the various functions
```
import ( 
      "github.com/microsoftgraph/msgraph-sdk-go/graphclient"
      "github.com/microsoftgraph/msgraph-sdk-go/users"
)

client := graphclient.NewGraphServiceClientWithCredentials(cred, nil)
users.Get(client,....)
```

2. Take a json encode/decode approach. 
```
import ( 
      "github.com/microsoftgraph/msgraph-sdk-go/graphclient"
      "github.com/microsoftgraph/msgraph-sdk-go/users"
)
...

client := graphclient.NewGraphServiceClientWithCredentials(cred, nil)
user_struc := users.NewListUser()
Client.Get(users.path, &user_struc, opts...)
```

**Comment by baywet** [comment]
Thanks for the additional context. Both those solutions would significantly degrade the experience for the end user.

> Unfortunately it's not possible to define receivers on structs from outside the package they are defined. The only solution would be a major redesign

Are you suggesting that if I have the graph service client at the root package (no functions defined besides *constructors*) and then a `Users()` function defined on that struct in the users sub package, that wouldn't work? It's one of the solutions (selective imports) we yet have to explore.

**Comment by Andrei-Predoiu** [comment]
To my knowledge, by design,  receiver functions can only be defined in the package where the struct is defined.
My go-fu is not that good but here is a link to an example of how to hack your way around it:

https://github.com/Andrei-Predoiu/goplayground/blob/master/main.go

**Comment by baywet** [comment]
you are correct, I took some time to poke around and posted my findings here https://github.com/microsoftgraph/msgraph-sdk-go-core/issues/106.
This would effectively mean that assuming we're not reducing the API surface, we need to either change the experience paradigm and/or reduce the amount of code being generated.

**Comment by baywet** [comment]
since we already have issues tracking each option, do you mind if I close this one? unless you have other suggestions to make?

**Comment by Andrei-Predoiu** [comment]
Hi, i don't have anything to add.

By the way. 
I ended up keeping the Auth and replacing the sdk with a simple http client.

My code was simply refusing to install even after 30+ minutes in our CI (we use circle i and I even tried running on the 20 core runner).

Now it takes 60 seconds to build and push docker in a 4 core runner.

**Comment by baywet** [comment]
thanks for sharing this. I'll go ahead and close this issue. Rest assured we're working hard to address this.
