### ISSUE TITLE
build hangs when importing package

### ISSUE THREAD

**Issue by tomas-mota** [microsoftgraph/msgraph-sdk-go#312]
When importing "github.com/microsoftgraph/msgraph-sdk-go", the build simply fails.
Reproduce with the following commands (go 1.19):
```
mkdir demo

go mod init demo

cat <<EOF > main.go
package main

import (
        "fmt"
        msgraphsdk "github.com/microsoftgraph/msgraph-beta-sdk-go"
)

func main() {
        fmt.Println("hi")
}
EOF

go mod tidy

go build main.go
```

In my case, the build just hangs until it fails with the following (includes time output):
```
go build github.com/microsoftgraph/msgraph-sdk-go/models: /usr/local/go/pkg/tool/linux_amd64/compile: signal: killed
go build -x main.go  68.65s user 6.95s system 85% cpu 1:28.74 total
```

**Comment by baywet** [comment]
hi @tomas-mota 
thanks for reporting this. It's something we're already investigating. You can set the GO Max procs as a workaround [details](https://github.com/microsoftgraph/msgraph-sdk-go/issues/129#issuecomment-1267698111)

**Comment by tomas-mota** [comment]
running `GOMAXPROCS=200 go get -u` does finish, but the build still hangs forever... to be honest I don't understand how importing a package (not even using it) can hang a build forever. Am I misunderstanding something or doing something wrong?

**Comment by tomas-mota** [comment]
ok after the first successful build, which took like 5 minutes, it is now faster.

**Comment by baywet** [comment]
Thanks for confirming. Closing this issue. Let us know if you need anything else.
