### ISSUE TITLE
users/item/calendarview/delta/delta_request_builder is not corresponding to the REST API reference documentation

### ISSUE THREAD

**Issue by DawnBreather** [microsoftgraph/msgraph-sdk-go#318]
- [QueryParameters structure definition in the code](https://github.com/microsoftgraph/msgraph-sdk-go/blob/main/users/item/calendarview/delta/delta_request_builder.go#L19)
- [QueryParameters description in the corresponding documentation](https://learn.microsoft.com/en-us/graph/api/event-delta?view=graph-rest-1.0&tabs=http#query-parameters)

**Code sample**
The code below is giving error `{"error":{"code":"ErrorInvalidParameter","message":"This request requires a time window specified by the query string parameters StartDateTime and EndDateTime."}}`

```go
import (
	"context"
	"github.com/microsoftgraph/msgraph-sdk-go/users/item/calendarview/delta"
)
delta, err := GetGraphServiceClient().UsersById(*user.GetUserPrincipalName()).CalendarView().Delta().Get(context.Background(), &delta.DeltaRequestBuilderGetRequestConfiguration{
		Headers: nil,
		Options: nil,
		QueryParameters: &delta.DeltaRequestBuilderGetQueryParameters{
			Count:   nil,
			Filter:  nil,
			Orderby: nil,
			Search:  nil,
			Select:  nil,
			Skip:    nil,
			Top:     nil,
		},
	})
```

Would you kindly fix the issue?

**Comment by baywet** [comment]
Hi @DawnBreather 
Thanks for reaching out and for using the Go SDK.
This is going to be difficult to fix as in essence the SDK is generated from metadata and this delta endpoint is not standard and the delta function (OData) doesn't allow to describe additional parameters how it's designed today.
Could you try creating a struct that is composed of `DeltaRequestBuilderGetQueryParameters` and adds the two missing fields? and then try to pass an instance of that struct to the method to see whether this is a suitable workaround?

**Comment by DawnBreather** [comment]
Hi @baywet ,
Thank you for your reply and suggestion!

The workaround you proposed worked just well:
```go
type DeltaRequestBuilderGetQueryParameters struct {
    // Include count of items
    Count *bool `uriparametername:"%24count"`
    // Filter items by property values
    Filter *string `uriparametername:"%24filter"`
    // Order items by property values
    Orderby []string `uriparametername:"%24orderby"`
    // Search items by search phrases
    Search *string `uriparametername:"%24search"`
    // Select properties to be returned
    Select []string `uriparametername:"%24select"`
    // Skip the first n items
    Skip *int32 `uriparametername:"%24skip"`
    // Show only the first n items
    Top *int32 `uriparametername:"%24top"`
    StartDateTime *string `uriparametername:"startdatetime"`
    EndDateTime   *string `uriparametername:"enddatetime"`
}
```
Thank you for being so helpful = )

**Comment by baywet** [comment]
You're welcome, thanks for sharing the solution with others.

**Comment by baywet** [comment]
@andrueastman I can see you've assigned yourself on this one. Was an issue in the metadata repo created? Did the metadata get fixed?

**Comment by andrueastman** [comment]
Hey @baywet,

I assigned myself following the discussion on https://github.com/microsoftgraph/msgraph-metadata/pull/313#pullrequestreview-1368933036 . Metadata hasn't been fixed yet though.

**Comment by Zuko1337** [comment]
> Hi @baywet , Thank you for your reply and suggestion!
> 
> The workaround you proposed worked just well:
> 
> ```go
> type DeltaRequestBuilderGetQueryParameters struct {
>     // Include count of items
>     Count *bool `uriparametername:"%24count"`
>     // Filter items by property values
>     Filter *string `uriparametername:"%24filter"`
>     // Order items by property values
>     Orderby []string `uriparametername:"%24orderby"`
>     // Search items by search phrases
>     Search *string `uriparametername:"%24search"`
>     // Select properties to be returned
>     Select []string `uriparametername:"%24select"`
>     // Skip the first n items
>     Skip *int32 `uriparametername:"%24skip"`
>     // Show only the first n items
>     Top *int32 `uriparametername:"%24top"`
>     StartDateTime *string `uriparametername:"startdatetime"`
>     EndDateTime   *string `uriparametername:"enddatetime"`
> }
> ```
> 
> Thank you for being so helpful = )
would it be possible to provide a full sample of the code you used?
I am not able to use a custom struct in `DeltaRequestBuilderGetRequestConfiguration` nor `ItemCalendarViewDeltaRequestBuilderGetRequestConfiguration`

**Comment by baywet** [comment]
The workaround won't be necessary anymore next week. We've corrected the metadata and the next version will contain the missing parameters.
