### ISSUE TITLE
users/item/messages/count.CountRequestBuilderGetRequestConfiguration is missing a QueryParameters field

### ISSUE THREAD

**Issue by r0nli** [microsoftgraph/msgraph-sdk-go#320]
Hi, I'm trying to count the number of messages that match a specific filter using something like this:

```
import "github.com/microsoftgraph/msgraph-sdk-go/users/item/messages/count"

var options count.CountRequestBuilderGetRequestConfiguration

filter = "isDraft eq false"
options.QueryParameters.Filter = &filter

client.UsersById(userId).Messages().Count().Get(context.Background(), &options)
```

However, the CountRequestBuilderGetRequestConfiguration struct does not contain a QueryParameters field.

I'd expect this request configuration object to match github.com/microsoftgraph/msgraph-sdk-go/users/item/messages.MessagesRequestBuilderGetQueryParameters - where this field is present and behaves as expected

Would you kindly fix this issue?

**Comment by baywet** [comment]
Hi @r0nli 
Thanks for letting us know, it appears to be a bug in the conversion library which I just [logged a bug for](https://github.com/microsoft/OpenAPI.NET.OData/issues/313)
Once it gets fixed, the SDK will be refreshed on the next Tuesday and contain the missing query parameter.

**Comment by baywet** [comment]
Thanks for the patience, the bug has been fixed. Now [we're waiting on a release of the conversion tool we use](https://github.com/microsoft/OpenAPI.NET/pull/1117)

**Comment by baywet** [comment]
Hi @r0nli 
Thanks for the patience, we believe this is now rolled out as part of v0.54.0.
Can you upgrade your dependency and let us know please?
Thanks

**Comment by r0nli** [comment]
Hi @baywet,

I can confirm that the fix works.

Thanks!
