### ISSUE TITLE
Only first page of results in available when using any api

### ISSUE THREAD

**Issue by arunpassi** [microsoftgraph/msgraph-sdk-go#33]
When using client.Users().Get(), it only gives the first 100 results. GetNextLink() returns the url for retrieving the next set of results but there doesn't seems to be any way of passing that url back into the client.Users().Get() or any other api.

Alternatively, when trying to pass Top or Skip options to the client.Users().Get(options), the request fails with error 400. "The query specified in the URI is not valid. The requested resource is not a collection. Query options $filter, $orderby, $count, $skip, and $top can be applied only on collections."

**Comment by baywet** [comment]
Hi again @arunpassi, 
Thanks for reaching out and for trying the SDK.

We had a similar conversion in another issue recently, [this comment should help you out](https://github.com/microsoftgraph/msgraph-sdk-go/issues/30#issuecomment-979973608)

Please go upvote [this feature](https://github.com/microsoftgraph/msgraph-sdk-go-core/issues/13) if you think it could help

**Comment by baywet** [comment]
additionally, since we received that question multiple times, I think it should be an example on the readme until we have the page iterator. Would you be willing to submit a pull request to add that to the readme?

**Comment by arunpassi** [comment]
Thanks for providing the solution.
I tried to create a branch but failed to commit with authentication denied (tried creating personal access token but I don't know how to use it either)

**Comment by baywet** [comment]
Thanks for trying to put a PR together. You should fork the repo, make the changes on your fork and then open the pull request from your fork to this repo.
