### ISSUE TITLE
File names are too long

### ISSUE THREAD

**Issue by meain** [microsoftgraph/msgraph-sdk-go#338]
With the latest version (`v0.48.0`), filenames have got quite long that clone/build can fail in some filesystems (I know it fails in `ext4` even if I clone at `$HOME`). Currently working around by cloning to `/tmp` which is not ideal.

<details>
<summary> Clone logs </summary>
<pre>
Cloning into 'msgraph-sdk-go'...
remote: Enumerating objects: 360476, done.
remote: Counting objects: 100% (64287/64287), done.
remote: Compressing objects: 100% (7157/7157), done.
remote: Total 360476 (delta 59109), reused 60623 (delta 57130), pack-reused 296189
Receiving objects: 100% (360476/360476), 78.08 MiB | 1.70 MiB/s, done.
Resolving deltas: 100% (245410/245410), done.
error: unable to create file deviceappmanagement/device_app_management_mobile_app_configurations_item_device_statuses_managed_device_mobile_app_configuration_device_status_item_request_builder.go: File name too long
error: unable to create file devicemanagement/device_management_device_compliance_policies_item_scheduled_actions_for_rule_device_compliance_scheduled_action_for_rule_item_request_builder.go: File name too long
error: unable to create file devicemanagement/device_management_device_compliance_policies_item_scheduled_actions_for_rule_item_scheduled_action_configurations_device_compliance_action_item_item_request_builder.go: File name too long
error: unable to create file devicemanagement/device_management_device_compliance_policy_setting_state_summaries_item_device_compliance_setting_states_device_compliance_setting_state_item_request_builder.go: File name too long
error: unable to create file devicemanagement/device_management_windows_information_protection_app_learning_summaries_windows_information_protection_app_learning_summary_item_request_builder.go: File name too long
error: unable to create file devicemanagement/device_management_windows_information_protection_network_learning_summaries_windows_information_protection_network_learning_summary_item_request_builder.go: File name too long
error: unable to create file groups/groups_item_calendar_calendar_view_item_instances_item_multi_value_extended_properties_multi_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file groups/groups_item_calendar_calendar_view_item_instances_item_single_value_extended_properties_single_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file groups/groups_item_conversations_item_threads_item_posts_item_in_reply_to_multi_value_extended_properties_multi_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file groups/groups_item_conversations_item_threads_item_posts_item_in_reply_to_single_value_extended_properties_single_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file groups/groups_item_conversations_item_threads_item_posts_item_multi_value_extended_properties_multi_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file groups/groups_item_conversations_item_threads_item_posts_item_single_value_extended_properties_single_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file groups/groups_item_drives_item_items_item_list_item_get_activities_by_interval_with_start_date_time_with_end_date_time_with_interval_request_builder.go: File name too long
error: unable to create file groups/groups_item_sites_item_lists_item_items_item_get_activities_by_interval_with_start_date_time_with_end_date_time_with_interval_request_builder.go: File name too long
error: unable to create file groups/groups_item_sites_item_term_stores_item_sets_item_parent_group_sets_item_children_item_children_item_relations_item_from_term_request_builder.go: File name too long
error: unable to create file groups/groups_item_team_channels_item_does_user_have_accessuser_id_user_id_tenant_id_tenant_id_user_principal_name_user_principal_name_request_builder.go: File name too long
error: unable to create file groups/groups_item_team_primary_channel_does_user_have_accessuser_id_user_id_tenant_id_tenant_id_user_principal_name_user_principal_name_request_builder.go: File name too long
error: unable to create file identitygovernance/identity_governance_access_reviews_definitions_item_instances_item_stages_item_decisions_access_review_instance_decision_item_item_request_builder.go: File name too long
error: unable to create file identitygovernance/identity_governance_entitlement_management_assignments_additional_access_with_access_package_id_with_incompatible_access_package_id_request_builder.go: File name too long
error: unable to create file identitygovernance/identity_governance_entitlement_management_catalogs_item_access_packages_item_access_packages_incompatible_with_access_package_item_request_builder.go: File name too long
error: unable to create file identitygovernance/identity_governance_entitlement_management_catalogs_item_access_packages_item_assignment_policies_access_package_assignment_policy_item_request_builder.go: File name too long
error: unable to create file identitygovernance/identity_governance_entitlement_management_catalogs_item_access_packages_item_incompatible_access_packages_access_package_item_request_builder.go: File name too long
error: unable to create file me/me_calendar_groups_item_calendars_item_calendar_view_item_instances_item_multi_value_extended_properties_multi_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file me/me_calendar_groups_item_calendars_item_calendar_view_item_instances_item_single_value_extended_properties_single_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file me/me_calendar_groups_item_calendars_item_calendar_view_item_multi_value_extended_properties_multi_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file me/me_calendar_groups_item_calendars_item_calendar_view_item_single_value_extended_properties_single_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file me/me_calendar_groups_item_calendars_item_events_item_instances_item_multi_value_extended_properties_multi_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file me/me_calendar_groups_item_calendars_item_events_item_instances_item_single_value_extended_properties_single_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file me/me_calendar_groups_item_calendars_item_events_item_single_value_extended_properties_single_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file me/me_calendars_item_calendar_view_item_instances_item_multi_value_extended_properties_multi_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file me/me_calendars_item_calendar_view_item_instances_item_single_value_extended_properties_single_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file me/me_contact_folders_item_child_folders_item_contacts_item_multi_value_extended_properties_multi_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file me/me_contact_folders_item_child_folders_item_contacts_item_single_value_extended_properties_single_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file me/me_joined_teams_item_channels_item_does_user_have_accessuser_id_user_id_tenant_id_tenant_id_user_principal_name_user_principal_name_request_builder.go: File name too long
error: unable to create file me/me_joined_teams_item_primary_channel_does_user_have_accessuser_id_user_id_tenant_id_tenant_id_user_principal_name_user_principal_name_request_builder.go: File name too long
error: unable to create file me/me_mail_folders_item_child_folders_item_messages_item_multi_value_extended_properties_multi_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file me/me_mail_folders_item_child_folders_item_messages_item_single_value_extended_properties_single_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file models/groups_item_team_primary_channel_does_user_have_accessuser_id_user_id_tenant_id_tenant_id_user_principal_name_user_principal_name_responseable.go: File name too long
error: unable to create file models/identity_governance_entitlement_management_assignments_additional_access_with_access_package_id_with_incompatible_access_package_id_responseable.go: File name too long
error: unable to create file models/identity_governance_entitlement_management_connected_organizations_item_external_sponsors_get_available_extension_properties_post_request_body.go: File name too long
error: unable to create file models/identity_governance_entitlement_management_connected_organizations_item_external_sponsors_get_available_extension_properties_post_request_bodyable.go: File name too long
error: unable to create file models/identity_governance_entitlement_management_connected_organizations_item_internal_sponsors_get_available_extension_properties_post_request_body.go: File name too long
error: unable to create file models/identity_governance_entitlement_management_connected_organizations_item_internal_sponsors_get_available_extension_properties_post_request_bodyable.go: File name too long
error: unable to create file models/me_joined_teams_item_channels_item_does_user_have_accessuser_id_user_id_tenant_id_tenant_id_user_principal_name_user_principal_name_responseable.go: File name too long
error: unable to create file models/me_joined_teams_item_primary_channel_does_user_have_accessuser_id_user_id_tenant_id_tenant_id_user_principal_name_user_principal_name_response.go: File name too long
error: unable to create file models/me_joined_teams_item_primary_channel_does_user_have_accessuser_id_user_id_tenant_id_tenant_id_user_principal_name_user_principal_name_responseable.go: File name too long
error: unable to create file models/users_item_joined_teams_item_channels_item_does_user_have_accessuser_id_user_id_tenant_id_tenant_id_user_principal_name_user_principal_name_response.go: File name too long
error: unable to create file models/users_item_joined_teams_item_channels_item_does_user_have_accessuser_id_user_id_tenant_id_tenant_id_user_principal_name_user_principal_name_responseable.go: File name too long
error: unable to create file models/users_item_joined_teams_item_primary_channel_does_user_have_accessuser_id_user_id_tenant_id_tenant_id_user_principal_name_user_principal_name_response.go: File name too long
error: unable to create file models/users_item_joined_teams_item_primary_channel_does_user_have_accessuser_id_user_id_tenant_id_tenant_id_user_principal_name_user_principal_name_responseable.go: File name too long
error: unable to create file users/users_item_calendar_calendar_view_item_instances_item_multi_value_extended_properties_multi_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file users/users_item_calendar_calendar_view_item_instances_item_single_value_extended_properties_single_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file users/users_item_calendar_groups_item_calendars_item_calendar_view_item_instances_item_multi_value_extended_properties_multi_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file users/users_item_calendar_groups_item_calendars_item_calendar_view_item_instances_item_single_value_extended_properties_single_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file users/users_item_calendar_groups_item_calendars_item_calendar_view_item_multi_value_extended_properties_multi_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file users/users_item_calendar_groups_item_calendars_item_calendar_view_item_single_value_extended_properties_single_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file users/users_item_calendar_groups_item_calendars_item_events_item_instances_item_multi_value_extended_properties_multi_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file users/users_item_calendar_groups_item_calendars_item_events_item_instances_item_single_value_extended_properties_single_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file users/users_item_calendar_groups_item_calendars_item_events_item_multi_value_extended_properties_multi_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file users/users_item_calendar_groups_item_calendars_item_events_item_single_value_extended_properties_single_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file users/users_item_calendars_item_calendar_view_item_instances_item_multi_value_extended_properties_multi_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file users/users_item_calendars_item_calendar_view_item_instances_item_single_value_extended_properties_single_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file users/users_item_calendars_item_events_item_instances_item_multi_value_extended_properties_multi_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file users/users_item_calendars_item_events_item_instances_item_single_value_extended_properties_single_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file users/users_item_contact_folders_item_child_folders_item_contacts_item_multi_value_extended_properties_multi_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file users/users_item_contact_folders_item_child_folders_item_contacts_item_single_value_extended_properties_single_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file users/users_item_contact_folders_item_child_folders_item_single_value_extended_properties_single_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file users/users_item_joined_teams_item_channels_item_does_user_have_accessuser_id_user_id_tenant_id_tenant_id_user_principal_name_user_principal_name_request_builder.go: File name too long
error: unable to create file users/users_item_joined_teams_item_primary_channel_does_user_have_accessuser_id_user_id_tenant_id_tenant_id_user_principal_name_user_principal_name_request_builder.go: File name too long
error: unable to create file users/users_item_mail_folders_item_child_folders_item_messages_item_multi_value_extended_properties_multi_value_legacy_extended_property_item_request_builder.go: File name too long
error: unable to create file users/users_item_mail_folders_item_child_folders_item_messages_item_single_value_extended_properties_single_value_legacy_extended_property_item_request_builder.go: File name too long
Updating files: 100% (15327/15327), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
</pre>
</details>

**Comment by baywet** [comment]
Hi @meain,
Thanks for using the Go SDK and letting us know.
Were you having the same issue with earlier versions?
What OS are you using?
Can you try with v0.49.0, we've made a small patch that shortens the file names by omitting the first segment name.

The max file name length with linux [is supposed to be 255](https://serverfault.com/questions/9546/filename-length-limits-on-linux) chars depending on the code point, and none of the entries from the log you shared exceed that length or come close to it.

**Comment by baywet** [comment]
Thanks for sharing your discoveries here. Since this is a encryption utility issue, I'm going to go ahead and close this issue. The solution being not to map the SDK onto encrypted partitions until that bug gets fixed.

**Comment by meain** [comment]
I'm not sure if you are planning/willing to take this any further, but `encryptfs` sees this more as a necessary limitation instead of a bug and don't have any plans to "fix" it.

> This bug is considered 'fixed' by the upstream maintainers. The eCryptfs kernel error message has been reduced to a debug level log message and eCryptfs now correctly reports its maximum supported filename length through the statfs() syscall. This is all that can be done without implementing a completely new encrypted filename design. A design that allows 255 character filenames without introducing other design limitations has not been identified and no one is currently working to come up with such a design.
