### ISSUE TITLE
Missing DeviceEnrollmentType value

### ISSUE THREAD

**Issue by ClementBouchard** [microsoftgraph/msgraph-sdk-go#339]
While iterating on devices, it is failing due to missing 'DeviceEnrollmentType' value.
See the following error output:
`unable to list devices: Unknown DeviceEnrollmentType value: azureAdJoinUsingAzureVmExtension`

Is there any reason why some values have not been implemented in this sdk while it has been done on msgraph-beta-sdk-go ?
See https://github.com/microsoftgraph/msgraph-beta-sdk-go/blob/62848feaab6cd72535d80d10949407ba11f3662f/models/device_enrollment_type.go

**Comment by baywet** [comment]
Bonjour @ClementBouchard,
Thanks for using the Go SDK and for reaching out.
Looking at the v1 service metadata, this enum option is not present. My guess is that it's either a ne new option that needs to be rolled out by the service or an overlook.
Could you provide us with the endpoint you're querying so we can engage with the service team please?

**Comment by baywet** [comment]
Thanks for the additional details. I'd like to make sure I understand the issue properly.
Could the issue be unrelated to the fact that your application is paging? It just so happens that records with that enum value are present only on the next pages, but if they were present on the first one, you'd be getting the issue with the first request?

**Comment by baywet** [comment]
Thanks for the follow up. The team closed the incident reporting that this work is part of their feature rollout, they haven't provided any ETA however.
The best course of action at this point is probably for you to open a support ticket on a production tenant referencing the ICM number above to get more attention on it.

**Comment by rkodev** [comment]
Hi @ClementBouchard , The missing values are available in release [v0.93.0](https://github.com/microsoftgraph/msgraph-beta-sdk-go/blob/main/models/device_enrollment_type.go)
