### ISSUE TITLE
`$select` query not working for `@content.downloadUrl` in delta api

### ISSUE THREAD

**Issue by meain** [microsoftgraph/msgraph-sdk-go#340]
I am trying to pull data from OneDrive delta api with select query parameter specified, but it does not seem to return the `@content.downloadUrl` info for files.

``` go
builder := service.Client().DrivesById(driveID).Root().Delta()
requestFields := []string{"id", "@content.downloadUrl"}
requestConfig := &msdrives.DrivesItemRootDeltaRequestBuilderGetRequestConfiguration{
	QueryParameters: &msdrives.DrivesItemRootDeltaRequestBuilderGetQueryParameters{
		Select: requestFields,
	},
}
r, err := builder.Get(ctx, requestConfig)
```

From the logs, this looks like the query that is being fired:

```
https://graph.microsoft.com/v1.0/drives/<drive-id>/root/microsoft.graph.delta()?$select=id%2C%40content.downloadUrl
```

This gives me just the `id` (plus `@odata.type` and `@odata.etag`), but `@content.downloadUrl` is not available. With the `$` removed from `$select`, it works as expected.

Probably related to https://github.com/microsoftgraph/msgraph-sdk-go/issues/130.

**Comment by baywet** [comment]
Hi @meain,
Thanks for reaching out and for using the Go SDK.
$ in from of OData query parameters is mandatory in v1.0 for Microsoft Graph.
The fact that Filed/Drives endpoints accept select without the $ sign is an issue in itself.
This repository and its issues is reserved to issues about the SDK itself and the service team is not watching it.
Can you create a new thread [in the dedicated Microsoft Q&A forum](https://learn.microsoft.com/en-us/answers/topics/microsoft-graph-files.html) only mentioning the difference in URLs (no need to include the Go snippets) so the service team is made away of that issue please?

**Comment by meain** [comment]
Looks like it should `content.downloadURL` when using with `$select`.
