### ISSUE TITLE
Retry for `POST` requests ends up with a `400 Bad Request`

### ISSUE THREAD

**Issue by meain** [microsoftgraph/msgraph-sdk-go#341]
Here is an example scenario where I am trying to create a new folder.

``` go
rawUrl := "https://graph.microsoft.com/v1.0/drives/<drive-id>/items/<item-id>/children"
builder := drive.NewDriveItemsRequestBuilder(rawURL, adapter)

item := newItem("dummy", true)
newItem, err := builder.Post(context.Background(), item, nil)
```

If the first request to create it fails with 429 because it got throttled and was retried, it always ends up with 400. Checking the `req.ContentLength`, it seems like it gets reduced from ~140 bytes the first time to ~25 bytes the second time.

Error returned:
```
{"error":{"code":"BadRequest","message":"Empty Payload. JSON content expected.","innerError":{"date":"2022-12-14T09:48:15","request-id":"c9e2a...cd1990f56","client-request-id":"2b4...1eb2"}}}
```

**Comment by meain** [comment]
Don't think this is from the compression middleware. I dropped the compression middleware completely and it was still having similar behavior with the second request giving a 400. That said `req.ContentLength` is `0` in both requests now.

**Comment by baywet** [comment]
The retry handler is [not doing anything with the request body when retrying](https://github.com/microsoft/kiota-http-go/blob/dee3530def1b4fe83088a20a5bd86ecc462444da/retry_handler.go#L135)
From the docs, [it looks like the body gets closed on the initial request submission](https://pkg.go.dev/net/http#Request) but the request adapter [uses a noop closer](https://github.com/microsoft/kiota-http-go/blob/dee3530def1b4fe83088a20a5bd86ecc462444da/nethttp_request_adapter.go#L246)
So it's probably a matter of [Seeking the body to 0](https://pkg.go.dev/bytes#Reader.Seek) before trying again if it's present.
Would you be willing to put a pull request together to address this?

**Comment by meain** [comment]
Don't think we can add a `Seek` here as `NopCloser` returns a `io.ReadCloser` and does not implement `io.Seeker`.

**Comment by baywet** [comment]
Thanks for pointing this. We could alternatively implement our own https://pkg.go.dev/io#ReadSeekCloser
