### ISSUE TITLE
Missing AndroidDeviceOwnerGeneralDeviceConfiguration

### ISSUE THREAD

**Issue by preslavgerchev** [microsoftgraph/msgraph-sdk-go#343]
While iterating over the possible device configurations, I noticed that `AndroidDeviceOwnerGeneralDeviceConfiguration` is missing from the sdk, while it is present in the beta-sdk: https://github.com/microsoftgraph/msgraph-beta-sdk-go/blob/main/models/android_device_owner_general_device_configuration.go#L8

Here's how my request looks like, using default config struct:
```
resp, err := client.DeviceManagement().DeviceConfigurations().Get(ctx, &devicemanagement.DeviceManagementDeviceConfigurationsRequestBuilderGetRequestConfiguration{})
```

Was wondering if there are plans to add this to this sdk too?

**Comment by baywet** [comment]
Hi @preslavgerchev,
Thanks for using the Go SDK and for reaching out.
The SDK (both v1 and beta) are auto-generated from the service metadata. API owners decide when/if a specific model/endpoint/property gets promoted from v1 to beta after it becomes stable. [Some more reading on the topic](https://learn.microsoft.com/en-us/graph/versioning-and-support#beta-version)
The only situation that'd be anormal would be if properties/models/endpoints are missing in the SDK but available on the API (for the same version), that'd indicate a gap in the metadata that needs to be addressed.
Do you have access to those properties in the v1 API when querying the endpoint directly?

**Comment by preslavgerchev** [comment]
Hi @baywet,
Thanks for the reply! I tested the endpoint via the msgraph explorer and indeed the model is not exposed, so there's no mismatch.
Closing this as it's a non-issue on the go sdk side
