### ISSUE TITLE
Teams Api: Requested API is not supported

### ISSUE THREAD

**Issue by RobinKamps** [microsoftgraph/msgraph-sdk-go#346]
```
result, err := g.Client.Teams().Get(context.Background(), nil)
```

has err: 
```
error: error status code received from the APIcode: NotFoundmsg: Requested API is not supported. Please check the path.
```

(accessing other graph resources e.g. users works fine)

version
```
	github.com/microsoftgraph/msgraph-sdk-go v0.48.0 // indirect
	github.com/microsoftgraph/msgraph-sdk-go-core v0.30.1 // indirect
```

**Comment by baywet** [comment]
Hi @RobinKamps 
Thanks for using the SDK and for reaching out.
This operation is [an inaccuracy of the metadata we use to generate the SDK](https://learn.microsoft.com/en-us/graph/teams-list-all-teams?context=graph%2Fapi%2F1.0&view=graph-rest-1.0)

Depending on what you're trying to achieve you can either [list all teams](https://learn.microsoft.com/en-us/graph/teams-list-all-teams?context=graph%2Fapi%2F1.0&view=graph-rest-1.0) or [list the teams a user has joined](https://learn.microsoft.com/en-us/graph/api/user-list-joinedteams?view=graph-rest-1.0&tabs=http)

I hope this helps, let us know if you have further questions.

**Comment by RobinKamps** [comment]
Thank you - with groups and a filter it is working. Wondering, why graph permissions under portal.azure.com for Team and TeamMember exist, if only Groups are accessible (and Teams permission alone

**Comment by RobinKamps** [comment]
Furthermore Orderby from GroupsRequestBuilderGetQueryParameters seems to be not supported.
E.g.

```
	query := groups.GroupsRequestBuilderGetQueryParameters{
		Orderby: []string{"displayName"},
		Select: []string{"displayName", "id", "mail"},
		Filter: &filter,
	}
	queryConfig := &groups.GroupsRequestBuilderGetRequestConfiguration{
		QueryParameters: &query,
	}
	result, err := g.Client.Groups().Get(context.Background(), queryConfig)
```

leads to api error:
```
error: error status code received from the APIcode: Request_UnsupportedQuerymsg: Sorting not supported for current query.
```

**Comment by baywet** [comment]
For that to work you need to set the ConsistencyLevel header to eventual, and set the count query parameter to true.
More reading on the subject
https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-advanced-queries-for-directory-objects-are-now-generally-available/

**Comment by RobinKamps** [comment]
Thank you very much.
