### ISSUE TITLE
ConversationMemberable has no userID and no email fields

### ISSUE THREAD

**Issue by RobinKamps** [microsoftgraph/msgraph-sdk-go#355]
the return of  ```result, err := graphClient.TeamsById("team-id").Members().Get(context.Background(), nil)``` as described in https://learn.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-1.0&tabs=go
has only role and displayName (and the memberID).  `ConversationMemberable` is missing userID and email.

**Comment by baywet** [comment]
Hi @RobinKamps,
Thanks for using the Go SDK and for reaching out.
You need to type assert to the target type to access the additional properties. Something like

```go
result, err := graphClient.TeamsById("team-id").Members().Get(context.Background(), nil)
if firstUser, ok := result.GetValue()[0].(models.AadUserConversationMemberable); ok {
   firstUser.GetEmail()
}
```
where models is an import of `github.com/microsoftgraph/msgraph-sdk-go/models`.

Let us know if you have further questions.

**Comment by RobinKamps** [comment]
Thank you very much.
