### ISSUE TITLE
create team documentation is missing odata type

### ISSUE THREAD

**Issue by RobinKamps** [microsoftgraph/msgraph-sdk-go#356]
the golang examples under https://learn.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&tabs=go are missing the member odata type, e.g.
```
odataType := "#microsoft.graph.aadUserConversationMember"
conversationMember..SetOdataType(&odataType)
```

**Comment by RobinKamps** [comment]
documentation of add members
https://learn.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&tabs=http
and add members in bulk 
https://learn.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-1.0&tabs=http
are missing the odata type, too

**Comment by baywet** [comment]
@rkodev I believe the fix you've implemented [here](https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/1361) will address this issue, do you concur?

**Comment by rkodev** [comment]
@baywet Yes, this will be closed by https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/1361
