### ISSUE TITLE
Cannot get workbook from a drive item

### ISSUE THREAD

**Issue by DjLeChuck** [microsoftgraph/msgraph-sdk-go#363]
Hi,

First of all, I'm pretty new with Go and more with Azure so sorry if my question seems a bit stupid. 😅 

My goal is to read the specific worksheet of a workbook in the drive of a user. I see there is a `Get Range` API endpoint which is exactly what I need (I think): https://learn.microsoft.com/en-us/graph/api/range-get?view=graph-rest-1.0&tabs=http

So, with this in mind, I'm trying to work with the SDK and I'm a bit confused. This is my code for now:

```go
func main() {
	cred, err := azidentity.NewClientSecretCredential("xxx", "xxx", "xxx", nil)
	if err != nil {
		fmt.Printf("Error creating credentials: %v\n", err)
	}

	client, err := msgraphsdk.NewGraphServiceClientWithCredentials(cred, nil)
	if err != nil {
		fmt.Printf("Error creating client: %v\n", err)
		return
	}

	drive, err := client.UsersById("xxx").Drive().Get(context.Background(), nil)
	if err != nil {
		fmt.Printf("Error getting the drive: %v\n", err)
		printOdataError(err)
		return
	}

	item, err := client.DrivesById(*drive.GetId()).ItemsById("xxx").Get(context.Background(), nil)
	if err != nil {
		fmt.Printf("Error getting the drive: %v\n", err)
		printOdataError(err)
		return
	}

	fmt.Printf("OdataType: %v\n", *item.GetOdataType()) # "#microsoft.graph.driveItem"
	fmt.Printf("Name: %v\n", *item.GetName()) # "my_file.xlsx"
	fmt.Printf("Workbook: %v", item.GetWorkbook()) # "nil"
}
```

As you can see, `item.GetWorkbook()` return `nil` and not the workbook. I don't know if it's normal because I'm missing something or if it's a lack on the API (I think it's the first guess 😄 )

Thank you for your help!

**Comment by baywet** [comment]
Hi @DjLeChuck 
Thanks for reporting this.
After taking a look at it, it appears we have several issues in our metadata conversion process.
I've logged [an issue](https://github.com/microsoft/OpenAPI.NET.OData/issues/327) in the conversion process as well as [created a pull request in the metadata fixup process](https://github.com/microsoftgraph/msgraph-metadata/pull/247)

Long story short, the workbook operations won't be available everywhere a drive item is available, this is to avoid the SDKs getting too big. But it should at least be available here.

```go
client.DrivesById("driveid").ItemsById("itemId").Workbook().WorksheetById("sheetId").Range("someRange").Get(ctx, nil)
```

**Comment by DjLeChuck** [comment]
Thank you for explainations "oh great overlord"! 😉 

Maybe I'm missing something, but `client.DrivesById("xxx").ItemsById("xxx").Workbook()` is not working:

```
client.DrivesById("xxx").ItemsById("xxx").Workbook undefined (type *drives.ItemItemsDriveItemItemRequestBuilder has no field or method Workbook
```

**Comment by baywet** [comment]
to be clear, this will only be available when we fix the metadata issue and generate a new version of the SDK.
We've investigated the issue further https://github.com/microsoftgraph/msgraph-metadata/issues/248

**Comment by DjLeChuck** [comment]
Oh sorry I've misunderstood you're answer. 😅

So I'm going to wait for this, thank you!

**Comment by baywet** [comment]
Hi @DjLeChuck 
Version 0.54.0 should address this. We've fixed the metadata to make sure the path items are reflected in the SDK.
After upgrading you should see all the Excel related APIs under the main drives path.
So something like

```Go
client.DrivesById("driveId").ItemWithPath("excelFilePath.xlsx").Workbook()...
```

Let us know if you have further questions.
