### ISSUE TITLE
Top-level error messages are not helpful

### ISSUE THREAD

**Issue by eric-millin** [microsoftgraph/msgraph-sdk-go#370]
**Description**

The top-level error messages are generally unhelpful. E.g., 

```go
	result, err := client.Users().Get(ctx, configWithSyntaxError)
	if err != nil {
		fmt.Println(err)
	}
```

prints

> error status code received from the API

Which doesn't tell me anything. Digging through the nested error data takes a lot work. I ended up having to write the following logging wrapper to get helpful information.

```go
func LogClientError(logger *zap.Logger, msg string, err error, zFields ...zap.Field) {
	logger = logger.WithOptions(zap.AddCallerSkip(1))

	zFields = append(zFields,
		zap.Error(err),
	)

	var odErr *odataerrors.ODataError
	if errors.As(err, &odErr) {
		zFields = append(zFields, zap.String("api_error", odErr.ApiError.Message))

		if mErr := odErr.GetError(); mErr != nil {
			zFields = append(zFields,
				zap.Stringp("main_error", mErr.GetMessage()),
				zap.Stringp("main_error_code", mErr.GetCode()),
				zap.Stringp("main_error_target", mErr.GetTarget()),
			)
		}
	}

	logger.Error(msg, zFields...)
}
```

which yields

```json
	{
	  "level": "error",
	  "caller": "mypkg/myfile.go:72",
	  "msg": "my message",
	  "error": "error status code received from the API",
	  "api_error": "",
	  "main_error": "Syntax error: character ':' is not valid at position 3 in 'bl :~'",
	  "main_error_code": "BadRequest",
	  "main_error_target": null,
	}
```

It shouldn't be that hard.

Also, `MainError` doesn't implement the `error` interface and afaict none of the errors implement `Unwrap`. Together, that means I can't use `errors.As` to get the `MainError` without a lot of digging.

**Expected**

- SDK `someErr.Error()` yields something like

> error status code received from the API: BadRequest: "Syntax error: character ':' is not valid at position 3 in 'bl :~'"

- All errors implement `error` interface
- Errors implement `Unwrap`, if appropriate
- `errors.As` can get `MainError`

**Actual** 

SDK `someErr.Error()` yields 

> error status code received from the API

- `MainError` does not implement `error` interface
- Errors do not implement `Unwrap`
- `errors.As` cannot get `MainError`

**Comment by baywet** [comment]
Hi @eric-millin,
Thanks for using the Go SDK and for the feedback. You're not the first one to outline the fact that the error experience of the SDK could be improved. I'm consolidating things under #313 to ease up planning on our side. And I suggest you follow things over there to be notified of progress.
