### ISSUE TITLE
Is it possible to pass the result of  Azure CLI login?

### ISSUE THREAD

**Issue by ken5scal** [microsoftgraph/msgraph-sdk-go#380]
Hi, is it possible to pass the result of Azure CLI login to this library?

The purpose is to run this sdk within Github Action so that I can utilize [azure/login](https://github.com/marketplace/actions/azure-login) for a key-less authentication between Github and Azure AD.

Thanks in advance.

**Comment by baywet** [comment]
Hi @ken5scal 
Thanks for using the Go SDK and for reaching out.
I believe you should be able to as long as you use the [CLI credential](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#AzureCLICredential) when building the Azure Identity authentication provider.

**Comment by ken5scal** [comment]
Hi @baywet 
Thanks for quick response. 
It actually worked. Thanks!

```
creds, _ := azidentity.NewAzureCLICredential(
		&azidentity.AzureCLICredentialOptions{TenantID: os.Getenv("AAD_TENANT_ID")},
	)

client, _ := msgraphsdkgo.NewGraphServiceClientWithCredentials(creds, []string{})
```
