### ISSUE TITLE
Is small files upload supported?

### ISSUE THREAD

**Issue by franklanganke** [microsoftgraph/msgraph-sdk-go#387]
Is uploading small files supported? As described here: 

https://learn.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&tabs=http

I got authentication and retrieving of existing drives and folders working, however I am stuck on defining put content requests. The drives import is missing the New* (model / builder) functions that are referenced in the example snippets.

```
import (
	msgraphsdk "github.com/microsoftgraph/msgraph-sdk-go"
	drives "github.com/microsoftgraph/msgraph-sdk-go/drives"
...

	parentID := "abc123" // ID of an existing folder
        driveID := "cde456" // ID of a sharepoint doc lib
	
	folder, err := client.DrivesById(driveID).ItemsById(parentID).Get(ctx, nil)
	if err != nil {
		return nil, errors.Wrap(err, "request error")
	}
	fmt.Println("folder: ", *folder.GetName())
```

**Comment by rkodev** [comment]
Hi @franklanganke Thanks for tyring the beta SDK. 
You should be able to use the current syntax

```go
client.DrivesById(driveID).ItemsById(parentID).Content().Put(ctx, `bytes to upload`, nil)
```

**Comment by franklanganke** [comment]
Thank you, this worked.

```
parentID := "xyc" // ID of a folder
itemID := "root:/foo.txt:"
err = client.DrivesById(driveID).ItemsById(itemID).Content().Put(ctx, []byte("payload"), nil)
```
