### ISSUE TITLE
Example for creating a new folder in a drive?

### ISSUE THREAD

**Issue by franklanganke** [microsoftgraph/msgraph-sdk-go#388]
Is it currently possible to create a new folder?

https://learn.microsoft.com/en-us/graph/api/driveitem-post-children?view=graph-rest-1.0&tabs=http

**Comment by rkodev** [comment]
Hi @franklanganke, The sdk does not support this specific call, however here is an alternative you can try out to create a folder and folders

```go
	item := models.NewDriveItem()
	name := "New Folder"
	item.SetName(&name)
	client.DrivesById("drive-item").Items().Post(context.Background(), item, nil)

```

**Comment by franklanganke** [comment]
Thank you, I was able to create a folder with a small addition:
```
item := models.NewDriveItem()
name := "uploads"
item.SetName(&name)
item.SetFolder(models.NewFolder()) 
drvItm, err := client.DrivesById(driveID).Items().Post(context.Background(), item, nil)
```

Follow-up question:
Is it possible to set an existing folder as a parent in order to create subfolders?

**Comment by rkodev** [comment]
Yes. This is possible. You can achive this by 

```go

	subfolder := models.NewDriveItem()
	subfolderName := "subfolderName"
	subfolder.SetName(&subfolderName)
	subfolder.SetFolder(drvItm.GetFolder()) // use the newly created name
```

**Comment by franklanganke** [comment]
@rkodev The sample does not work for me. The subfolder will always be created on the root level. I tried using programmatically and manually created parent folders as references.

**Comment by rkodev** [comment]
Hi @franklanganke , We discovered an issue with the drive api and there is a new release that should allow you to create subfolders. Try release `0.54.0` and use this syntax and confrim if it now works.

```go
subfolder:= models.NewDriveItem()
name := "subfolder"
subfolder.SetName(&name)
subfolder.SetFolder(models.NewFolder()) 
client.DrivesById("root").ItemsById("parentFolderId").Children().Post(context.Background(), subfolder, nil)
```

**Comment by franklanganke** [comment]
Can confirm, as of v0.54.0 I can create subfolders like a boss.
