### ISSUE TITLE
Feature Request: isMfaRegistered not available in MSGraph SDK but available in Beta version

### ISSUE THREAD

**Issue by djuneja-uptycs** [microsoftgraph/msgraph-sdk-go#389]
### Feature Request:
  * MSGraph SDK used: `github.com/microsoftgraph/msgraph-sdk-go v0.49.0`
  * When trying to fetch the user information using the User Call: `c.client.Users().Get(ctx, options)`, it does not have the MFA Registered information for users.
  * MSGraph Beta SDK already have this information. We can just pass this as the query parameters and it will return the field `isMfaRegistered` as part of the response for each user.

**Comment by rkodev** [comment]
Hi @djuneja-uptycs, please do note that this should be expected, to an extent, when comparing the sdk's. There is no guarantee that this sdk version will have all the fields present in `Beta` or vice-versa as the `Beta` version is design to provide early access to some new features, or deprecate old ones to be tested out. These features may eventually make it to the stable sdk.

**Comment by djuneja-uptycs** [comment]
@rkodev Thanks for reverting back and apologies for not getting back to you sooner, I see the ticket has been marked as closed automatically. I opened the ticket only to get a tentative timeline of when can we expect this feature in the stable version of the sdk. Based on that we can plan our timelines too.

Thanks.
