### ISSUE TITLE
Sample code to get users fails with permissions error

### ISSUE THREAD

**Issue by dwschulze** [microsoftgraph/msgraph-sdk-go#393]
Here's the error:

Authorization_RequestDeniedmsg: Insufficient privileges to complete the operation

My registered app has:

Files.Read
offline_access
openid
profile
User.Read.All
User.ReadWrite.All

The last two have Admin consent granted "Yes".

**Comment by baywet** [comment]
Can you share the code setting up the client as well as the code making the request please? (without any secret)

**Comment by dwschulze** [comment]
The code to setup the client was as shown in the readme.  That was the problem.  The client has to be

client, err := msgraphsdk.NewGraphServiceClientWithCredentials(cred, []string{"User.Read.All"})

Do I need to set the API permissions on the registered app, or just include them when creating the client, or both?

**Comment by baywet** [comment]
how are you setting up the credentials?

**Comment by baywet** [comment]
and how are you making the request?

**Comment by shachardevops** [comment]
I am having the same issue, the difference is that I am having JWT token 
```
cred := accessToken(azcore.AccessToken{
		Token:     oauthToken.AccessToken,
		ExpiresOn: oauthToken.Expiry,
	})

	auth, err := az.NewAzureIdentityAuthenticationProviderWithScopesAndValidHosts(cred, []string{"User.Read.All"}, nil)
	if err != nil {
		return nil, err
	}
```

 it doesn't help me to change the scope to user.Read.All

**Comment by baywet** [comment]
@shachardevops 
Assuming you're building this request (from the other linked issue)

```Go 
	groupsIds, err := graphClient.UsersById(res.Jwt.Oid).MemberOf().Get(ctx, params)
```

User.Read.All is not the right permission. You need one of those:
- delegated User.Read
- delegated GroupMember.Read.All
- delegated Directory.Read.All
- delegated Directory.ReadWrite.All
- app only Directory.Read.All
- app only Directory.ReadWrite.All

**Comment by shachardevops** [comment]
@baywet I was trying to use `User.Read` but still. I am getting "Insufficient privileges to complete the operation."

**Comment by shachardevops** [comment]
in the token, I have `  "scp": "User.Read profile openid email"` @baywet

**Comment by shachardevops** [comment]
If I am giving User.Read.All its working but I am getting a different error 
`"Resource 'memberOf' does not exist or one of its queried reference-property objects are not present."`

**Comment by baywet** [comment]
Looking at [other issues on the matter](https://github.com/microsoftgraph/microsoft-graph-docs/issues/3539) it's likely that the Id you're passing is either:
- not a valid user Id (mal-formatted).
- doesn't exist on that tenant.

Using the users blade in the azure active directory portal, are you able to find this user using the ID you're passing?

**Comment by shachardevops** [comment]
solved the problem. thanks

**Comment by baywet** [comment]
closing since this is solved and the OP is unresponsive.
