### ISSUE TITLE
Sample code to read user's drive gives "Tenant does not have a SPO license"

### ISSUE THREAD

**Issue by dwschulze** [microsoftgraph/msgraph-sdk-go#394]
Sample code to read the user's drive gives this error:

Tenant does not have a SPO license

There are dozens of posts about this error. None of them has a solution, and the discussions don't even make sense.

What is a SPO license and why would I need one to read the drive?

**Comment by baywet** [comment]
SPO stands for SharePoint Online. SharePoint is the service behind the OneDrive offering in Office 365, hence the license requirement.
To make sure the target user:
1. login to the [admin portal](https://admin.microsoft.com)
2. click on users
3. click on active users
4. find the user you're trying to access in the list
5. check the checkbox next to their name
6. click on mange product licenses
7. In the APP section, make sure "SharePoint online" is checked
8. save changes

**Comment by dwschulze** [comment]
Step 1 requires admin permission which I don't have for the account I'm using.  I'll have to see if someone in IT can do these for me.

**Comment by dwschulze** [comment]
I had IT follow the steps you gave above and it did not solve the problem.  I'm still getting

....To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code FHM7P9NRW to authenticate.
Error getting the drive: error status code received from the API
error:%!(EXTRA string=error status code received from the API)code: BadRequestmsg: Tenant does not have a SPO license.

**Comment by baywet** [comment]
Thanks for the additional information. Assuming the target user has a provisioned SharePoint license, it seems that either the authentication is setup incorrectly (wrong permissions/context/tenant/app id) or the wrong account is in use when signing in.

Could you share the client initialization code please?

Could you also verify that you're using the right account that belongs to that tenant when running the code?

**Comment by dwschulze** [comment]
IT followed the steps that you gave above and I still get the same error.

**Comment by baywet** [comment]
Which validates that one account has a SharePoint license provision. Now what we're trying to validate is the same account on the same tenant is in use, which depends on how the authentication is setup in the application and the sign-in steps you go through when running the application. 
If you don't want to share the code, can you at least check that:
- the tenant ID in the code matches the tenant ID in the UI (client registration blade in AAD portal) with your IT department
- the client ID in the code matches the client ID in the UI
- the account you're using to go through the sign-in steps is the same your IT department has provisioned?
