### ISSUE TITLE
Data lost during JSON deserialization

### ISSUE THREAD

**Issue by eric-millin** [microsoftgraph/msgraph-sdk-go#396]
When I serialize an app role assignment and then deserialize it, data is lost. In the repro below, it is `businessPhones` but in my test with against a larger collection, there were other fields that got lost, such as `appRoleAssignments`.

This test fails:

```go
func TestRepro(t *testing.T) {
	blob := `{
		"value": [
			  {
				  "businessPhones": [
					  "950.389.2369"
				  ],
                                  "displayName": "Joe Smith"
			  }
		  ]
	  }`

	jpn, err := kjson.NewJsonParseNode([]byte(blob))
	assert.NoError(t, err)
	v, err := jpn.GetObjectValue(models.CreateAppRoleAssignmentCollectionResponseFromDiscriminatorValue)
	assert.NoError(t, err)

	serialized := v.(*models.AppRoleAssignmentCollectionResponse)
	ser, err := jsonserialization.NewJsonSerializationWriterFactory().GetSerializationWriter("application/json")
	assert.NoError(t, err)
	err = serialized.Serialize(ser)
	assert.NoError(t, err)

	data, err := ser.GetSerializedContent()
	assert.NoError(t, err)
	data = append([]byte("{"), data...)
	data = append(data, byte('}'))

	jpn, err = kjson.NewJsonParseNode(data)
	assert.NoError(t, err)
	v, err = jpn.GetObjectValue(models.CreateAppRoleAssignmentCollectionResponseFromDiscriminatorValue)
	assert.NoError(t, err)

	deserialized := v.(*models.AppRoleAssignmentCollectionResponse)
	assert.Equal(t, serialized, deserialized)
}

```

The test passes if you get rid of the phone number as so:

```go 
func TestRepro(t *testing.T) {
	blob := `{
		"value": [
			  {
				  "businessPhones": [ ],
                                  "displayName": "Joe Smith"
			  }
		  ]
	  }
`
// ...
```

**Expected**
Serializing models to and from JSON should not lose data.

**Actual**
Serializing models to and from JSON loses data.

**Comment by eric-millin** [comment]
Assertion package I used is `github.com/stretchr/testify` if you want to re-run the exact test.

**Comment by eric-millin** [comment]
I just tested deserializing-> serializing application objects and experienced the same thing.

**Comment by eric-millin** [comment]
> For information the fix has just been released. If you could upgrade to github.com/microsoft/kiota-serialization-json-go@v0.8.1 and confirm please?

Thanks for the fast response. Good news: the change fixed `businessPhones`. Bad news: `appRoleAssignments` are still broken:
```json
        {
            "displayName": "Some Dude",
            "appRoleAssignments": [
                {
                    "id": "123"
                }
            ]
        }
```

Also, applications show a similar problem.

```json
        {
            "id": "7f82be47-c406-4c0d-8298-ef4e26a354eb",
            "passwordCredentials": [
                {
                    "endDateTime": "2023-07-11T14:18:14.946Z",
                    "keyId": "f92ec133-34aa-49e9-b078-9f0b247d8059"
                }
            ]
        }
```

`endDateTime` seems to be an issue. 

In both cases, the responses from https://developer.microsoft.com/en-us/graph/graph-explorer?tenant=sample provide good test data.

**Comment by rkodev** [comment]
Hi @eric-millin, We can released version  github.com/microsoft/kiota-serialization-json-go@v0.8.2 which should  resolve this issue
