### ISSUE TITLE
Package Not Found

### ISSUE THREAD

**Issue by gajawadaprashanth** [microsoftgraph/msgraph-sdk-go#397]
Hi,
I was trying to integrate Microsoft Graph API into my go Application. I have followed all the instruction mentioned in this url: https://learn.microsoft.com/en-us/graph/tutorials/go?tabs=aad and I have struck with one package problem which is not implemented it. i got this error: MeMailFoldersItemMessagesRequestBuilderGetRequestConfiguration not declared by packagem, NewMeSendMailPostRequestBody not declared by package models these two errors i got even i declared the package. can you please update this package asap.
Any queries contact me: [gajawadaprashanth@gmail.com](mailto:gajawadaprashanth@gmail.com)

**Comment by rkodev** [comment]
Hi @gajawadaprashanth, Thanks for trying out the Go SDK. Could you kindly share a snippet of the code you have so I can help you debug

**Comment by gajawadaprashanth** [comment]
![Uploading Screenshot 2023-02-20 at 12.57.30 PM.png…]()
<img width="1440" alt="Screenshot 2023-02-20 at 12 57 09 PM" src="https://user-images.githubusercontent.com/118792945/220040871-9c339623-3dee-4e4e-9246-363f073e887f.png">
<img width="1440" alt="Screenshot 2023-01-31 at 2 34 17 PM" src="https://user-images.githubusercontent.com/118792945/220040907-aabc1ee9-2d94-4b7c-8dd8-53f302139d9f.png">

**Comment by gajawadaprashanth** [comment]
![Uploading Screenshot 2023-02-20 at 12.57.09 PM.png…]()
.png…]()
![Uploading Screenshot 2023-02-20 at 12.57.30 PM.png…]()

code:
package graphhelper

import (
	"context"
	"fmt"
	"os"
	"strings"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	auth "github.com/microsoft/kiota-authentication-azure-go"
	msgraphsdk "github.com/microsoftgraph/msgraph-sdk-go"
	"github.com/microsoftgraph/msgraph-sdk-go/me"
	"github.com/microsoftgraph/msgraph-sdk-go/models"
)


type GraphHelper struct {
	deviceCodeCredential *azidentity.DeviceCodeCredential
	userClient           *msgraphsdk.GraphServiceClient
	graphUserScopes      []string
}

func NewGraphHelper() *GraphHelper {
	g := &GraphHelper{}
	return g
}

func (g *GraphHelper) InitializeGraphForUserAuth() error {
	clientId := os.Getenv("CLIENT_ID")
	tenantId := os.Getenv("TENANT_ID")
	scopes := os.Getenv("GRAPH_USER_SCOPES")
	g.graphUserScopes = strings.Split(scopes, ",")

	// Create the device code credential
	credential, err := azidentity.NewDeviceCodeCredential(&azidentity.DeviceCodeCredentialOptions{
		ClientID: clientId,
		TenantID: tenantId,
		UserPrompt: func(ctx context.Context, message azidentity.DeviceCodeMessage) error {
			fmt.Println(message.Message)
			return nil
		},
	})
	if err != nil {
		return err
	}

	g.deviceCodeCredential = credential

	// Create an auth provider using the credential
	authProvider, err := auth.NewAzureIdentityAuthenticationProviderWithScopes(credential, g.graphUserScopes)
	if err != nil {
		return err
	}

	// Create a request adapter using the auth provider
	adapter, err := msgraphsdk.NewGraphRequestAdapter(authProvider)
	if err != nil {
		return err
	}

	// Create a Graph client using request adapter
	client := msgraphsdk.NewGraphServiceClient(adapter)
	g.userClient = client

	return nil
}
func (g *GraphHelper) GetUserToken() (*string, error) {
	token, err := g.deviceCodeCredential.GetToken(context.Background(), policy.TokenRequestOptions{
		Scopes: g.graphUserScopes,
	})
	if err != nil {
		return nil, err
	}

	return &token.Token, nil
}

func (g *GraphHelper) GetUser() (models.Userable, error) {
	query := me.MeRequestBuilderGetQueryParameters{
		// Only request specific properties
		Select: []string{"displayName", "mail", "userPrincipalName"},
	}
	return g.userClient.Me().Get(context.Background(),
		&me.MeRequestBuilderGetRequestConfiguration{
			QueryParameters: &query,
		})
}

func (g *GraphHelper) GetInbox() (models.MessageCollectionResponseable, error) {
	var topValue int32 = 25
	query := me.MeMailFoldersItemMessagesRequestBuilderGetRequestConfiguration{
		// Only request specific properties
		Select: []string{"from", "isRead", "receivedDateTime", "subject"},
		// Get at most 25 results
		Top: &topValue,
		// Sort by received time, newest first
		Orderby: []string{"receivedDateTime DESC"},
	}

	return g.userClient.Me().
		MailFoldersById("inbox").
		Messages().
		Get(context.Background(),
			&me.MeMailFoldersItemMessagesRequestBuilderGetRequestConfiguration{
				QueryParameters: &query,
			})
}

func (g *GraphHelper) SendMail(subject *string, body *string, recipient *string) error {
    // Create a new message
    message := models.NewMessage()
    message.SetSubject(subject)

    messageBody := models.NewItemBody()
    messageBody.SetContent(body)
    contentType := models.TEXT_BODYTYPE
    messageBody.SetContentType(&contentType)
    message.SetBody(messageBody)

    toRecipient := models.NewRecipient()
    emailAddress := models.NewEmailAddress()
    emailAddress.SetAddress(recipient)
    toRecipient.SetEmailAddress(emailAddress)
    message.SetToRecipients([]models.Recipientable{
        toRecipient,
    })

    sendMailBody := models.NewMeSendMailPostRequestBody()
    sendMailBody.SetMessage(message)

    // Send the message
    return g.userClient.Me().SendMail().Post(context.Background(), sendMailBody, nil)
}

func (g *GraphHelper) MakeGraphCall() error {
    // INSERT YOUR CODE HERE
    return nil
}

**Comment by gajawadaprashanth** [comment]
![Uploading Screenshot 2023-02-20 at 12.57.09 PM.png…]()
<img width="1440" alt="Screenshot 2023-02-20 at 12 57 30 PM" src="https://user-images.githubusercontent.com/118792945/220042526-fccd67ea-e0f4-4727-977d-a6234ecba442.png">

**Comment by gajawadaprashanth** [comment]
Hi @rkodev, I have already declared this "github.com/microsoftgraph/msgraph-sdk-go/me"  and if i trying to list down the messages and sending the mail. it showing its not declared by package.
The documentation i followed is: https://learn.microsoft.com/en-us/graph/tutorials/go?tabs=aad
Till Get use step is working fine after that it's showing the above error.

**Comment by rkodev** [comment]
Hi @gajawadaprashanth Thanks for clarifying. Can you try using the function `me.MailFoldersItemMessagesRequestBuilderGetRequestConfiguration`  In such cases, please remove the prefix `me` i.e the letters that match the package name, I've noted the issue in the documentation and will log a ticket to correct this

**Comment by gajawadaprashanth** [comment]
Hi @rkodev, I have remove the prefix me and i got the another issue unknown field Select in struct literal. can tell me what i need to know?
![Uploading Screenshot 2023-02-20 at 2.45.34 PM.png…]()

**Comment by gajawadaprashanth** [comment]
<img width="1440" alt="Screenshot 2023-02-20 at 12 57 09 PM" src="https://user-images.githubusercontent.com/118792945/220065149-76b3ea37-85f8-42b8-b96c-46320aa02474.png">

**Comment by rkodev** [comment]
Hi @gajawadaprashanth , This should be your get inbox function

```go

func (g *GraphHelper) GetInbox() (models.MessageCollectionResponseable, error) {
	var topValue int32 = 25
	query := me.MailFoldersItemMessagesRequestBuilderGetQueryParameters{
		// Only request specific properties
		Select: []string{"from", "isRead", "receivedDateTime", "subject"},
		// Get at most 25 results
		Top: &topValue,
		// Sort by received time, newest first
		Orderby: []string{"receivedDateTime DESC"},
	}

	return g.userClient.Me().
		MailFoldersById("inbox").
		Messages().
		Get(context.Background(),
			&me.MailFoldersItemMessagesRequestBuilderGetRequestConfiguration{
				QueryParameters: &query,
			})
}
```

This should be the send main function, There is a slight change on the request body and the call to post  a request 

```go
func (g *GraphHelper) SendMail(subject *string, body *string, recipient *string) error {
	// Create a new message
	message := models.NewMessage()
	message.SetSubject(subject)

	messageBody := models.NewItemBody()
	messageBody.SetContent(body)
	contentType := models.TEXT_BODYTYPE
	messageBody.SetContentType(&contentType)
	message.SetBody(messageBody)

	toRecipient := models.NewRecipient()
	emailAddress := models.NewEmailAddress()
	emailAddress.SetAddress(recipient)
	toRecipient.SetEmailAddress(emailAddress)
	message.SetToRecipients([]models.Recipientable{
		toRecipient,
	})

	sendMailBody := me.NewMicrosoftGraphSendMailSendMailPostRequestBody()
	sendMailBody.SetMessage(message)

	// Send the message
	return g.userClient.Me().MicrosoftGraphSendMail().Post(context.Background(), sendMailBody, nil)
}

```

**Comment by gajawadaprashanth** [comment]
Yeah, i have changed the getindex() one. but i got this error.

2023/02/20 15:36:51 Error getting user's inbox: content type text/html does not have a factory registered to be parsed
panic: Error getting user's inbox: content type text/html does not have a factory registered to be parsed

goroutine 1 [running]:
log.Panicf({0x1052ec628?, 0x2?}, {0x1400063fde8?, 0x104adaa38?, 0x10616c3c0?})
        /Users/prashanth/.gobrew/current/go/src/log/log.go:395 +0x68
main.listInbox(0x105787de0?)
        /Users/prashanth/Desktop/Microsoft global api/graphtutorial.go:111 +0x60
main.main()
        /Users/prashanth/Desktop/Microsoft global api/graphtutorial.go:55 +0x350
exit status 2

**Comment by rkodev** [comment]
@gajawadaprashanth I'm not sure which function you are referring to as `getIndex`, you only make the changes to `getInbox` and `sendmail` with the changes proposed above, this should be resolve the issues you are having

**Comment by gajawadaprashanth** [comment]
<img width="1440" alt="Screenshot 2023-02-20 at 4 06 56 PM" src="https://user-images.githubusercontent.com/118792945/220082186-10bebe05-faf1-416a-a2d8-0c5bbbb30477.png">
<img width="1440" alt="Screenshot 2023-02-20 at 4 07 32 PM" src="https://user-images.githubusercontent.com/118792945/220082203-ee295341-280d-4cfc-abdf-3ed78389e5e4.png">

@rkodev , I'm calling the getIndex function and trying to list the messages but its throwing me this error.

**Comment by gajawadaprashanth** [comment]
Hi @rkodev,
I have solved the issue now i'm able to get messages. i have one query whenever i run my code its asking me for authentication
like: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code HUY9HLKL4 to authenticate.

the above one is displaying, so can i remove this authentication and once i run my code its needs to authenticate automatically, shows the mails.

**Comment by gajawadaprashanth** [comment]
@rkodev, I have tried every possibility to remove the authentication but its still asking me for user authentication. if possible can we have 15 minutes call now?

**Comment by baywet** [comment]
@gajawadaprashanth We're not staffed to handle calls with customers, if you want to get a call support, you should open a [support case](https://developer.microsoft.com/en-us/graph/support).

Microsoft Graph APIs are always behind authorization (which requires authentication) to make sure customers data remains secured.
The only way to avoid any kind of prompt to the end user would be to use an app only flow like client credentials (with secret or certificate). (Ronald already share some pointers about that in his previous reply)
