### ISSUE TITLE
Serialization of responses of content type `text/html` is not supported

### ISSUE THREAD

**Issue by rkodev** [microsoftgraph/msgraph-sdk-go#398]
Serialization of responses for content type `text/html ` is currently not supported by the SDK.

**Comment by baywet** [comment]
Hey @rkodev 
Can you provide more context on why you believe this should be supported?
HTML is "not structured" (at least not in an OOP/data sense), so why should we support its serialization/deserialization?
The expected behaviour right now is that we'll be using streams (byte arrays in Go) so the client app has full control over the payload.

**Comment by baywet** [comment]
Thanks for the additional information [according to the docs](https://learn.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=http#example-4-send-a-new-message-using-mime-format) the only two response formats that are supported are application/json and text/plain (base64 encoded mime email format). I'm not sure how the client got and HTML response? Maybe a badly handled error on the service side?
Anyway, unless we can repro it with a certain level of confidence, I'd rule that an edge case and close this issue. What do you think?

**Comment by rkodev** [comment]
I agree, we can keep the ticket in the backlog and investigate if it happens again since it does look like an error.

**Comment by dravenk** [comment]
I try to send a PDF file to email using GraphAPI but fail. I found the issue and related documentation.
https://learn.microsoft.com/en-us/graph/api/resources/fileattachment?view=graph-rest-1.0

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/14295318/233823934-061d5be7-23a0-4a37-91fc-fc586fd371c4.png">
