### ISSUE TITLE
Sense of SDK stability

### ISSUE THREAD

**Issue by austingebauer** [microsoftgraph/msgraph-sdk-go#403]
Hello 👋  

HashiCorp Vault uses the Microsoft Graph API in both our Azure [Secrets Engine](https://developer.hashicorp.com/vault/docs/secrets/azure) and [Auth Method](https://developer.hashicorp.com/vault/docs/auth/azure). Currently, we're relying on [go-autorest](https://github.com/Azure/go-autorest) to interact with the APIs. With the go-autorest modules going out of support soon, we're looking to make the transition to using this SDK as a replacement.

I saw this disclaimer in the readme:

> Note: the Microsoft Graph Go SDK is currently in Community Preview. During this period we're expecting breaking changes to happen to the SDK based on community's feedback. Checkout the [known limitations](https://github.com/microsoftgraph/msgraph-sdk-go-core/issues/1).

Can you give us a sense for the stability of this SDK? Is it ready to be used in production-level applications? If not, do you have a sense for how far out that will be? I realize these questions can be difficult to answer and depend on a variety of factors. I appreciate any light you can shed on this.

Thank you!

**Comment by baywet** [comment]
Hi @austingebauer 
Thanks for considering switching over.
While I can't provide numbers about requests/production applications using the SDK publicly, we'll be happy to provide that additional context upon request privately assuming you're under NDA and part of the TAP program (which I believe you are, but if you're not, reach out, I'll forward things to our CPX team).

As per the reliability aspect, we're putting the final touches on the performance and reliability aspects to get to GA. While we expect some breaking changes to happen until we get there, we're trying to keep them to a minimum at this point and documenting them in the changelog when that happens so application developers can get a better sense of the upgrade code.

On the timelines front, we're trying to get to a release candidate state in the next few weeks and a GA in the next few months.

Lastly, this SDK is generated using [Microsoft Kiota](https://github.com/microsoft/kiota) which you might want to checkout as an alternative so build your own client with only a subset of the API while getting the same development experience.

I hope that gives you additional context, let us know if you need further information.

**Comment by austingebauer** [comment]
My apologies for the late reply here, @baywet! I really appreciate the detailed response. I see that you all made the RC announcement (congrats!). Our team is starting to look at making this transition within the next ~1-2 months.
