### ISSUE TITLE
Client retries

### ISSUE THREAD

**Issue by eric-millin** [microsoftgraph/msgraph-sdk-go#409]
Does the client have retry logic built-in for cases such as 429s?

**Comment by baywet** [comment]
Correct, that's one of the many things you get for free by using the SDK
https://github.com/Microsoft/kiota-http-go/blob/main/retry_handler.go#L19

**Comment by eric-millin** [comment]
> Correct, that's one of the many things you get for free by using the SDK https://github.com/Microsoft/kiota-http-go/blob/main/retry_handler.go#L19

sweeeet 😎
