### ISSUE TITLE
`HTTP/1.x transport connection broken: malformed HTTP response`

### ISSUE THREAD

**Issue by AlessioC31** [microsoftgraph/msgraph-sdk-go#417]
Hello, 

Since a couple of days, when I execute something like `err := client.UsersById(user).EventsById(eventID).Delete(context.Background(), nil)` it happens that I receive an error with `HTTP/1.x transport connection broken: malformed HTTP response`.
When this does not happen and `err == nil`, I still get `Unsolicited response received on idle HTTP channel starting with "0\r\n\r\n"; err=<nil>` in stdout and the event is deleted.

Am I doing something wrong or is something happening with MSGraph API? The error started appearing randomly, I haven't redeployed my application

**Comment by dumim** [comment]
We are making the same calls directly to the API using a http.Client and we are getting the same error:

```
Delete "https://graph.microsoft.com/v1.0/me/events/XXXXX?%24select=Id%2CSubject%2CBody%2CStart%2CEnd%2CIsAllDay%2CLocation%2CReminderMinutesBeforeStart": net/http: HTTP/1.x transport connection broken: malformed HTTP response "0"
```
Has the API changed?

**Comment by rkodev** [comment]
Hi @dumim , @AlessioC31 , thanks for the extra information.

This issue looks like it's from the service and not an issue with the SDK itself. This repo is however dedicated to the SDK and not issues with the services.
In such a case, the best thing to do is to post a question to [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) forums where members of the service teams are providing answers.

**Comment by meain** [comment]
@AlessioC31 Did you happen to file a ticket on the forum? Could you share a link to the discussion in case you did?

**Comment by gmatev** [comment]
@rkodev @baywet  here is a very similar report from the Q&A forums - https://learn.microsoft.com/en-us/answers/questions/1184068/has-the-email-delete-message-endpoint-started-to-r

This implies that there is indeed a server issue that can break HTTP clients that make assumptions about what is returned with a 204. 

While this is a server issue, it is creating real problems for us as users of the SDK as calls using the same client after a delete fail. 

Is there anything that can be done in terms of defensive coding in the SDK to alleviate this issue? Alternatively do you have a suggestion how to work around it in the SDK.

**Comment by rkodev** [comment]
Hi @gmatev Were you able to find a work around for this problem. If not, I would suggest recreating the client when such an error occurs while the service team is still working on that [issue](https://learn.microsoft.com/en-us/answers/questions/1184068/has-the-email-delete-message-endpoint-started-to-r). And if this is an idempotence endpoint , i.e `DELETE` , `GET` , `PUT` you can retry the endpoint.
