### ISSUE TITLE
Is there anyway to see the full request and response URL and body?

### ISSUE THREAD

**Issue by 99-lives** [microsoftgraph/msgraph-sdk-go#425]
Hi team,

For the purposes of debugging and logging, is there anyway to see the full request URL and body that the SDK generates, and the full response body, after making a request?

This would really help to identify if there is missing parameters in my request, and will make it easy to see why my program crashes when I use a Get* method on the result for a field that was not provided in the response.

This would help immensely with debugging my project, and would be valuable for logging once it goes to production.

Cheers.

**Comment by rkodev** [comment]
Hi @99-lives , this can be achieved by logging all the request that are sent via `http.Client`, you can use a number of different methods available such as tracing using `https://go.dev/blog/http-tracing` or a number of libraries out there that are present to log the http request.

1. You will need to provide an implementation of the `http.Client` that has logging 
2. Provide this to the request adapter i.e 

For example using the http.Client to implement [this](https://go.dev/blog/http-tracing) tracing

```go
         t := &transport{}

        trace := &httptrace.ClientTrace{
            GotConn: t.GotConn,
        }

	httpClient := &http.Client{
		Transport: t,
	}
	adapter, err := msgraphsdk.NewGraphRequestAdapterWithParseNodeFactoryAndSerializationWriterFactoryAndHttpClient(auth, nil, nil, httpClient)

// get the client 
client := msgraphsdk.NewGraphServiceClient(adapter)

```

**Comment by rkodev** [comment]
A simple alternative, you can use a log library to simply provide a traced transport object

**Comment by 99-lives** [comment]
Awesome, thanks for the help @rkodev.
