### ISSUE TITLE
page iterator: reflect: call of reflect.Value.IsNil on zero Value

### ISSUE THREAD

**Issue by stephenwan-opal** [microsoftgraph/msgraph-sdk-go#433]
Hello, I started seeing this error starting 2 days ago:

```go
panic: goroutine 500907 [running]:
panic({0x2f8ccc0, 0xc01dd3a0d8})
	/usr/local/go/src/runtime/panic.go:884 +0x212
reflect.Value.IsNil(...)
	/usr/local/go/src/reflect/value.go:1554
github.com/microsoftgraph/msgraph-sdk-go-core.convertToPage({0x37b7280, 0xc00fd4ba80})
	/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go-core@v0.31.0/page_iterator.go:205 +0x51b
github.com/microsoftgraph/msgraph-sdk-go-core.(*PageIterator).next(0xc00e8ee120?, {0x3ea9fd0?, 0xc00d369140?})
	/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go-core@v0.31.0/page_iterator.go:126 +0x4e
github.com/microsoftgraph/msgraph-sdk-go-core.(*PageIterator).Iterate(0xc00e8ee120, {0x3ea9fd0, 0xc00d369140}, 0xc00d270500?)
	/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go-core@v0.31.0/page_iterator.go:92 +0x5e
	<...snip...>
: reflect: call of reflect.Value.IsNil on zero Value
```

This looks similar to #249 and https://github.com/microsoftgraph/msgraph-sdk-go/issues/224 but it is a different line of code panicking.

code looks like this:
```go
iter, err := msgraphcore.NewPageIterator(
	users,
	s.client.GetAdapter(),
	models.CreateUserFromDiscriminatorValue,
)
if err != nil {
	return nil, azuread.WrapErr(err)
}
if err := iter.Iterate(ctx, func(item interface{}) bool {
	// ...
}
```

panicking code:
```go
value := ref.FieldByName("value")
if value.IsNil() { // this line
	return page, errors.New("value property missing in response object")
}
```

which is different from the issue addressed by https://github.com/microsoftgraph/msgraph-sdk-go-core/pull/105/files.

**Comment by rkodev** [comment]
@stephenwan-opal could you kindly confirm if you are using `v0.34.1` for package github.com/microsoftgraph/msgraph-sdk-go-core`, if not , could you upgrade and confirm if the error is still present?

**Comment by stephenwan-opal** [comment]
we are using 0.31.0. I will upgrade and take a look, thanks.

Did the API response change? Why would this issue start happening 3 days ago?

**Comment by rkodev** [comment]
@stephenwan-opal There isn't a change in the API response, this was a required change in the supporting library and was implement in [core](https://github.com/microsoftgraph/msgraph-sdk-go-core/pull/167)

**Comment by rkodev** [comment]
You can also upgrade to SDK `v0.57.0`

**Comment by stephenwan-opal** [comment]
Hi @rkodev, thanks - I guess I am confused on: why did I start seeing this issue 4 days ago, the same say https://github.com/microsoftgraph/msgraph-sdk-go-core/pull/167 was put out? (is that coincidence? i.e. latent bug happens to show up on the same day?)

Doing this upgrade is unfortunately not straightforward for me. I tried to upgrade just the `msgraph-sdk-go-core` package but there are breaking changes up and downstream that require a bunch of things to be upgraded together. Because https://github.com/microsoftgraph/msgraph-sdk-go/issues/129 is still an issue for me, the base `msgraph-beta-sdk-go` package is unusable for me, so I am doing this [nasty hack](https://github.com/stephenwan-opal/msgraph-beta-sdk-go/commit/bd1251194c638fe121457a03282d9f56d7274cfd) to keep build times reasonable.

**Comment by baywet** [comment]
> so I am doing this [nasty hack](https://github.com/stephenwan-opal/msgraph-beta-sdk-go/commit/bd1251194c638fe121457a03282d9f56d7274cfd) to keep build times reasonable.

@stephenwan-opal the only part "nasty" about that solution is the fact that you're generating off a fork of this repo. You could perfectly generate your own client with only the API surface you care about in your project. In fact now that the tech to do so is mostly ready, we're working on lighting up experiences to make this easier to anybody who has stronger size/performance requirements than what the full SDK offers can use that option instead.

**Comment by stephenwan-opal** [comment]
sorry - I'd like to de-emphasize the specific change linked there. I'm excited to hear that the self-generated kiota build should help; at the time it was tricky to figure out and the kiota generation did not work out of the box (i.e. missing `graph_service_client.go` and some other files).

coming back to the issue at hand, do you have a sense when this issue gets triggered? is there a specific api response that doesn't return the `value` field?

**Comment by rkodev** [comment]
@stephenwan-opal /Perhaps a little context to help. This issue was brought about as a result of implementing the backing store. Values were no longer stored on the structs properties but were read from the backing store. The fix was to invoke the `GetValue` method via  reflection as opposed to reading the `value` property.  If it helps this the specific change that was done https://github.com/microsoftgraph/msgraph-sdk-go-core/pull/167
