### ISSUE TITLE
Getting error `accessDenied` for api `UsersById(...).Authentication().Methods().Get(...)`

### ISSUE THREAD

**Issue by karanpopat** [microsoftgraph/msgraph-sdk-go#441]
While querying the API `UsersById(...).Authentication().Methods().Get(...)`
I am getting this error `{"Code":"accessDenied","Message":"Request Authorization failed"}`

My user has the roles:

- Authentication Administrator
- Authentication Policy Administrator

```go
az "github.com/microsoft/kiota-authentication-azure-go"

func getUserAuthenticationMethods() (interface{}, error) {
	ctx := context.Background()

	auth, err := az.NewAzureIdentityAuthenticationProvider(cred)
	if err != nil {
		return nil, nil, fmt.Errorf("error creating authentication provider: %v", err)
	}

	adapter, err := msgraphsdkgo.NewGraphRequestAdapter(auth)
	if err != nil {
		return nil, nil, fmt.Errorf("error creating graph adapter: %v", err)
	}
	client := msgraphsdkgo.NewGraphServiceClient(adapter)

	params := methods.MethodsRequestBuilderGetRequestConfiguration{}

	auth, err := client.UsersById(<user-id>).Authentication().Methods().Get(ctx, &params)
	if err != nil {
		return nil, err
	}

	return auth, nil
}
```

I get a proper response on querying `https://graph.microsoft.com/v1.0/users/<user-id>/authentication/methods` using graph explorer. But error while using the SDK

**Comment by rkodev** [comment]
Hi @karanpopat, as stated on the previous comment by @ddyett , The issue looks to be an issue with the provided scopes. You will need to provide the correct scopes for this request, for you this will be `UserAuthenticationMethod.Read`. An easy way to identoify the scopes that are used in graph explorer is to check the `Modify permissions` tab and this should list the scopes graph explorer is using to serve the request .

![image](https://user-images.githubusercontent.com/43806892/231121729-ea80cfa3-ee09-4b54-94dc-4203ba3b086b.png)

**Comment by karanpopat** [comment]
Thanks, @rkodev @ddyett for the recommendation. I'll try this API again with the correct permission and get back if I find any problems.

**Comment by rkodev** [comment]
Hi @karanpopat, was your issue resolved?
