### ISSUE TITLE
[Question] how do i get the *Sensitivity Value from an Event?

### ISSUE THREAD

**Issue by hofq** [microsoftgraph/msgraph-sdk-go#444]
Hi,
first as a disclaimer - i am fairly new to Go.

```go
	for _, event := range result.GetValue() {
		fmt.Printf("Sensitivity: %v\n", *event.m.GetSensitivity())
                fmt.Printf("Sensitivity: %v\n", *event.m.GetSensitivity().String())
		reservations = append(reservations,
			Reservation{
				StartDateTime: c.ConvertTime(*event.GetStart().GetDateTime()),
				EndDateTime:   c.ConvertTime(*event.GetEnd().GetDateTime()),
				TopicSubject:  *event.GetSubject(),
				ReservedBy:    *event.GetOrganizer().GetEmailAddress().GetName(),
			},
		)
		i++

	}
```
My Test Statements both fail, because the Type Returned by the Function is *Sensitivity and not *string or *int. if i remove the pointer, i'll just get the value nil without any error.

the error i am reciving is:
```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x85e32e]
```

Is there something i have missed? How can i get the Value from *Sensitivity to a normal, "usable" value?

**Comment by hofq** [comment]
Okay, so that's also what i thought. But i don't get how the sensitivity Value can be nil as it should (in my understanding) default to normal. 

In Outlook i have the Option to Mark an Appointment as Private and in my Testing even these showed up as nil. I want to filter these as Private Marked Appointments.

Have i missed another parameter or am i thinking wrong about this?

Thanks for your time Roland (@rkodev )

**Comment by rkodev** [comment]
@hofq please share the SDK executed statement that returns the given result

**Comment by hofq** [comment]
I fixed it now,
in this Branch i had not Added the sensitivity to my Filter Criteria, now it is added:
```go
query := cv.CalendarViewRequestBuilderGetQueryParameters{
  Select: []string{
	  "subject",
	  "start",
	  "end",
	  "organizer",
	  "sensitivity",
  }
}
```
Thanks @rkodev and sorry for the Time Waste :/
