### ISSUE TITLE
Endpoint /education/me/assignments is not in the SDK

### ISSUE THREAD

**Issue by calebkiage** [microsoftgraph/msgraph-sdk-go#453]
The endpoint aliases for `**/me/**` are ignored in generated code. endpoints under `/me/**` are aliased and handled by a middleware but the `/education/me/**` endpoints aren't.

**Comment by rkodev** [comment]
Resolved by https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/990
