### ISSUE TITLE
client.Users().Count().Get() fails with "text does not support current method"

### ISSUE THREAD

**Issue by r0nli** [microsoftgraph/msgraph-sdk-go#466]
Hi,

After updating my project from using SDK version v0.53.0 to v0.61.0. I can no longer get the user count using the following code:

```
import "github.com/microsoftgraph/msgraph-sdk-go/users"

opts := &users.CountRequestBuilderGetRequestConfiguration{Headers: abstractions.NewRequestHeaders()}
opts.Headers.Add("consistencylevel", "eventual")

userCount, err := client.Users().Count().Get(ctx, opts)
if err != nil {
    panic(err)
}
```

Would you kindly fix this issue?

**Comment by rkodev** [comment]
Hi @r0nli, Thanks for reporting this issue, it does appear we had an issue serializing primitive types in one of the support libraries. Please upgrade the library `kiota-serialization-text-go` to v0.7.1 using this command 
`go get github.com/microsoft/kiota-serialization-text-go@0.7.1` and test again
