### ISSUE TITLE
Add a global logging framework

### ISSUE THREAD

**Issue by rkodev** [microsoftgraph/msgraph-sdk-go#467]
Add a global logging framework that should allow running the sdk in different logging modes.  This should improve developers experience when debugging issues

**Comment by baywet** [comment]
Before we dive into that, have you tried setting up Open Telemetry? What information was missing?
This aspect is missing in our documentation, I just added an issue.
https://github.com/MicrosoftDocs/openapi-docs-pr/issues/21
