### ISSUE TITLE
Issue with values field for xlsx file using golang SDK

### ISSUE THREAD

**Issue by archit-bedrock** [microsoftgraph/msgraph-sdk-go#473]
Hi,

I'm trying to get values from an xlsx file using the golang SDK. This is how I'm constructing the builder - 

```
r := "A1:M1"
ptrRange := &r
p.graph.Drives().ByDriveId(driveID).Items().ByDriveItemId(itemID).Workbook().Worksheets().ByWorkbookWorksheetId("Sheet1").RangeWithAddress(ptrRange)
```

and this is how I'm trying to get the `values` field. 

```
res, err := e.builder.Get(ctx, e.options)
if err != nil {
    return nil, util.Error(err)
}
w := jsonserialization.NewJsonSerializationWriter()
fmt.Println("cell count: ", *res.GetCellCount())
fmt.Println("column hidden: ", *res.GetColumnHidden())
err = res.GetValues().Serialize(w)
if err != nil {
return nil, err
}
elem, err := w.GetSerializedContent()
if err != nil {
return nil, err

// This always returns [], even though on the graph explorer UI there are entries for values
fmt.Println(elem)
}
```

I tried this on the graph explorer UI and the `values` field is correctly populated for the xlsx file.

The cell count and column hidden field show up using the SDK, but the values field always returns an empty result. Is there something I need to do differently to get the values field? 

Thanks so much!

**Comment by archit-bedrock** [comment]
To simplify this - would it be possible to know if there is another method of serialization needed to get the results stored in `values` from the response result? I tried using the default json.Marshal approach as well which also gave an empty result.

**Comment by archit-bedrock** [comment]
Any follow up on this? Just wanted to see if this issue can be resolved

**Comment by rkodev** [comment]
Hi @archit-bedrock, Thanks for highlighting this issue.  The reason you are unable to access the data from the result object stems from an issue with how [kiota](https://github.com/microsoft/kiota), an automated code generator responsible for generating this sdk,  interprets what should be "generic Json objects" as an [actual struct](https://github.com/microsoftgraph/msgraph-sdk-go/blob/main/models/json.go) and generates the code for it. There is an  [issue ](https://github.com/microsoft/kiota/issues/2319) in code generator and once resolved the values should give you access

**Comment by archit-bedrock** [comment]
Thanks @rkodev for the response! Is there a timeline I can expect to have this issue resolved. Thanks again

**Comment by archit-bedrock** [comment]
@rkodev Just wanted to follow up. Is there an estimate on when I can expect this issue to get resolved?

**Comment by rkodev** [comment]
Hi @archit-bedrock , thanks for the patience. We have some tests in progress to enable access of this data as the changes are being worked out in the code generator

**Comment by bssughosh** [comment]
I still am facing this issue. I am getting empty values in the go sdk but when I make an API call, I cam able to see the values
