### ISSUE TITLE
How to deserialize change notifications

### ISSUE THREAD

**Issue by eric-millin** [microsoftgraph/msgraph-sdk-go#481]
We were using `ChangeNotificationCollectionResponse` to deserialize change notifications. However, that type is no longer available in the latest release. What should we use instead?

**Comment by baywet** [comment]
Hi @eric-millin 
Sorry for pulling the rug from under your feet. Our plan is to have them as part of the core package instead. But our sequencing was out of order.
If you'd like to fast track things, please go ahead and submit a PR in core by just moving the [models from the previous version](https://github.com/microsoftgraph/msgraph-sdk-go/blob/v0.63.0/models/change_notification.go) there.

**Comment by eric-millin** [comment]
Ok, thanks for the explanation. If we can't wait, I'll create the PR.

**Comment by baywet** [comment]
let's keep the issue open, at least as an indication for us that works need to be done in that space.

**Comment by eric-millin** [comment]
@baywet What's the timeline for addressing this issue.

**Comment by eric-millin** [comment]
@andrueastman Do you know the timeline for addressing this issue?
