### ISSUE TITLE
400 when getting file content

### ISSUE THREAD

**Issue by eric-millin** [microsoftgraph/msgraph-sdk-go#485]
I'm trying to get the contents of a drive item. When I use the SDK client to make the call, I get a 400. However, when I curl the same URL, it works. That makes me believe it might be an SDK issue rather than and API issue.

I am using v0.60.0 (I cannot upgrade because of https://github.com/microsoftgraph/msgraph-sdk-go/issues/481).

### Details

Here's roughly what happens:
1. Client calls `https://graph.microsoft.com/v1.0/drives/<drive-id>/items/<item-id>/content`.
   ```go
   graphClient.DrivesById(driveId).ItemsById(itemId).Content().Get(ctx, nil)
   ```
3. API returns `302` to `https://mytech.sharepoint.com/_layouts/15/download.aspx?UniqueId=ugly-gu-id&Translate=false&tempauth=some.jwt.token&ApiVersion=2.0`
4. After client redirects, the API returns `400` with the message
   > \<h2>Our services aren't available right now\</h2>\<p>We're working to restore all services as soon as possible. Please check back soon.\</p>0123

However, If I curl the redirect URL, e.g. 
   ```shell
   curl "https://mytech.sharepoint.com/_layouts/15/download.aspx?UniqueId=ugly-gu-id&Translate=false&tempauth=some.jwt.token&ApiVersion=2.0" > my.docx
   ```
the API returns a valid file.

**Comment by eric-millin** [comment]
Confirmed that Go's default HTTP client also works successfully.

**Comment by eric-millin** [comment]
@rkodev @baywet Can someone take a look at this? Thanks

**Comment by maxklav** [comment]
We also are currently using the Go's default HTTP client for this specific call

**Comment by eric-millin** [comment]
@baywet @rkodev Any chance you can take a look at this? We're using an ugly hack (wait for the 400 and then use the URL to make another request with default client) to work around this. We're still in the prototype phase, so we can deal for the very short-term, but obviously won't work for production. Thanks.

**Comment by eric-millin** [comment]
@baywet @rkodev Can someone look at this, please?

**Comment by rkodev** [comment]
Hi @eric-millin this issue is currently in progress. , Please close [this ] related issue (https://github.com/microsoft/kiota-http-go/issues/97)issue and keep the conversation here.
