### ISSUE TITLE
Api not listing the `Conditional Access Policy` when `Grant Access` is set to `Phishing-resistant MFA`

### ISSUE THREAD

**Issue by Priyanka-Chatterjee-2000** [microsoftgraph/msgraph-sdk-go#488]
On following the steps:

- Creating a `Conditional Access Policy` 
- Setting `Cloud apps or actions` to `All cloud apps`
- Setting `Users and groups` to `All users`
- Setting `Grant Access` to `Require authentication strength: Phishing- resistant MFA` 
- Then setting `Enable policy` to `Report-only`  
Tried using the go-sdk as well:

```go
	options := &policies.PoliciesRequestBuilderGetRequestConfiguration{
		QueryParameters: input,
	}

	result, err := client.Identity().ConditionalAccess().Policies().Get(ctx, options)
```
but wasn't fruitful as this particular policy was not getting listed
Then, tried to call https://graph.microsoft.com/v1.0/policies/conditionalAccessPolicies  but was getting the same result.

**Comment by rkodev** [comment]
Hi @Priyanka-Chatterjee-2000 are you able to share the error details / message you get when you followed this steps?
