### ISSUE TITLE
help please. Groups().ByGroupId(groupId).Members().Get() how to retrieve member id

### ISSUE THREAD

**Issue by zoezhangmattr** [microsoftgraph/msgraph-sdk-go#489]
hi there, i am trying to retrieve the email from group members func
result, err := client.Groups().ByGroupId(groupId).Members().Get(x,y)
for _, j := range result.GetValue() {
		//can get member id, j.GetId()
	}

could you guide me how to get the email for each member please, thank you so much

**Comment by rkodev** [comment]
Hi @zoezhangmattr , thanks for trying the Go SDK. You can access the mail object using this statement.

```go
	result, _ := client.Groups().ByGroupId("groupId").Members().Get(context.Background(), nil)
	for _, item := range result.GetValue() {
		user := item.(models.Userable)

		fmt.Printf("User mail is : %v\n", user.GetMail())
	}

```
