### ISSUE TITLE
POST to create SharePoint lists return `General exception while processing`

### ISSUE THREAD

**Issue by meain** [microsoftgraph/msgraph-sdk-go#490]
When trying to create a SharePoint list with the latest version, it errors out with the mentioned error. Here is a minimal reproducable example. In the following example if I uncomment the line with `SetValidation`, the request fails. I could pass in `models.NewColumnValidation()` instead of `nil`, but was wondering why this would cause an issue.

This is happening when using version `1.0.0` or `1.1.0`. It works in `0.33.0`

```go
package main

import (
	"context"
	"fmt"
	"log"

	msgraphsdk "github.com/microsoftgraph/msgraph-sdk-go"
	"github.com/microsoftgraph/msgraph-sdk-go/models"
)

const (
	tenentID     = "1"
	clientID     = "2"
	clientSecret = "3"
	siteID       = "4"
)

func main() {
	adapter, err := createAdapter(tenentID, clientID, clientSecret)
	if err != nil {
		log.Fatal("Could not create a adapter:", err)
	}

	client := msgraphsdk.NewGraphServiceClient(adapter)

	name := "<name>"
	newList := models.NewList()
	newList.SetDisplayName(&name)
	column := models.NewColumnDefinition()
	column.SetName(&name)
	column.SetText(models.NewTextColumn())
	// column.SetValidation(nil) // <-- uncomment this line to get the error
	newList.SetColumns([]models.ColumnDefinitionable{column})

	_, err = client.Sites().BySiteId(siteID).Lists().Post(context.Background(), newList, nil)
	if err != nil {
		log.Fatal("Could not create list:", err)
	} else {
		fmt.Println("List created")
	}
}
```

Here is the full error:
``` json
{
  "error": {
    "code": "generalException",
    "message": "General exception while processing",
    "innerError": {
      "date": "2023-05-12T13:30:18",
      "request-id": "d...2484",
      "client-request-id": "db901...62484"
    }
  }
}
```

**Comment by rkodev** [comment]
Hi @meain 

This is a service layer issue and not a Graph Go SDK issue. Setting the validation values to nil sends a null value to the sharepoint service. The error message you receive is  as a response of explicitly setting the validation value to a "null" and getting a response from the service and not the SDK.

This repo is dedicated to the Graph go SDK and not the service. If you would like to understand more about this issue please file a response in [the dedicated Microsoft Q&A](https://learn.microsoft.com/en-us/answers/tags/161/ms-graph)
