### ISSUE TITLE
azidentity.NewAuthorizationCodeCredential does not exist

### ISSUE THREAD

**Issue by mebert1** [microsoftgraph/msgraph-sdk-go#501]
The authorization code credential dependency mentioned in the [Authorization code provider documentation](https://learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?view=graph-rest-1.0&tabs=Go#authorization-code-provider) does not exist.

```
import (
    "context"
    azidentity "github.com/Azure/azure-sdk-for-go/sdk/azidentity"
    msgraphsdk "github.com/microsoftgraph/msgraph-sdk-go"
)

cred, err := azidentity.NewAuthorizationCodeCredential(
    "TENANT_ID",
    "CLIENT_ID",
    "AUTH_CODE",
    "REDIRECT_URL",
    &azidentity.AuthorizationCodeCredentialOptions {
        ClientSecret: "CLIENT_SECRET",
    },
)

client := msgraphsdk.NewGraphServiceClientWithCredentials(cred, []string{"User.Read"})

result, err := client.Me().Get(nil)
```

My workaround to create a client with an Azure access token was this:

```
token := oauth2.Token{
	AccessToken: "access token",
	TokenType:    "Bearer",
}

cred := azureTokenCredential{token: token}

auth, err := authentication.NewAzureIdentityAuthenticationProviderWithScopes(cred, s.scopes)
if err != nil {
	return nil, errors.Wrap(err, "AzureAuthenticationProvider")
}

adapter, err := msgraph.NewGraphRequestAdapter(auth)

client := msgraph.NewGraphServiceClient(adapter)
```

The alternative approach works fine but I think the above-linked piece of documentation should be updated to avoid the headache for other developers in the future.

**Comment by rkodev** [comment]
Hi @mebert1. Thanks for pointing this out in the documentation. A ticket has been raised to correct the documentation.
In the meantime you can use this sample code to get the access token.

```go

	cred, err := azidentity.NewClientSecretCredential(
		"TENANT_ID",
		"CLIENT_ID",
		"CLIENT_SECRET",
		&azidentity.ClientSecretCredentialOptions{},
	)

	client := msgraphsdk.NewGraphServiceClientWithCredentials(cred, []string{"User.Read"})

```

**Comment by mebert1** [comment]
There was no problem with obtaining the access token, but rather with using said token to authenticate the user from a different platform.

Example system:
1. A mobile system obtains the auth code and uses it to retrieve an access token and refresh token.
2. The token is sent to a backend system
3. The backend system uses the token to authenticate and retrieve User information (such as messages)

If the documentation on creating the client on the backend is updated accordingly, this issue can be closed.

**Comment by rkodev** [comment]
Hi @mebert1, the documentation has been updated to reflect that this authorization flow is not supported in the Go SDK. 

As an alternative, there are a number of different authentication flows that are supported in the SDK From the system you have described above I'd recommend you use the application [secret flow](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-authentication-flows#authorization-code) describe above or [on-behalf-on flow](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-authentication-flows#on-behalf-of-obo) which would enable your api to acquire a token on behalf of the user and access graph.

For more documentation on on-behalf-off use [azidentity.NewOnBehalfOfCredentialWithSecret](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/on_behalf_of_credential.go),  an example of this implementation would be [here](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/on_behalf_of_credential_test.go).
