### ISSUE TITLE
Post attachment panics in case of nested attachment

### ISSUE THREAD

**Issue by neha-Gupta1** [microsoftgraph/msgraph-sdk-go#506]
In case of nested Item attachment the SDK panics with error -  
`panic recovery: file /tmp/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v1.4.0/models/message.go - line 729: interface conversion: interface is nil, not serialization.Parsable`

Scenario- 
attach email (with an item attachment) as item attachment to an email using `POST attachment`. 
 Current output -  
The code panics with above mentioned error.

Log snippet:
"panic recovery: file /tmp/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v1.4.0/models/message.go - line 729: interface conversion: interface is nil, not serialization.Parsable",
 "errorVerbose": "interface conversion: interface is nil, not serialization.Parsable\npanic recovery: file /tmp/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v1.4.0/models/message.go

**Comment by baywet** [comment]
Related https://github.com/microsoft/kiota-serialization-json-go/issues/91
