### ISSUE TITLE
build constraints exclude all Go files in

### ISSUE THREAD

**Issue by LiWenZi** [microsoftgraph/msgraph-sdk-go#515]
github.com/Azure/azure-sdk-for-go/sdk/azidentity: build constraints exclude all Go files in E:\goworkstation\pkg\mod\github.com\!azure\azure-sdk-fo
r-go\sdk\azidentity@v1.3.0
My project uses go version 1.16?
Isn't this version applicable?

**Comment by baywet** [comment]
Hi,
This repository is for the Microsoft Graph SDK.
The repository for Azure SDK is this one https://github.com/azure/azure-sdk-for-go
Closing.
