### ISSUE TITLE
Extra comma(,) in payload of exchanges' mail with nested attachments 

### ISSUE THREAD

**Issue by neha-Gupta1** [microsoftgraph/msgraph-sdk-go#518]
With the latest release, an extra comma(,) get inserted in the payload for POST attachment API with nested attachment. Code to reproduce-

[Payload](https://gist.github.com/neha-Gupta1/1147b089a058bb12bcb20eff5cd1b5e7) goes as 'template' in the code.

```
package main

import (
	"fmt"
	kjson "github.com/microsoft/kiota-serialization-json-go"
	"github.com/microsoftgraph/msgraph-sdk-go/models"
)

func sendMailWithAttachment() {
	message := fmt.Sprintf(
		template,
		"subject",
		"A Stranger",
		"foobar@8qzvrj.onmicrosoft.com",
		"foobar@8qzvrj.onmicrosoft.com",
		"LidiaH@8qzvrj.onmicrosoft.com",
	)

	messageByte := []byte(message)

	parseNode, err := kjson.NewJsonParseNodeFactory().GetRootParseNode("application/json", messageByte)
	if err != nil {
		return
	}

	v, err := parseNode.GetObjectValue(models.CreateMessageFromDiscriminatorValue)
	if err != nil {
		return
	}
	msg := v.(models.Messageable)
	attachments := msg.GetAttachments()

	//code to post email using POST API
	//....
	// code to post email using POST API completed successfully

	transform := attachments[0].(models.ItemAttachmentable)
	item := transform.GetItem()
	message := item.(models.Messageable)

	getAttachment(message)

	transform.SetItem(newMessage)

	// *msgraphsdkgo.GraphServiceClient client
	_, err := Client().Users().ByUserId(userID).MailFolders().
		ByMailFolderId("Sent Items").Messages().ByMessageId(parentItemID).Attachments().Post(ctx, body, nil)
	// Error received from this POST
	if err != nil {
		return
	}

}

func getAttachment(orig models.Messageable) (models.Messageable, error) {
	attachments, err := getAttachment(message.GetAttachments())

	if err != nil {
		return nil, err
	}

	orig.SetAttachments(attachments)

	return message, nil
}

```

Error: On running the above code with payload provided an error `parsing time "2023-06-27T06:21:33" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "Z07:00""` is received with 400 status code. But the problem seems to be with the json payload created with the above code. The payload has an invalid ',' inserted at the start of attachment sub struct.  Also the sub struct with attachment is blank.  

```
{
   "id":"AAMkAGQ1NzViAAAAAEMAAB8wYc0thTTTYl3RpEYIUq_AADFfThSAAABEgAQAIyAgT1ZccRCjKKyF7VZ3dA=",
  ...
   "item":{
      "attachments":[
        // extra comma here 
         ,
         {
            "id":"AAMkAGQ1NzIUq_AAAAAAEMAAB8wYc0thTTTYl3RpEYIUq_AADFfThSAAACEgAQAI02RpJrZPzCBFQ==",
           ...
            "item":{
               "calendar":null,
              ...
              // this attachment is blank!!
               "attachments":[
                  
               ],
               "body":{
                  "content":"<html><head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"><metahttp-equiv=\"Content-Type\"content=\"text html;charset=\"utf-8&quot;\"></head><body>Let'slookforfunding! </body></html>",
                  "contentType":"html"
               },
             ...
            }
         }
      ],
      "body":{
         "content":"<html><head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"><metahttp-equiv=\"Content-Type\"content=\"text html;charset=\"utf-8&quot;\"><styletype=\"text css?style=\"display:none\"><!--\r\np\r\n\t{margin-top:0;\r\n\tmargin-bottom:0}\r\n--><bodydir=\"ltr\"><divclass=\"elementToProof\"style=\"font-family:Calibri,Arial,Helvetica,sans-serif;font-size:12pt;color:rgb(0,0,0);background-color:rgb(255,255,255)\"></head><body>Lookingtodothis&nbsp; <div></div></body></html>",
         "contentType":"html"
      },
     ...
      "webLink":"https://outlook.office365.com/owa/?AttachmentItemID=AAMkTM"
   }
}
```
The complete [payload](https://gist.github.com/neha-Gupta1/9b763c7db46f2d608cd4b6f38a7b172c) created by msgraph-sdk-go.

Note: its a relatively simplified version of code. Also the same error is seen in case of events attachments inside a message attachment.

**Comment by neha-Gupta1** [comment]
@rkodev  any updates here?

**Comment by neha-Gupta1** [comment]
One more finding here- On trying to get the drive with `Users().ByUserId(userID).Drive().Get(ctx, nil)` info for user who has no active drive, receiving an error -  `parsing time "2023-07-10T07:40:39" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "Z07:00""`

**Comment by rkodev** [comment]
Hi @neha-Gupta1 , Thanks for the update on the date serialization issue, this has been reported [here](https://github.com/microsoftgraph/msgraph-sdk-go-core/issues/212). Kindly use that issue to report the date serialization.

**Comment by rkodev** [comment]
Looking at this comment `Error: On running the above code with payload provided an error parsing time "2023-06-27T06:21:33" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "Z07:00"" is received with 400 status code. But the problem seems to be with the json payload created with the above code. The payload has an invalid ',' inserted at the start of attachment sub struct. Also the sub struct with attachment is blank.`

The error you are getting on this response is because of the date serialization. This issue is currently being worked on and we should expect a fix by the next release

**Comment by neha-Gupta1** [comment]
@rkodev there are two issues here-
- the invalid payload getting generated(, in the payload) which results in a 400 response.
- now when the error response is parsed we get the date serialization issue.
So ideally if the first issue is fixed(extra , in the payload) we won't see date  serialization issue at all.

**Comment by neha-Gupta1** [comment]
Hello @rkodev,
any updates here?

**Comment by zackrossman** [comment]
@neha-Gupta1 @rkodev is there any update on this?

> This issue is currently being worked on and we should expect a fix by the next release

**Comment by rkodev** [comment]
Hi @zackrossman , @neha-Gupta1 The root cause of the "extra comma" seems to be as a result of serialization of a nil values in collections. 
@neha-Gupta1 In your case to get past this issue you can check that the attachments are not nill, a fix is being worked on in the serialization library to send a "null" as opposed to no value
