### ISSUE TITLE
Query parameters not populating request

### ISSUE THREAD

**Issue by simongottschlag** [microsoftgraph/msgraph-sdk-go#52]
Hi!

I've been trying out this module and it seems like there's something wrong when following your examples.

I've tried the following:
```go
func run() error {
	cred, err := azidentity.NewAzureCLICredential(&azidentity.AzureCLICredentialOptions{})
	if err != nil {
		return fmt.Errorf("error creating credentials: %w", err)
	}

	auth, err := a.NewAzureIdentityAuthenticationProviderWithScopes(cred, []string{"https://graph.microsoft.com"})
	if err != nil {
		return fmt.Errorf("error authentication provider: %w", err)
	}

	adapter, err := msgraphsdk.NewGraphRequestAdapter(auth)
	if err != nil {
		return fmt.Errorf("error creating adapter: %w", err)
	}

	client := msgraphsdk.NewGraphServiceClient(adapter)

	startDateTime := "2021-12-12T20:57:37.046Z"
	endDateTime := "2021-12-19T20:57:37.046Z"

	query := calendarview.CalendarViewRequestBuilderGetQueryParameters{
		StartDateTime: &startDateTime,
		EndDateTime:   &endDateTime,
	}

	options := calendarview.CalendarViewRequestBuilderGetOptions{
		Q: &query,
	}

	result, err := client.Me().CalendarView().Get(&options)
	if err != nil {
		return fmt.Errorf("get req failed: %w", err)
	}

	for _, event := range result.GetValue() {
		subject := event.GetSubject()
		startTime := event.GetStart()
		endTime := event.GetEnd()
		fmt.Printf("%s (%s - %s)\n", *subject, *startTime.GetDateTime(), *endTime.GetDateTime())
	}

	return nil
}
```

This causes no errors and no results (`GetValue()` is empty). Digging down deeper into when the request is sent using the debugger, I can see that the query parameters are never populated. I can also see that the body returned by the graph api is:
`"{\"error\":{\"code\":\"ErrorInvalidParameter\",\"message\":\"This request requires a time window specified by the query string parameters StartDateTime and EndDateTime.\"}}"`

Not sure exactly which of all the modules involved in this actually causing the issue, but I'll start here and please point me in the right direction if you don't think it can be solved from here.

**Comment by baywet** [comment]
Hi @simongottschlag ,
Thanks for reaching out and for trying the sdk.
This sounds very similar to #44.
Can you make sure your application has its dependencies up to date please by running go get -u at the root of your project?

Also at the authentication part, if you just want the default permissions the app is registered for, you can simply call a.NewAzureIdentityAuthentication(cred) instead.

**Comment by simongottschlag** [comment]
Hi @baywet!

Thank you for your response! :^)

When running `go get -u`, my computer broke. :-( Not really broke, but it never went passed the following:

```shell
go get -u                                                                                                                                                                                                                
go: downloading github.com/microsoft/kiota/authentication/go/azure v0.0.0-20211213121005-916d74626d0b
go: downloading github.com/microsoft/kiota/abstractions/go v0.0.0-20211213121005-916d74626d0b
go: downloading github.com/microsoft/kiota/serialization/go/json v0.0.0-20211213121005-916d74626d0b
go: downloading github.com/microsoft/kiota/http/go/nethttp v0.0.0-20211213121005-916d74626d0b
```

After 15 minutes, I pressed `CTRL+C`. Asked a friend and same experience there.

I was able to _only_ update the SDK: `go get -u github.com/microsoftgraph/msgraph-sdk-go` - it only took 2,5 minutes of 100% CPU!

It gave me the following deps:

```go
[...]

require (
	[...]
	github.com/microsoftgraph/msgraph-sdk-go v0.3.2
)

require (
	[...]
	github.com/microsoft/kiota/abstractions/go v0.0.0-20211213121005-916d74626d0b // indirect
	github.com/microsoft/kiota/http/go/nethttp v0.0.0-20211213121005-916d74626d0b // indirect
	github.com/microsoft/kiota/serialization/go/json v0.0.0-20211213121005-916d74626d0b // indirect
	[...]
)
```

I did try `v0.3.2` yesterday and went down to `v0.3.1` as well as `v0.3.0` without any success.

Any ideas why `go get -u` never finishes? I've never seen that before. 

Unfortunately, the above (without actually being able to finish updates of everything) didn't work either. I did switch to `a.NewAzureIdentityAuthentication(cred)` though, thanks for the tip :+1: 

Any ideas what the next step should be? I could try leaving the computer on over the night and see if the update ever finishes.

Sorry for the wall of text, I'm really confused at the moment. :^)

**Comment by simongottschlag** [comment]
Well, actually! It seems like the update I managed to get through actually works. Now the query parameters get passed to the request, but I'm getting a 403 due to az cli not being permitted the Calendars.Read scope in my directory.

**Comment by baywet** [comment]
Glad it solved your problem.
On the fact it takes a while to update, I've noticed that too. The update seems to be recompiling everything including dependencies multiple times instead of once when you don't specify a dependency name in the command.
I'm not sure why the go cli does that though. When you update a single dependency it doesn't.

On the permissions aspect. Azure identity seems to default the client ID to the one they use for the cli when nothing is provided.
But you should register your own application and set the ID in the credentials.

I hope that helps.

**Comment by baywet** [comment]
I've also noted that if visual studio code is open on the project while I run the update command, the update command takes significantly longer. Maybe some kind of negative feedback loop happening here.
