### ISSUE TITLE
Investigate high number of known issues for V1 (2K+)

### ISSUE THREAD

**Issue by ddyett** [microsoftgraph/msgraph-sdk-go#538]
Investigate and fix the large number of known issues in Go Raptor tests. 

- [x] #541
- [ ] Update know issues list for go raptor tests

**Comment by rkodev** [comment]
- [ ] Fix 1K+ issues as a result of the inaccurate fluent path generated

**Comment by rkodev** [comment]
Fixed by https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/1681 and https://github.com/microsoftgraph/microsoft-graph-devx-api/pull/1679
