### ISSUE TITLE
GET method for Teams missing

### ISSUE THREAD

**Issue by neha-Gupta1** [microsoftgraph/msgraph-sdk-go#539]
The get Teams method corresponding to - GET /teams API is missing for SDK.

Steps to reproduce- 
```
client.Teams().Get() // client of type *msgraphsdkgo.GraphServiceClient
``` 
call fails as unable to find the Get() method.

**Comment by rkodev** [comment]
@neha-Gupta1 Are you able to confirm which version of the SDK you are using?

Testing using the latest version, this is possible
```go
	teams, err := graphClient.Teams().Get(context.Background(), nil)
	if err != nil {
		return 
	}	
	for _, team := range teams.GetValue() {
		fmt.Printf("Team name is : %v\n", team.GetDisplayName())
	}

```

**Comment by neha-Gupta1** [comment]
It seems to be working fine with the latest version. Thank you @rkodev
