### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by TomerHeber** [microsoftgraph/msgraph-sdk-go#54]
Hi,

I'm getting a fatal error `fatal error: concurrent map writes`. (Stacktrace below) when creating multiple clients.
I'll check if I mutexes or sync.once can help, and update.

goroutine 873 [running]:
runtime.throw({0x1cbe360, 0x4739268})
	/usr/local/Cellar/go/1.17.5/libexec/src/runtime/panic.go:1198 +0x71 fp=0xc000979ba8 sp=0xc000979b78 pc=0x1036991
runtime.mapassign_faststr(0x1b4c020, 0xc0001ba7e0, {0x1cb7f79, 0x10})
	/usr/local/Cellar/go/1.17.5/libexec/src/runtime/map_faststr.go:294 +0x38b fp=0xc000979c10 sp=0xc000979ba8 pc=0x10143cb
github.com/microsoft/kiota/abstractions/go.RegisterDefaultSerializer(0x100c0001100b0)
	/Users/theber/go/pkg/mod/github.com/microsoft/kiota/abstractions/go@v0.0.0-20211214082231-caf19efef7a9/api_client_builder.go:12 +0x5e fp=0xc000979c50 sp=0xc000979c10 pc=0x14a64be
github.com/microsoftgraph/msgraph-sdk-go.NewGraphServiceClient({0x1ee2f90, 0xc0004fe410})
	/Users/theber/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.3.2/graph_service_client.go:271 +0xc5 fp=0xc000979c88 sp=0xc000979c50 pc=0x1663385

Crash is occurring in line 12 `s.DefaultSerializationWriterFactoryInstance.ContentTypeAssociatedFactories[contentType] = factory`

```
package abstractions

import (
        s "github.com/microsoft/kiota/abstractions/go/serialization"
)

// RegisterDefaultSerializer registers the default serializer to the registry singleton to be used by the request adapter.
func RegisterDefaultSerializer(metaFactory func() s.SerializationWriterFactory) {
        factory := metaFactory()
        contentType, err := factory.GetValidContentType()
        if err == nil && contentType != "" {
                s.DefaultSerializationWriterFactoryInstance.ContentTypeAssociatedFactories[contentType] = factory
        }
}

// RegisterDefaultDeserializer registers the default deserializer to the registry singleton to be used by the request adapter.
func RegisterDefaultDeserializer(metaFactory func() s.ParseNodeFactory) {
        factory := metaFactory()
        contentType, err := factory.GetValidContentType()
        if err == nil && contentType != "" {
                s.DefaultParseNodeFactoryInstance.ContentTypeAssociatedFactories[contentType] = factory
        }
}
```

**Comment by TomerHeber** [comment]
https://github.com/microsoft/kiota/blob/efb42b44e341043a81e75b2c4291eeb1ab90485f/abstractions/go/api_client_builder.go

**Comment by TomerHeber** [comment]
The following workaround solved the issue for me (adding a mutex):

```
func newGraphClient(ctx context.Context, cc CallContext, topic string) (*msgraphsdkgo.GraphServiceClient, error) {
	adapter, err := newGraphAdapter(ctx, cc, topic)
	if err != nil {
		return nil, err
	}

	// https://github.com/microsoftgraph/msgraph-sdk-go/issues/54
	mutex.Lock()
	defer mutex.Unlock()
	return msgraphsdkgo.NewGraphServiceClient(adapter), nil
}
```

**Comment by baywet** [comment]
Hi @TomerHeber,
Thanks for trying out the SDK and for reaching out.
I was able to reproduce and fix this bug and I put a PR together [over the kiota repo](https://github.com/microsoft/kiota/pull/996).

Please have a look at the pull request and don't hesitate to provide any feedback.

Once the PR gets merged, running `go get -u` at the root of your project should grab the latest version.

This issue will be closed when the pull request gets merged.

**Comment by TomerHeber** [comment]
Hi @baywet ,

Thank you for the update.

I briefly reviewed the PR. Adding a mutex seems like a valid solution.

You may also consider this option:
https://pkg.go.dev/sync#Map

(It really depends on how often the factory method is called).

Thank you for taking care of this so quickly!

**Comment by baywet** [comment]
I noticed that "concurrent map" when looking into the issue. I chose to keep the current map we have as we don't anticipate people instantiating a lot of new clients in a single application. I wasn't sure what were the performance impacts of using this map compared with using the "regular one" and decided to play it safe.. (historically in dotnet concurrent dictionary has been much slower than the regular one).

Actually I'm curious about your scenario that necessitates a lot of clients instantiations?

**Comment by TomerHeber** [comment]
Hi @baywet ,

I totally agree about "concurrent map". It really depends on the use case.

Regarding your question:
In our use-case our Microservices handles multiple tenants (customers), it could potentially reach 100s/1000s of clients on a single microservice.

Another reason to use multiple clients is rate-limiting. Not all APIs are the same, rate-limiting policies vary.
So we use multiple clients depending on the API call and enforce varying rates to the graph API.

**Comment by FabianTe** [comment]
Today I had the same issue (see stack trace below). I too may have a scenario where concurrently my application may interact with dozens (hundreds?) of tenants at the same time.

I also use a lock to avoid this issue: https://gist.github.com/FabianTe/b87e2fcf4107f46a8e7c61bf5078fe40

```
fatal error: concurrent map writes

goroutine 7 [running]:
github.com/microsoft/kiota-abstractions-go.RegisterDefaultDeserializer(0xc0001259c8?)
        /home/fabian/go/pkg/mod/github.com/microsoft/kiota-abstractions-go@v0.19.0/api_client_builder.go:30 +0xa5
github.com/microsoftgraph/msgraph-sdk-go.NewGraphBaseServiceClient({0xb77600, 0xc000210460}, 0x0?)
        /home/fabian/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.60.0/graph_base_service_client.go:240 +0x23d
github.com/microsoftgraph/msgraph-sdk-go.NewGraphServiceClient(...)
        /home/fabian/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.60.0/graph_service_client.go:17
github.com/microsoftgraph/msgraph-sdk-go.NewGraphServiceClientWithCredentialsAndHosts({0xb6ed60?, 0xc000204220?}, {0xc000125d18?, 0xc00007e1e0?, 0xc0001dc420?}, {0x0?, 0xc0001849c0?, 0xc00011fcc0?})
        /home/fabian/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.60.0/graph_service_client.go:52 +0x19c
github.com/microsoftgraph/msgraph-sdk-go.NewGraphServiceClientWithCredentials(...)
        /home/fabian/go/pkg/mod/github.com/microsoftgraph/msgraph-sdk-go@v0.60.0/graph_service_client.go:25
```
