### ISSUE TITLE
MSGraph Permission delay in SDK

### ISSUE THREAD

**Issue by piyushdatazip** [microsoftgraph/msgraph-sdk-go#550]
Golang SDK have a delay when assigned MSGraph Permissions to azure managed Identity. 

Azure CLI installed in Pod get's access with managed identity in few minutes. but azidentity and msgraph SDK are taking hours to resolve the permission. 
I've added a FATAL which forces the service to restart in AKS making sure that it has refreshed token

Due to this my team is routing towards CLI execution and parsing the output. SDK isn't helping in this

**Comment by piyushdatazip** [comment]
Tagging @andrueastman for your attention here

**Comment by rkodev** [comment]
Hi @piyushdatazip , Thanks for trying the SDK. F
I'd like to see  the code that you are using to trying to retrieve the Permission in GoLang. There is a context timeouts that's added to requests and I'd like to know what code path is resulting to more than a 1hr wait.
