### ISSUE TITLE
UnknownError code from graph SDK

### ISSUE THREAD

**Issue by karanpahlani** [microsoftgraph/msgraph-sdk-go#559]
Are there any plans to address  UnknownError code responses?

Current all I see in response is

```
Code: UnknownError
No error message
```

We get this response a decent number of times 25-10 every day and would like to:

- Better handle these unknown errors
-  Get more insight into what went wrong.

Would appreciate any insight on whether this is in the works or already exists and I am simply missing something.
Also any guidance on how to handle them

Thanks,
Karan

**Comment by eric-millin** [comment]
See https://github.com/microsoftgraph/msgraph-sdk-go/issues/510

Personally, I've written a custom function to dump the ODataError

**Comment by rkodev** [comment]
Hi @karanpahlani ,

as mentioned above,this issue is related to issue https://github.com/microsoftgraph/msgraph-sdk-go/issues/510. As mentioned in this [comment](https://github.com/microsoftgraph/msgraph-sdk-go/issues/510#issuecomment-1731978625) the error message was improved as of release v1.19.0
