### ISSUE TITLE
1.0 APIs are missing from the SDK.

### ISSUE THREAD

**Issue by TomerHeber** [microsoftgraph/msgraph-sdk-go#56]
Hi,

I noticed that the following APIs are available in 1.0, but are currently not available in the SDK.
Note that they are available in the beta SDK.

https://docs.microsoft.com/en-us/graph/api/resources/identityprotectionroot?view=graph-rest-1.0

Beta reference:
https://github.com/microsoftgraph/msgraph-beta-sdk-go/blob/7fd30d3dd5d20f0cd7b387da57e0a30c2859d997/models/microsoft/graph/identity_protection.go

**Comment by baywet** [comment]
I've just heard back from the service team, they are now working on fixing the metadata.
The change should show up in the sdk in 2/3 weeks at the latest.

**Comment by baywet** [comment]
Hi @TomerHeber 
Thanks for your patience. The service team has corrected their metadata and the change is present in #64.
When this PR gets merged, it'll close this issue.
The only thing left is to run `go get -u` at the root of your project to get the latest version of the SDK.
Thanks again for reporting this!

**Comment by TomerHeber** [comment]
Hi @baywet ,

Thank you for the update and the quick turnaround!
