### ISSUE TITLE
Directory deleted items - SDK generates code incorrectly.

### ISSUE THREAD

**Issue by TomerHeber** [microsoftgraph/msgraph-sdk-go#57]
As described here:
https://docs.microsoft.com/en-us/graph/api/directory-deleteditems-list?view=graph-rest-1.0&tabs=http

`The OData cast type is a required part of the URI and calling GET /directory/deleteditems without a type is not supported.`

The SDK expects `GET /directory/deleteditems` which is incorrect.

Should be something like this:
`client.Directory().DeletedItems().Users().Get()`

Tried `client.Directory().DeletedItemsById("...")` but this returns the wrong type (A single object).

**Comment by baywet** [comment]
Hi @TomerHeber,
Thanks for trying out the SDK and for reaching out.
You are right, endpoints for collection/items type cast for OData are missing.
To understand this problem better here is an overview of how we generate the Go SDK:

1. The service owners publish [metadata](https://graph.microsoft.com/v1.0/$metadata) (CSDL) about their APIs.
2. This metadata [gets converted to an OpenAPI description](https://github.com/microsoft/OpenAPI.NET.OData).
3. The OpenAPI description is processed by [kiota](https://github.com/microsoft/kiota), our next gen SDK generator.
4. The Go SDK is generated.

Now, we have identified a few issues with step 2 we're working on fixing, including [missing typecast segments in the resulting description](https://github.com/microsoft/OpenAPI.NET.OData/pull/149).

Although this issue has been fixed, it hasn't been released yet, [we have a number of other issues we're working on fixing before releasing a new version of the conversion process](https://github.com/microsoft/OpenAPI.NET.OData/milestone/5).

I'll revert here once everything is wrapped up for this, it might take a few weeks.

In the meantime, you can workaround this issue by using the [UsersRequestBuilder and passing in the URL yourself](https://github.com/microsoftgraph/msgraph-sdk-go/blob/7e61e55777ef141bc8038364dfead12186470db3/users/users_request_builder.go#L77), you'll loose the benefits of a fluent API, but at least you'll get deserialization and other aspects of the SDKs (compared with using a native client).

**Comment by baywet** [comment]
Update we just released a version that relies on the updated descriptions and that also fixes using request builders with a raw url.

While this doesn't yet add the API path for the .Users() sub segment, this is good progress towards that. I've logged [an issue](https://github.com/microsoftgraph/msgraph-metadata/issues/126) to update the metadata so we get the new path.

to update

```bash
go get -u github.com/microsoftgraph/msgraph-sdk-go@v0.13.0
```

**Comment by baywet** [comment]
update the [path segment is now available](https://github.com/microsoftgraph/msgraph-sdk-go/blob/c994a6500dc1be44fdd42e6dc81635f89c5f8e0b/directory/deleteditems/user/user_request_builder.go#L90).

```shell
go get -u github.com/microsoftgraph/msgraph-sdk-go@v0.26.0
```

to get the latest version

and then

```golang
client.Directory().DeletedItems().User().Get() // note the absence of s at the end of user
```

Closing. Let us know if you need anything else!
