### ISSUE TITLE
How to get drive deltas

### ISSUE THREAD

**Issue by eric-millin** [microsoftgraph/msgraph-sdk-go#582]
I want to call `delta` without any parameters as described by the documentation. While I see how to get deltas for a DriveItem, I don't see a way to get deltas for all items. Wondering if it's possible. I.e., how do I query `/drives/{drive-id}/root/delta`?

https://learn.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&tabs=go

@rkodev @baywet

**Comment by baywet** [comment]
Hi @eric-millin,
Thanks for using the SDK and for reaching out.
For future issues, no need to mention people from the team, we have a triage process in place to make sure we answer issues.

This one is a bit more complex due to design limitations of OData and the size of Microsoft Graph. Long story short, we only project canonical paths to the SDKs to avoid SDKs becoming too large. In the case of drive the canonical path is /drives/id/... and for drive item the canonical path is ../items/{id}, root is just a shorthand.

So in multiple requests:

```go
driveId := "someId"

root, err := graphClient.Drives().ByDriveId(driveId).Root().Get(context.Background(), nil)
delta, err := graphClient.Drives().ByDriveId(driveId).Items().ByDriveItemId(*root.GetId()).Delta().Get(context.Background(), nil)
```

But if you already have the full URL for delta (from the delta link of a previous request for example), you can issue a single request

```go
uri := "someUri"

delta, err := graphClient.Drives().ByDriveId("foo").Items().ByDriveItemId("bar").Delta().WithUrl(uri).Get(context.Background(), nil)
```

**Comment by eric-millin** [comment]
> Hi @eric-millin, Thanks for using the SDK and for reaching out. For future issues, no need to mention people from the team, we have a triage process in place to make sure we answer issues.
> 

Will do. I looked at the other issues and it appeared that many lacked responses altogether or hadn't been followed up on in a couple months. I'll be honest that it made me anxious about using these packages. Good to know that there's a process in place.

**Comment by eric-millin** [comment]
> ```go
> delta, err := graphClient.Drives().ByDriveId("foo").Items().ByDriveItemId("bar").Delta().WithUrl(uri).Get(context.Background(), nil)
> ```

@baywet It appears the code you're using is from an older version of the SDK. When I try to do this with the latest version I get an error for `WithUri`

> undefined (type *"github.com/microsoftgraph/msgraph-sdk-go/drives".ItemItemsItemDeltaRequestBuilder has no field or method WithUrl)

```go
graphClient.Drives().ByDriveIdString("foo").Items().ByDriveItemIdString("bar").Delta().WithUrl(uri).Get(context.Background(), nil)
```

It looks like you have to parse the odata.deltaLink URL to get the `token` value and then pass that on subsequent requests.

```go
graphClient.Drives().ByDriveIdString(driveId).Items().ByDriveItemIdString(rootId).DeltaWithToken(deltaToken).Get(context.Background(), nil)
```

**Comment by baywet** [comment]
@eric-millin please make sure you're using the latest version of the SDK as the method is present.
https://github.com/microsoftgraph/msgraph-sdk-go/blob/7b8ce31a83f74b419511f55abe50614f6f1bc29c/drives/item_items_item_delta_request_builder.go#L88

This delta with token method shouldn't exist, it's a design issue from the SharePoint we've been trying to get them to correct, I have created an [additional issue in the metadata repo](https://github.com/microsoftgraph/msgraph-metadata/issues/431) so we can fix this in post.

**Comment by eric-millin** [comment]
> @eric-millin please make sure you're using the latest version of the SDK as the method is present.
> 
> https://github.com/microsoftgraph/msgraph-sdk-go/blob/7b8ce31a83f74b419511f55abe50614f6f1bc29c/drives/item_items_item_delta_request_builder.go#L88
> 
> This delta with token method shouldn't exist, it's a design issue from the SharePoint we've been trying to get them to correct, I have created an [additional issue in the metadata repo](https://github.com/microsoftgraph/msgraph-metadata/issues/431) so we can fix this in post.

I see it in 1.18.0, thanks

**Comment by eric-millin** [comment]
@baywet You're probably already aware, but the lists delta API in the beta SDK has the same issue with `DeltaWithToken`

**Comment by baywet** [comment]
I was aware but I forgot to document it in my metadata issue. Thanks. Now that everything is resolved. Closing.

**Comment by eric-millin** [comment]
@baywet Cool, thanks for the help 👍
