### ISSUE TITLE
NewOnlineMeeting

### ISSUE THREAD

**Issue by Traliaa** [microsoftgraph/msgraph-sdk-go#59]
No method `NewOnlineMeeting()`  
https://docs.microsoft.com/ru-ru/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&tabs=go

**Comment by baywet** [comment]
Hi @Traliaa,
Thanks for trying out the SDK, reaching out, and for your patience. I was on vacations last week.
There's a `NewOnlineMeeting` function, but it's under a [different import path](https://github.com/microsoftgraph/msgraph-sdk-go/blob/7e61e55777ef141bc8038364dfead12186470db3/models/microsoft/graph/online_meeting.go#L57)

```Golang
import (
   models "github.com/microsoftgraph/msgraph-sdk-go/models/microsoft/graph"
)
// ...
models.NewOnlineMeeting()
```

Should work.
Let us know if you have further questions.
