### ISSUE TITLE
A Typo in Error Response When Creating Subscriptions 

### ISSUE THREAD

**Issue by Rashad-j** [microsoftgraph/msgraph-sdk-go#596]
When trying to create subscriptions, we usually get an error. There is a type in the error message:
```
{
    "error": {
        "code": "ExtensionError",
        "message": "Operation: Create; Exception: [Status Code: Conflict; Reason: A subscripton already exists. It must be deleted before a another can be made.]",
        "innerError": {
            "date": "2023-10-16T04:39:39",
            "request-id": "12b6298c-9cbc-457c-b34e-adkfue78a7b7",
            "client-request-id": "12sd928c-9cbc-499c-b34e-48djgl78a7b7"
        }
    }
}
```

The word **subscripton** is incorrect.

**Comment by baywet** [comment]
Hi @Rashad-j 
Thanks for reporting this.
This repository is dedicated to the Go SDK itself. For issues with the service the best course of actions is to create a post [in the dedicated Microsoft Q&A forum](https://learn.microsoft.com/en-us/answers/tags/304/microsoft-graph-change-notifications-api) with the microsoft graph change notifications tag in this case.
Service team members will be able to reply and address the issue there.
