### ISSUE TITLE
NotEqualsMatch is not supported. user list from B2C (However able to get it form Graph Explorer)

### ISSUE THREAD

**Issue by namdhev-kr** [microsoftgraph/msgraph-sdk-go#599]
## **Issue**
While listing users whose _mobilePhone ne null_ the graph explorer is able to provide appropriate response. However, the golang SDK for msgraph is throwing the following error
`error: Filter operator 'NotEqualsMatch' is not supported.code: Request_UnsupportedQuerymsg: Filter operator 'NotEqualsMatch' is not supported.user list from b2c,`

## **Code snippet for initialising and listing users**

```go
func (g *GraphHelper) InitializeGraphServiceClient() error {
	err := godotenv.Load("configs/.env")
	if err != nil {
		return err
	}

	clientId := os.Getenv("B2C_CLIENT_ID")
	tenantId := os.Getenv("B2C_TENANT_ID")
	clientSecret := os.Getenv("B2C_CLIENT_SECRET")
	scopes := os.Getenv("GRAPH_SCOPES")  // default scope
	g.graphUserScopes = strings.Split(scopes, ",")

	credential, err := azidentity.NewClientSecretCredential(tenantId, clientId, clientSecret, nil)

	if err != nil {
		return err
	}
	g.clientCredential = credential

	// Create an auth provider using the credential
	authProvider, err := auth.NewAzureIdentityAuthenticationProvider(credential)
	if err != nil {
		return err
	}

	// Create a request adapter using the auth provider
	adapter, err := msgraphsdk.NewGraphRequestAdapter(authProvider)
	if err != nil {
		return err
	}

	// Create a Graph client using request adapter
	client := msgraphsdk.NewGraphServiceClient(adapter)
	g.graphClient = client

	return nil
}

func (g *GraphHelper) ListUsers() (*models.UserCollectionResponseable, error) {

	headers := abstractions.NewRequestHeaders()
	headers.Add("ConsistencyLevel", "eventual")

	requestFilter := "mobilePhone ne null"
	requestCount := true

	requestParameters := &graphusers.UsersRequestBuilderGetQueryParameters{
		Filter: &requestFilter,
		Count:  &requestCount,
	}
	configuration := &graphusers.UsersRequestBuilderGetRequestConfiguration{
		Headers:         headers,
		QueryParameters: requestParameters,
	}

	users, err := g.graphClient.Users().Get(context.Background(), configuration)
	if err != nil {
		return nil, err
	}

	pageIterator, err := msgraphgocore.NewPageIterator[models.Userable](users, g.graphClient.GetAdapter(), models.CreateUserCollectionResponseFromDiscriminatorValue)

	err = pageIterator.Iterate(context.Background(), func(user models.Userable) bool {
		fmt.Printf("%s\n", *user.GetDisplayName())
		// Return true to continue the iteration
		return true
	})

	return &users, nil

}
```

## **Screenshots**
_**Graph Explorer**_
<img width="1461" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-go/assets/110983154/1e6c99b3-9fe6-40ea-b354-c70e228fe876">

_**Code run through IntelliJ IDEA Ultimate**_
![image](https://github.com/microsoftgraph/msgraph-sdk-go/assets/110983154/ee9d5756-acd0-484b-b005-e58e2b1e9857)

_**Dependency versions**_
<img width="752" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-go/assets/110983154/9624f46b-4a48-45c2-9f53-96974ebc7fcc">

**Comment by namdhev-kr** [comment]
The same happens even for running thru postman with bearer token from client credentials

**cURL**
`
curl --location 'https://graph.microsoft.com/v1.0/users?%24filter=mobilePhone%20ne%20null&%24count=true' \
--header 'ConsistencyLevel: eventual' \
--header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI6ImxJRmNxZUtmeHJFNDlxemhNOUhDQ1QzVURZSmNiOUdIcWJrU3c3WjZIalEiLCJhbGciOiJSUzI1NiIsIng1dCI6IjlHbW55RlBraGMzaE91UjIybXZTdmduTG83WSIsImtpZCI6IjlHbW55RlBraGMzaE91UjIybXZTdmduTG83WSJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC83MTEyMzYyOS0wYjM4LTQ1MDUtODA3Mi1jZjFjMjcxYmM5YmEvIiwiaWF0IjoxNjk4MDM5NzY2LCJuYmYiOjE2OTgwMzk3NjYsImV4cCI6MTY5ODA0MzY2NiwiYWlvIjoiRTJGZ1lIQ1F5TjYxc3YwNDY3bE84MFdySk5KK0FnQT0iLCJhcHBfZGlzcGxheW5hbWUiOiJPVFMgR3JhcGggQ2xpZW50IiwiYXBwaWQiOiJhYTExZTA0OC01OTcxLTRmY2YtOTk5Yi02MzcwY2NmZjA3ODgiLCJhcHBpZGFjciI6IjEiLCJpZHAiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC83MTEyMzYyOS0wYjM4LTQ1MDUtODA3Mi1jZjFjMjcxYmM5YmEvIiwiaWR0eXAiOiJhcHAiLCJvaWQiOiIwNGU5MGY2YS1kMTc3LTQwNzgtYTVkNS0yYjAzNmQwZGU4NjQiLCJyaCI6IjAuQVIwQUtUWVNjVGdMQlVXQWNzOGNKeHZKdWdNQUFBQUFBQUFBd0FBQUFBQUFBQUFkQUFBLiIsInJvbGVzIjpbIlVzZXIuUmVhZFdyaXRlLkFsbCJdLCJzdWIiOiIwNGU5MGY2YS1kMTc3LTQwNzgtYTVkNS0yYjAzNmQwZGU4NjQiLCJ0ZW5hbnRfcmVnaW9uX3Njb3BlIjoiTkEiLCJ0aWQiOiI3MTEyMzYyOS0wYjM4LTQ1MDUtODA3Mi1jZjFjMjcxYmM5YmEiLCJ1dGkiOiJvU3h2MWsyZ0ZVdTZQRTFGRmRkSUFBIiwidmVyIjoiMS4wIiwid2lkcyI6WyIwOTk3YTFkMC0wZDFkLTRhY2ItYjQwOC1kNWNhNzMxMjFlOTAiXSwieG1zX3RjZHQiOjE1OTcyNjU1NDR9.vEGogkZvwz-XM3rH8eTVWQVbDOB8cxVnulOBZYsIm1OlATmLd-sdKKubsuZ9vb-GNN2Yc1I7cFfKRqT3r23W8RhlWo_CIxjtUFKWDWQR8M5eAoQbNNXKEy0V57s2yuOjsRBkgpzn_gVSKNOeXzmZPPaNchvRQJc_JYiZcNB2qrmrNkJANa0pskw6juDoudeorvB97cghUssVEo6sNfvdJZK-hMIdC6hTvPdy3YCd1khRpdp6-yMmy05-RtdO2n1T3kOyIJ1SxnxN_tC23r7HCbXEguDC1kFCnz7LSbnDZlFEgxGaG0XAm5RLfEiyxXrI9ENY3iHDh6Hd_prIctqNTA'
`

**Comment by baywet** [comment]
Thanks for reaching out @namdhev-kr 
First, please refrain from including tokens in your messages, this posses a security risk for your organization.
Then, I believe you're getting this error when the iterator attempts to get the second page because the consistency level header is not being set by the page iterator, and the request gets routed to a service that doesn't support this filter.

After you create the page iterator, and before you call Iterate, call the SetHeaders method on the iterator to set the consistency level header like you did in the initial request.

Let us know if you have further questions.

**Comment by namdhev-kr** [comment]
Hi @baywet  - Thanks for your suggestion. I have complied accordingly and removed the token.

I removed the pageIterator and still the error occurs. When I debugged the code, i could see that the header key got changed to lower case.

This is a common golang problem where request headers are lower cased by default before sending it over. Kindly refer: https://github.com/golang/go/issues/5022 

While I tried to set the _**ConsistencyLevel:eventual**_ header per suggested alternative fix for the same, the abstractions.RequestHeaders does not allow headers to be indexed.

**Comment by baywet** [comment]
The casing of the header shouldn't matter (you can try any casing with curl/graph explorer and you should see a consistent behaviour).

I was able to run the same exact request locally and have it succeed. One thing to be careful about is that some OData query parameters or their value are not supported by mezzo (the service which answers when the consistency level header and count query parameter are set), and mezzo reverts back to DS API (the legacy service that answer any other request), which in turns might not support the filter.

An example of that is if you are also providing a expand query parameter. So please make sure you're running the same request (same query parameters, same headers).

**Comment by Licantrop0** [comment]
Hi @namdhev-kr, [Advanced Queries](https://learn.microsoft.com/en-us/graph/aad-advanced-queries?tabs=http) (the ones requiring `$count=true` query param and `ConsistencyLevel=eventual` header), allowing you to use `NE` operator, are not supported on B2C tenants, see the note in the documentation linked above:
![Uploading image.png…]()

We don't have any other solution at the moment other than filtering client side. However, the new CIAM tenants announced at Build will have the support for all Advanced Queries.

**Comment by Licantrop0** [comment]
Hi @namdhev-kr, [Advanced Queries](https://learn.microsoft.com/en-us/graph/aad-advanced-queries?tabs=http) (the ones requiring `$count=true` query param and `ConsistencyLevel=eventual` header), allowing you to use `NE` operator, are not supported on B2C tenants, see the note in the documentation linked above:
<img width="491" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-go/assets/2388430/358e4f70-2a89-467d-aa5d-dd7c8a9d4a57">


We don't have any other solution at the moment other than filtering client side.

**Comment by baywet** [comment]
Thanks for joining the discussion @Licantrop0 
Yes, the code I tried locally was on a regular tenant on my end.
Let us know if you have further questions

**Comment by namdhev-kr** [comment]
Ah.. That solves why it is not filterable. Thanks @Licantrop0. I will watch out for updates on enabling this to B2C tenants. Closing this issue henceforth.
