### ISSUE TITLE
Invalid JSON output, caused by inherited Entity call order

### ISSUE THREAD

**Issue by pbrooks** [microsoftgraph/msgraph-sdk-go#61]
When using models such as SchemaExtension, they inherit from Entity.
Entity's serialization of AdditionalData will trim the last delimiter, if AdditionalData is empty then it will remove the delimiter from the Id field.

This will then produce invalid JSON output, that the Microsoft Graph API will reject.

A full explanation has been provided here: https://github.com/pbrooks/msgraph-sdk-go-serialize

**Comment by baywet** [comment]
Hi @pbrooks 
Thanks for reaching out, trying the Go SDK and the very thorough analysis which made it really easy to reproduce and address the bug.
I've put together a pull request to fix this issue, once it gets merged, it'll close this issue, and you can get the update by running `go get -u` in your project.

https://github.com/microsoft/kiota/pull/1012
