### ISSUE TITLE
Error: `Invalid parameter paramName: WindowLiveNetId` is thrown when calling `Delete()` on `Directory().DeletedItems()`

### ISSUE THREAD

**Issue by arturtorun** [microsoftgraph/msgraph-sdk-go#632]
# Environment Information:

API Version: `v1.0`
SDK Version: `v1.27.0` (also tested with `v1.26.0`, `v1.20.0`, `v.1.19.0`)
Go Version: `1.21.5`
Operating System: `macOS Ventura 13.6.2`

# Description:
We built in-house tool using MS Graph SDK for Go to manage our B2C Active Directory.
Affected code was working fine for more than a year, but suddenly stopped working today (18 Dec 2023).
I'm posting this issue here as according to my findings the bug might be on the edge of the SDK and the MS Graph API Server.
I've concluded that, because when I'm using the MS Graph Explorer (see below), it works fine for v1.0 API, but throws exactly the same error for beta API - which seems to be opposite to the behavior of the SDK. Furthermore I can't test Beta API of this exact Graph API method as it's not available in Beta version of MS Graph SDK for Go.

MS Graph Explorer: https://developer.microsoft.com/en-us/graph/graph-explorer?request=organization&method=DELETE&GraphUrl=https://graph.microsoft.com&tenant=DUMMYTENANT.onmicrosoft.com
(replace `DUMMYTENANT.onmicrosoft.com` with your tenant name)

Paste the below URL into the Graph Explorer (replace dummy UUID with real UUID of deleted user):
- v1.0 API, works OK (status code: `200`): `https://graph.microsoft.com/v1.0/directory/deletedItems/12345678-1234-1234-1234-123456789012`
- Beta API, returns the same error as `MS Graph SDK for Go v1.0` (status code: `400`): `https://graph.microsoft.com/beta/directory/deletedItems/12345678-1234-1234-1234-123456789012`
```json
{
    "error": {
        "code": "Request_BadRequest",
        "message": "Invalid parameter paramName: WindowLiveNetId, paramValue: null or empty, objectType: System.Collections.Generic.IList`1[[System.Byte, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]",
        "innerError": {
            "date": "2023-12-18T10:53:37",
            "request-id": "<REMOVED>",
            "client-request-id": "<REMOVED>"
        }
    }
}
```

The problem is related to the below code which deletes a User from the deleted items (recycle bin) of B2C Active Directory.

```go
userID := "<UUID_OF_USER>" // e.g. 12345678-1234-1234-1234-123456789012
err := graphClientV1.Directory().DeletedItems().ByDirectoryObjectId(userID).Delete(ctx, nil)
if err != nil {
    log.Fatal(err)
}
```

# Steps to Reproduce:
- Add new user to B2C Active Directory
- Obtain user's UUID
- Delete user from B2C Active Directory manually
- Run above code with user's UUID
- Observe the error
```log
Invalid parameter paramName: WindowLiveNetId, paramValue: null or empty, objectType: System.Collections.Generic.IList`1[[System.Byte, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]
```

# Expected Behavior:
- User is deleted from B2C Active Directory Deleted Users (Recycle Bin)

# Actual Behavior:
- Error is thrown

# Additional Context:
Build a minimal reproducible example of the bug to separate it from any application specific code.

**Comment by baywet** [comment]
@arturtorun 
Thanks for using the Go SDK and for reaching out.

@irvinesunday I looked into why the delete method is absent from beta and couldn't figure out why:
https://github.com/microsoftgraph/msgraph-sdk-go/blob/main/directory/deleted_items_directory_object_item_request_builder.go#L62
https://github.com/microsoftgraph/msgraph-beta-sdk-go/blob/main/directory/deleted_items_directory_object_item_request_builder.go

To me both beta have:
- the singleton
- the entity type
- the navigation property
- constraints
- the same contains target attributes

Would you mind having a look at that please?

@arturtorun it seems the different in behaviour between GE and Go SDK could be caused by the authentication context, how is the application authenticated?

**Comment by arturtorun** [comment]
Hi @baywet. 

Thanks for quick reply.

I'm using DeviceCode authentication with help of `kiota` and `azidentity` packages.

The tool is utilising both SDK's v1.0 and beta, but as I said I couldn't use `Delete()` method as it's not found, and I've got compiler error:
`graphClientBeta.Directory().DeletedItems().ByDirectoryObjectId(userID).Delete undefined (type *directory.DeletedItemsDirectoryObjectItemRequestBuilder has no field or method Delete)`

Here is minimal reproducible example showing the authentication + request:

```go
package main

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	kiota "github.com/microsoft/kiota-authentication-azure-go"
	msgraphv1sdk "github.com/microsoftgraph/msgraph-sdk-go"
)

type TenantDesc struct {
	TenantID string
	ClientID string
}

func main() {
	tenantDesc := TenantDesc{}
	tenantDesc.TenantID = "<PUT YOUR TENANT ID HERE>"
	tenantDesc.ClientID = "<PUT YOUR CLIENT ID HERE>"
	userID := "<PUT THE DELETED USER ID HERE>"
	err := deleteUserFromRecycleBin(userID, tenantDesc)
	if err != nil {
		fmt.Println(err)
	}
}

func deleteUserFromRecycleBin(userID string, tenantDesc TenantDesc) error {
	credentials, err := azidentity.NewDeviceCodeCredential(
		&azidentity.DeviceCodeCredentialOptions{
			TenantID: tenantDesc.TenantID,
			ClientID: tenantDesc.ClientID,
			UserPrompt: func(ctx context.Context, message azidentity.DeviceCodeMessage) error {
				fmt.Println(message.Message)
				return nil
			},
		})
	if err != nil {
		return errors.New(fmt.Sprintf("Error creating credentials: %s\n", err.Error()))
	}

	scopesAry := strings.Split("Application.ReadWrite.All User.ReadWrite.All", " ")
	authProvider, err := kiota.NewAzureIdentityAuthenticationProviderWithScopes(
		credentials,
		scopesAry)
	if err != nil {
		return errors.New(fmt.Sprintf("Error authentication provider: %s\n", err.Error()))
	}

	// api v1.0
	graphAdapterV1, err := msgraphv1sdk.NewGraphRequestAdapter(authProvider)
	if err != nil {
		return errors.New(fmt.Sprintf("Error creating adapter: %s\n", err.Error()))
	}

	graphClientV1 := msgraphv1sdk.NewGraphServiceClient(graphAdapterV1)
	err = graphClientV1.Directory().DeletedItems().ByDirectoryObjectId(userID).Delete(context.Background(), nil)
	if err != nil {
		return err
	}

	return nil
}
```

`go.mod` file:

```go
module github.com/EmptyRecycleBin

go 1.21

require (
	github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.4.0
	github.com/microsoft/kiota-authentication-azure-go v1.0.1
	github.com/microsoftgraph/msgraph-sdk-go v1.27.0
)
```

**Comment by baywet** [comment]
Thanks for the additional information.
The authentication context is delegated in both cases, I wanted to double check whether a difference could have explained things here.
In terms of user for GE and the application, are you signing in with the same user?

Also could you provide client request ids and timestamps please? They are not sensitive so you don't need to obfuscate them, and they allow us to see some of the logs.

**Comment by arturtorun** [comment]
@baywet Ok thanks for that, below is GE request with id & timestamp. I've checked it few minutes ago and the issue still occurs for GE and SDK.
```
{
    "error": {
        "code": "Request_BadRequest",
        "message": "Invalid parameter paramName: WindowLiveNetId, paramValue: null or empty, objectType: System.Collections.Generic.IList`1[[System.Byte, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]",
        "innerError": {
            "date": "2023-12-19T09:21:58",
            "request-id": "d3159631-743d-4995-9926-3185efdcbd5a",
            "client-request-id": "65f5b481-0858-31bb-4dc5-d1463175f833"
        }
    }
}
```

**Comment by baywet** [comment]
Thanks, this is the id from GE. Can you also provide me one (+ timestamp) for the Go application please?

**Comment by arturtorun** [comment]
Hey again @baywet. 
Here are the app RequestID & ClientRequestID. 

Timestamp is approximate as it has been taken using `time.Now()` at the time when the function call returned an error, as the error value of `ODataError` returns `nil` from `GetInnerError().GetDate()`.

`Timestamp`: `2023-12-19 17:42:53.501766 +0000 GMT m=+18.881071293`
`request-id` `e040d990-decb-4903-859d-f4d76740dba0`
`client-request-id`: `f71e6e7a-598c-4246-9355-92efe82e970b`

**Comment by baywet** [comment]
Thanks for providing this additional information.
I can see the URLs are identical (besides the beta/v1.0 difference) and the URL is properly built by the SDK, as well as your application seems to have the right permissions according to the documentation.
Unfortunately that's as far as I'll be able to help you on this matter. We (the SDK team) only have limited access to the service logs due to privacy concerns. This repository is dedicated to issues about the SDK itself and the SDK is behaving as expected.
Please open a support ticket from your Azure or Office 365 admin portal to get support from the service team.
