### ISSUE TITLE
Access token failure

### ISSUE THREAD

**Issue by chandrakanthkannam** [microsoftgraph/msgraph-sdk-go#639]
Hi Team, I'm new to this sdk and trying to setup my very first application with an interactive teams integration, ability to post messages in to channels and store the responses so the service I'm working on can get back to those threads in channels. as a start I have registered an application on entra, followed the documentation steps and here is where i'm stuck,

I have this basic code,

```
package main

import (
	"context"
	"fmt"

	azidentity "github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	msgraphsdk "github.com/microsoftgraph/msgraph-sdk-go"
)

func main() {
	cred, err := azidentity.NewDeviceCodeCredential(&azidentity.DeviceCodeCredentialOptions{
		TenantID: "<ID>",
		ClientID: "<ID>",
		UserPrompt: func(ctx context.Context, message azidentity.DeviceCodeMessage) error {
			fmt.Println(message.Message)
			return nil
		},
	})

	if err != nil {
		fmt.Printf("Error creating credentials: %v\n", err)
	}

	graphClient, err := msgraphsdk.NewGraphServiceClientWithCredentials(cred, []string{"api://<ID>/Channels.Read"})
	if err != nil {
		fmt.Printf("Error creating credentials: %v\n", err)
	}

	channels, err := graphClient.Teams().ByTeamId("<ID>").Channels().Get(context.Background(), nil)
	if err != nil {
		fmt.Printf("Error getting channels: %v\n", err)
	}
}

```

this is giving me below error,

```
Error getting channels: Access token validation failure. Invalid audience.
<nil>
```

Here is what i have on the permissions:
<img width="1053" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-go/assets/49658217/206332da-8e51-4e3a-a1c1-dfc84344ad1d">

can someone please help me with this?

**Comment by baywet** [comment]
Hi @chandrakanthkannam 
Thanks for reaching out and for using the Go SDK.
As you can see [in this example](https://learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=go#device-code-provider) the scopes you are passing when creating the client do not need the api://id/ prefix, just add the scope name (Channels.Read) and your code should work.
Let us know if you have further questions.
