### ISSUE TITLE
Paging for CrossTenantAccessPolicy.Partners.Get() missing

### ISSUE THREAD

**Issue by tobiaszuercher** [microsoftgraph/msgraph-sdk-go#694]
```go
graphClient := msgraphsdk.NewGraphServiceClientWithCredentials(xxx)
graphClient.Policies().CrossTenantAccessPolicy().Partners().Get(ctx, nil)
```

has no paging. any chance to get paging implemented?

i've also tried with RequestHeaders to set $top and $skip, but these had no effect in the result.

in the current implementation: what is the max items returned?

**Comment by rkodev** [comment]
Hi @tobiaszuercher, Thanks for trying the SDK. 
For request to service layer issues or enhancements, it best advised to post them in [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/)  for service teams to address. 
This repo's scope only addresses issues related to the Go Graph SDK and not the individual service issues.
