### ISSUE TITLE
Documentation states wrong OData bindings

### ISSUE THREAD

**Issue by HorizonNet** [microsoftgraph/msgraph-sdk-go#717]
When following the [example](https://learn.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&tabs=go#example-2-application-permissions) to create a team in Teams the following error pops up when either setting an owner or a template for the team (by specifying `odataBind` as in the example)

```
Unable to create team, got error: The navigation bind for the user was missing in request
```

After finding the following [thread](https://techcommunity.microsoft.com/t5/teams-developer/creating-a-team-via-the-graph-giving-quot-the-navigation-bind/m-p/1929857) (and trying out the proposed solution) it seems like the documentation needs be updated to point to the correct binding. For me the following works when setting the template and assigning the owner

```go
...
newTeam.SetAdditionalData(map[string]interface{}{
    "template@odata.bind": "https://graph.microsoft.com/v1.0/teamsTemplates('standard')",
})

...

conversationMember.SetAdditionalData(map[string]interface{}{
    "user@odata.bind": "https://graph.microsoft.com/v1.0/users('xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')",
})
...
```

**Comment by rkodev** [comment]
Hi @HorizonNet, thanks for discovering and reporting on the documentation issue. A fix for the documentation is currently underway
