### ISSUE TITLE
release 1.44 breaks the api with no releasenotes or documentation updates

### ISSUE THREAD

**Issue by havardelnan** [microsoftgraph/msgraph-sdk-go#721]
The function NewItemGetMemberGroupsPostRequestBody turned into ItemGetmembergroupsGetMemberGroupsPostRequestBody 

Docs: https://learn.microsoft.com/nb-no/graph/api/directoryobject-getmembergroups?view=graph-rest-1.0&tabs=go#example-2-check-group-memberships-for-the-signed-in-user

Please dont break on minor releases.
Please include release notes

<
// NewItemGetMemberGroupsPostRequestBody instantiates a new ItemGetMemberGroupsPostRequestBody and sets the default values.
func NewItemGetMemberGroupsPostRequestBody()(*ItemGetMemberGroupsPostRequestBody) {
    m := &ItemGetMemberGroupsPostRequestBody{
    }
    m.backingStore = ie8677ce2c7e1b4c22e9c3827ecd078d41185424dd9eeb92b7d971ed2d49a392e.BackingStoreFactoryInstance();
    m.SetAdditionalData(make(map[string]any))
    return m
}
>
// NewItemGetmembergroupsGetMemberGroupsPostRequestBody instantiates a new ItemGetmembergroupsGetMemberGroupsPostRequestBody and sets the default values.
func NewItemGetmembergroupsGetMemberGroupsPostRequestBody()(*ItemGetmembergroupsGetMemberGroupsPostRequestBody) {
    m := &ItemGetmembergroupsGetMemberGroupsPostRequestBody{
    }
    m.backingStore = ie8677ce2c7e1b4c22e9c3827ecd078d41185424dd9eeb92b7d971ed2d49a392e.BackingStoreFactoryInstance();
    m.SetAdditionalData(make(map[string]any))
    return m
}

**Comment by jasonjoh** [comment]
Additional changes I've run into:

- `ItemCalendarViewRequestBuilderGetQueryParameters` -> `ItemCalendarviewCalendarViewRequestBuilderGetQueryParameters`
- `ItemCalendarViewRequestBuilderGetRequestConfiguration` -> `ItemCalendarviewCalendarViewRequestBuilderGetRequestConfiguration`
- `ItemMailFoldersItemMessagesRequestBuilderGetQueryParameters` -> `ItemMailfoldersItemMessagesRequestBuilderGetQueryParameters`
- `ItemMailFoldersItemMessagesRequestBuilderGetRequestConfiguration` -> `ItemMailfoldersItemMessagesRequestBuilderGetRequestConfiguration`
- `NewItemSendMailPostRequestBody` -> `NewItemSendmailSendMailPostRequestBody`
