### ISSUE TITLE
Can't set SkuID to add a license to a user

### ISSUE THREAD

**Issue by Trevor-J-Ortiz** [microsoftgraph/msgraph-sdk-go#735]
On the assign license doc, it requires setting the SkuID using the uuid package. UUID is internal so it can't be imported. Is there another way to set the SkuID or am I doing this incorrectly? 

https://github.com/microsoftgraph/msgraph-sdk-go/blob/v1.45.0/models/assigned_license.go
https://learn.microsoft.com/en-us/graph/api/user-assignlicense?view=graph-rest-1.0&tabs=go
![image](https://github.com/microsoftgraph/msgraph-sdk-go/assets/53014173/e705ca3b-ab76-4f2f-8d4c-384616cee58c)

**Comment by andrueastman** [comment]
Thanks for raising this @Trevor-J-Ortiz 

Any chance you can confirm if the GO sample at the link below is helpful? https://learn.microsoft.com/en-us/graph/api/user-assignlicense?view=graph-rest-1.0&tabs=go

**Comment by andrueastman** [comment]
@Trevor-J-Ortiz 

I believe you only need to add the import for `"github.com/google/uuid"` as the generated code relies on the package for the type.

Any chance you can confirm this works out for you?
