### ISSUE TITLE
[NewItemAddpasswordAddPasswordPostRequestBody] Is this a typo?

### ISSUE THREAD

**Issue by reborn1867** [microsoftgraph/msgraph-sdk-go#737]
Recently I updated msgraph-sdk-go from v1.38.0 -> v1.45.0, when checking code changes I found the function `applications.NewItemAddPasswordPostRequestBody()` is renamed to `applications.NewItemAddpasswordAddPasswordPostRequestBody()` which is quite confusing. I know this library seems to be auto-generated but is this new function name a typo or intended change?

**Comment by rkodev** [comment]
Related to https://github.com/microsoftgraph/msgraph-sdk-go/issues/721

**Comment by rkodev** [comment]
Hi @reborn1867 , This issue is caused by a bad release and is being resolved in ticket https://github.com/microsoftgraph/msgraph-sdk-go/issues/721. Please skip revert to release v1.43 as 1.44 and 1.45

**Comment by reborn1867** [comment]
Thanks for the reply
