### ISSUE TITLE
MS Windows - Unable to import library or clone repository because file names are too long

### ISSUE THREAD

**Issue by RichGski** [microsoftgraph/msgraph-sdk-go#743]
In MS Windows I'm getting a bunch of errors because the file names are too long:
rror: unable to create file storage/filestorage_containers_item_drive_list_items_item_getactivitiesbyintervalwithstartdatetimewithenddatetimewithinterval_get_activities_by_interval_with_start_date_time_with_end_date_time_with_interval_request_builder.go: Filename too long
error: unable to create file storage/filestorage_containers_item_drive_list_items_item_getactivitiesbyintervalwithstartdatetimewithenddatetimewithinterval_get_activities_by_interval_with_start_date_time_with_end_date_time_with_interval_response.go: Filename too long
error: unable to create file teams/item_channels_item_doesuserhaveaccessuseriduseridtenantidtenantiduserprincipalnameuserprincipalname_does_user_have_accessuser_id_user_id_tenant_id_tenant_id_user_principal_name_user_principal_name_get_response.go: Filename too long
error: unable to create file teams/item_channels_item_doesuserhaveaccessuseriduseridtenantidtenantiduserprincipalnameuserprincipalname_does_user_have_accessuser_id_user_id_tenant_id_tenant_id_user_principal_name_user_principal_name_request_builder.go: Filename too long
error: unable to create file teams/item_channels_item_doesuserhaveaccessuseriduseridtenantidtenantiduserprincipalnameuserprincipalname_does_user_have_accessuser_id_user_id_tenant_id_tenant_id_user_principal_name_user_principal_name_response.go: Filename too long
error: unable to create file teams/item_primarychannel_doesuserhaveaccessuseriduseridtenantidtenantiduserprincipalnameuserprincipalname_does_user_have_accessuser_id_user_id_tenant_id_tenant_id_user_principal_name_user_principal_name_get_response.go: Filename too long
error: unable to create file teams/item_primarychannel_doesuserhaveaccessuseriduseridtenantidtenantiduserprincipalnameuserprincipalname_does_user_have_accessuser_id_user_id_tenant_id_tenant_id_user_principal_name_user_principal_name_request_builder.go: Filename too long
error: unable to create file teams/item_primarychannel_doesuserhaveaccessuseriduseridtenantidtenantiduserprincipalnameuserprincipalname_does_user_have_accessuser_id_user_id_tenant_id_tenant_id_user_principal_name_user_principal_name_response.go: Filename too long
error: unable to create file teamwork/deletedteams_item_channels_item_doesuserhaveaccessuseriduseridtenantidtenantiduserprincipalnameuserprincipalname_does_user_have_accessuser_id_user_id_tenant_id_tenant_id_user_principal_name_user_principal_name_get_response.go: Filename too long
error: unable to create file teamwork/deletedteams_item_channels_item_doesuserhaveaccessuseriduseridtenantidtenantiduserprincipalnameuserprincipalname_does_user_have_accessuser_id_user_id_tenant_id_tenant_id_user_principal_name_user_principal_name_request_builder.go: Filename too long
error: unable to create file teamwork/deletedteams_item_channels_item_doesuserhaveaccessuseriduseridtenantidtenantiduserprincipalnameuserprincipalname_does_user_have_accessuser_id_user_id_tenant_id_tenant_id_user_principal_name_user_principal_name_response.go: Filename too long
error: unable to create file users/item_joinedteams_item_channels_item_doesuserhaveaccessuseriduseridtenantidtenantiduserprincipalnameuserprincipalname_does_user_have_accessuser_id_user_id_tenant_id_tenant_id_user_principal_name_user_principal_name_get_response.go: Filename too long
error: unable to create file users/item_joinedteams_item_channels_item_doesuserhaveaccessuseriduseridtenantidtenantiduserprincipalnameuserprincipalname_does_user_have_accessuser_id_user_id_tenant_id_tenant_id_user_principal_name_user_principal_name_request_builder.go: Filename too long
error: unable to create file users/item_joinedteams_item_channels_item_doesuserhaveaccessuseriduseridtenantidtenantiduserprincipalnameuserprincipalname_does_user_have_accessuser_id_user_id_tenant_id_tenant_id_user_principal_name_user_principal_name_response.go: Filename too long
error: unable to create file users/item_joinedteams_item_primarychannel_doesuserhaveaccessuseriduseridtenantidtenantiduserprincipalnameuserprincipalname_does_user_have_accessuser_id_user_id_tenant_id_tenant_id_user_principal_name_user_principal_name_get_response.go: Filename too long
error: unable to create file users/item_joinedteams_item_primarychannel_doesuserhaveaccessuseriduseridtenantidtenantiduserprincipalnameuserprincipalname_does_user_have_accessuser_id_user_id_tenant_id_tenant_id_user_principal_name_user_principal_name_request_builder.go: Filename too long
error: unable to create file users/item_joinedteams_item_primarychannel_doesuserhaveaccessuseriduseridtenantidtenantiduserprincipalnameuserprincipalname_does_user_have_accessuser_id_user_id_tenant_id_tenant_id_user_principal_name_user_principal_name_response.go: Filename too long
Updating files: 100% (14540/14540), done.

**Comment by baywet** [comment]
Hi @RichGski 
Thanks for using the Microsoft graph SDK and for reaching out. 
Have you enabled long path support on your Windows installation? 
https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/

**Comment by RichGski** [comment]
> Hi @RichGski Thanks for using the Microsoft graph SDK and for reaching out. Have you enabled long-path support on your Windows installation? https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/
I enabled long path names and it fixed this issue.
