### ISSUE TITLE
importing "github.com/microsoftgraph/msgraph-sdk-go" adds 10 seconds to build time

### ISSUE THREAD

**Issue by quinn** [microsoftgraph/msgraph-sdk-go#753]
### Describe the bug

Adding this package took my build time from around 1 second to 10 to 20 seconds. 

### Expected behavior

I would expect adding a new dependency to only make a marginal difference on build time. 

Is there a way to only include the graph libraries that I will be using? 

### How to reproduce

main.go:

```go
package main

import (
	"fmt"

	msgraphsdk "github.com/microsoftgraph/msgraph-sdk-go"
)

type Repo struct {
	msgraph *msgraphsdk.GraphServiceClient
}

func main() {
	fmt.Println("%v", Repo{})
}
```

```bash
$ go mod init test
$ go mod tidy
$ time go build main.go
go build main.go  6.78s user 3.18s system 55% cpu 18.043 total
```

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by baywet** [comment]
Hi @quinn,
Thank you for using the sdk and for reaching out.
We just had a very similar question a couple of days ago so I thought I would link you to the answer I provided back then.
https://github.com/microsoftgraph/msgraph-sdk-java/issues/2098#issuecomment-2255773250
Let us know if you have any additional question.
