### ISSUE TITLE
Undefined types in Golang for users related to Delta parameters and configurations

### ISSUE THREAD

**Issue by Shaka-Man** [microsoftgraph/msgraph-sdk-go#768]
### Describe the bug

With an app-only authentication program I am attempting to monitor particular user's mail folder utilizing delta requests.  The requests work in Graph Explorer.  When utilizing the code snippet built by Explorer for the query an undefined returned for both the Parameters and the Configuration.

The two types in question are users.UserItemMailFolderItemMessagesDeltaWithRequestBuilderGetQueryParameters and users.UserItemMailFolderItemMessagesDeltaWithRequestBuilderGetRequestConfiguration.

Here is an example of the query used in Explorer:
https://graph.microsoft.com/v1.0/users/{id}/mailFolders('inbox')/messages/delta?changeType=created&$select=subject,from,isRead,body,receivedDateTime

The code snippet generated is as follows:

import (
	  "context"
	  abstractions "github.com/microsoft/kiota-abstractions-go"
	  msgraphsdk "github.com/microsoftgraph/msgraph-sdk-go"
	  graphusers "github.com/microsoftgraph/msgraph-sdk-go/users"
	  //other-imports
)

headers := abstractions.NewRequestHeaders()
headers.Add("Prefer", "outlook.body-content-type=\"text\"")

requestChangeType := "created"

requestParameters := &graphusers.UserItemMailFolderItemMessagesDeltaWithRequestBuilderGetQueryParameters{
	ChangeType: &requestChangeType,
	Select: [] string {"subject","from","isRead","body","receivedDateTime"},
}
configuration := &graphusers.UserItemMailFolderItemMessagesDeltaWithRequestBuilderGetRequestConfiguration{
	Headers: headers,
	QueryParameters: requestParameters,
}

// To initialize your graphClient, see https://learn.microsoft.com/en-us/graph/sdks/create-client?from=snippets&tabs=go
delta, err := graphClient.Users().ByUserId("user-id").MailFolders().ByMailFolderId("mailFolder-id").Messages().Delta().GetAsDeltaGetResponse(context.Background(), configuration)

### Expected behavior

I expected the sample code generated by Graph Explorer to compile

### How to reproduce

Place the provided query in Explorer and execute.  Review the Golang code snippet and open with vscode.  That will immediately highlight the two types as undefined.

### SDK Version

1.47.0

### Debug output

undefined: users.UserItemMailFolderItemMessagesDeltaWithRequestBuilderGetRequestConfigurationcompiler[UndeclaredIm](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#UndeclaredImportedName)

(undefined: users.UserItemMailFolderItemMessagesDeltaWithRequestBuilderGetQueryParameterscompiler[UndeclaredImporte](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#UndeclaredImportedName)

### Configuration

macOS 14.6.1
Apple M3 Pro

**Comment by rkodev** [comment]
Hi @Shaka-Man , thank you for testing out the SDK.
I've noted the issue with the generated code and it will be fixed on the [snippet generation tool](https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/2228)

As for now, you can use the sample

```go

	headers := abstractions.NewRequestHeaders()
	headers.Add("Prefer", "outlook.body-content-type=""text""")

	requestChangeType := "created"

	requestParameters := &graphusers.ItemMailFoldersItemMessagesDeltaRequestBuilderGetQueryParameters{
		ChangeType: &requestChangeType,
		Select:     []string{"subject", "from", "isRead", "body", "receivedDateTime"},
	}
	configuration := &graphusers.ItemMailFoldersItemMessagesDeltaRequestBuilderGetRequestConfiguration{
		Headers:         headers,
		QueryParameters: requestParameters,
	}

	// To initialize your graphClient, see https://learn.microsoft.com/en-us/graph/sdks/create-client?from=snippets&tabs=go
	delta, err := graphClient.Users().ByUserId("user-id").MailFolders().ByMailFolderId("mailFolder-id").Messages().Delta().GetAsDeltaGetResponse(context.Background(), configuration)
```
