### ISSUE TITLE
There is no way to perform batch request

### ISSUE THREAD

**Issue by nagnagendra** [microsoftgraph/msgraph-sdk-go#77]
No way to perform the batch request using sdk which is supported by msgraph api

**Comment by baywet** [comment]
Hi @nagnagendra ,
Thanks for trying the sdk and for reaching out.
You are correct, this is a feature gap today.
We have an issue open already here https://github.com/microsoftgraph/msgraph-sdk-go-core/issues/11
We're working to close the feature gap and in the meantime can I suggest you subscribe to that issue so you get updates as we make progress please?
Thanks! Closing
