### ISSUE TITLE
Convert DirectoryObjects to User objects?

### ISSUE THREAD

**Issue by hanix** [microsoftgraph/msgraph-sdk-go#79]
Hi, I am using the GO SDK to fetch users and group information from AD. Because I have a lot of users, I am fetching groups first and then foreach group I get it's members.

```Golang
func fetchGroupMembers(*groups graph.Group) {
	var dirObjList []graph.DirectoryObject = make([]graph.DirectoryObject, 0)
	
	for _, group := range groups {
		page1, err := client.GroupsById(*group.GetId()).Members().Get(nil)
		if err != nil {
			return err
		}
		dirObjList = append(dirObjList, page1.GetValue()...)

		//Iterator to iterate over remaining pages and fetch users
		iterator, err := msgcore.NewPageIterator(page1, *adapter, func() serialization.Parsable {
			return directoryobjects.NewDirectoryObjectsResponse()
		})
		if err != nil {
			return err
		}
		callback := func(item interface{}) bool {
			dirObjList = append(dirObjList, item.(graph.DirectoryObject))
			return true
		}
		iterator.Iterate(callback)
		fmt.Println("#Users: ", len(dirObjList))

		//Here, I am expecting users object but I get directory objects
		for _, u := range dirObjList {

			//I need to access user object attributes like displayName and so on ...
		}

		match = false
	}
}
```

Is there a way to convert graph.DirectoryObjects to graph.User objects? Or how should I go about this? Thanks.
PS: This code is representational only.

**Comment by baywet** [comment]
Hi @hanix,
Thanks for trying the SDK and for reaching out.
This is listed as a [known limitation](https://github.com/microsoftgraph/msgraph-sdk-go-core/issues/1) and needs to be [implemented in the generator first](https://github.com/microsoft/kiota/issues/648).
The good news is that [I started the work in the generator](https://github.com/microsoft/kiota/pull/1174), but we're probably still as least one week out before this shows up in the SDK.

When this is complete, the callback will provide you the final object, up-casted as directoryObject. You'll need to downcast to a User object and you'll see the user-specific properties with values.

In the meantime, you can access the properties you need from user through additional data (user-> directoryObject-> entity)

https://github.com/microsoftgraph/msgraph-sdk-go/blob/a2632179253fd9fc980cf966ac7512838771ad49/models/microsoft/graph/entity.go#L22

**Comment by baywet** [comment]
if that can help for future reference once the feature is implemented, you can "downcast" like this

```Golang
// response is a directory object response like for client.GroupsById("id").Members.Get(nil), where the value array is an array of directory objects
// m is the import for the models package
// absser is the import for github.com/microsoft/kiota/abstractions/go/serialization
for _, do := range response.GetValue() {
		pdo := absser.Parsable(&do)
		user := pdo.(*m.User)
		upn := user.GetUserPrincipalName()
		fmt.Printf("UPN: %v\n", *upn)
	}
```

**Comment by hanix** [comment]
Thank you @baywet for replying, I will be waiting for the enhancement to be released. Could you provide an example of how I could use the user->directoryObject->entity to access the user properties? I I played with it a little bit I wasn't able to produce anything ?

**Comment by hanix** [comment]
One more thing, I noticed that user object (and possibly) others don't support json.marshaling. The attributes are not Exported nor do they have the json tag.

Should I open a new issue for this as well ?
Thanks

**Comment by hanix** [comment]
Thank you.
I will keep up with the progress of the enhancements : )

**Comment by baywet** [comment]
you're welcome!
I'll go ahead and close this issue since we're already tracking it at other places. I suggest you subscribe [to this issue](https://github.com/microsoft/kiota/issues/648) to track progress.

**Comment by ronsun8** [comment]
I'm having the same problem as OP and waiting for the iterator enhancement.

In the meantime, I tried your example but I'm unable to dereference upn from your example.  It says gives me `invalid indirect of upn type 'interface{}'`

I found a method to get the value using reflect below:
```
additionalData := dirObj.GetAdditionalData()
i := additionalData["displayName"]
if i != nil {
  test := reflect.ValueOf(i).Elem()
  fmt.Printf("%v", test)
}
```
Is this the recommended way to do it or am I missing something?

**Comment by baywet** [comment]
You might have to add a type assertion to the sample I've provided. So

```Golang
// response is a directory object response like for client.GroupsById("id").Members.Get(nil), where the value array is an array of directory objects
for _, do := range response.GetValue() {
upn := do.GetAdditionalData()["userPrincipalName"]. (*string) // upn will be nil if not a user, might want to nil check before dereferencing
fmt.Printf("UPN: %v\n", *upn)
}
```

**Comment by ronsun8** [comment]
it worked great, thanks for the quick reply!

**Comment by baywet** [comment]
You're welcome!
If you push this code to production there are a bunch of nil checks missing.

**Comment by Mattes83** [comment]
> ```go
> // response is a directory object response like for client.GroupsById("id").Members.Get(nil), where the value array is an array of directory objects
> // m is the import for the models package
> for _, do := range response.GetValue() {
> 		user := do.(m.Userable)
> 		upn := user.GetUserPrincipalName()
> 		fmt.Printf("UPN: %v\n", *upn)
> 	}
> ```

Should this work by now? When I try 

```go
if result, err := r.GraphServiceClient.GroupsById(objectID.String()).TransitiveMembers().Get(); err == nil {
  for _, do := range result.GetValue() {
    user := do.(models.Userable)
    upn := user.GetUserPrincipalName()
    logger.Info(*upn)
}
```

I get a panic because do cannot be cast to models.Userable

**Comment by devopriya23** [comment]
If you are out there like me, you have to fetch the upn via GetBackingStore().Get("userPrincipalName")
