### ISSUE TITLE
ManagedDevices.CreateDevice returns No OData route exists

### ISSUE THREAD

**Issue by hazcod** [microsoftgraph/msgraph-sdk-go#807]
### Describe the bug

I am trying to update the compliance state of an Azure device via the Graph API SDK for Go.

This always returns error: `failed to update device: No OData route exists that match template ~/singleton/navigation with http verb POST for request /DeviceFE/StatelessDeviceFEService/deviceManagement/managedDevices."

### Expected behavior

Works.

### How to reproduce

```go
	_, err = a.graphClient.DeviceManagement().ManagedDevices().Post(context.Background(),
		device.azureDevice, nil)
	if err != nil {
		return fmt.Errorf("failed to update device: %v", err)
	}
```

### SDK Version

v1.51.0

### Known Workarounds

N/A

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

### Configuration

Go version:  `go version go1.23.3 darwin/arm64`

**Comment by baywet** [comment]
Hi @hazcod 
Thank you for using the SDK and for reaching out.

For others reference [this is the operation we're referring to here](https://learn.microsoft.com/en-us/graph/api/intune-devices-manageddevice-create?view=graph-rest-1.0&tabs=http)

This seems to be a service issue, as the client experiences team we do not have access to backend services. Please contact the support. [More information](https://developer.microsoft.com/en-us/graph/support)

Closing.
