### ISSUE TITLE
ItemItemsRequestBuilderGetQueryParameters Filter has no Effect anymore

### ISSUE THREAD

**Issue by sidi7** [microsoftgraph/msgraph-sdk-go#817]
### Describe the bug

I am trying to filter a drive using request filters similar to the doc here: https://learn.microsoft.com/en-us/graph/query-parameters?tabs=go#filter-parameter

### Expected behavior

The code snippet below used to work and returned just one item. Now it returns every item on that drive!

`
	requestFilter := "name eq 'TEST'"

	requestParameters := &graphdrives.ItemItemsRequestBuilderGetQueryParameters{
		Filter: &requestFilter,
	}
	configuration := &graphdrives.ItemItemsRequestBuilderGetRequestConfiguration{
		QueryParameters: requestParameters,
	}

	fils, err := graphClient.Drives().ByDriveId("DRIVEID").Items().Get(context.Background(), configuration)

	if err != nil {
		fmt.Printf("Error: %v\n", err)
	}`
/

### How to reproduce

Run the code above on a Drive and filter by name for some existing folder.

### SDK Version

1.51.0

### Other information

I did not change anything in the code. The application was running fine.

**Comment by baywet** [comment]
Hi @sidi7 
Thank you for using the SDK and for reaching out.

Can you replace the last `Get` part of that call by "ToGetRequestInformation" instead. 
And then log the Uri of the returned value so you can share it here please?

**Comment by sidi7** [comment]
hi @baywet 
I get:
&{GET %!s(*url.URL=<nil>) %!s(*abstractions.RequestHeaders=&{{map[accept:map[application/json:{}]]}}) map[%24filter:name eq 'TEST'] map[]  map[baseurl:https://graph.microsoft.com/v1.0 drive%2Did:DRIVEID] map[] {+baseurl}/drives/{drive%2Did}/items{?%24count,%24expand,%24filter,%24orderby,%24search,%24select,%24skip,%24top} map[]}

Is this what you mean?

**Comment by baywet** [comment]
Thank you for the additional information.
Yes, I meant the url, thanks for sharing.

The SDK is sending the right request with the correct query parameters, if anything is wrong, it's related to the service itself.

This seems to be a service issue, as the client experiences team we do not have access to backend services. Please contact the support. [More information](https://developer.microsoft.com/en-us/graph/support)

**Comment by sidi7** [comment]
Hi @baywet 
It indeed seems like an issue on the service: https://learn.microsoft.com/en-us/answers/questions/2133562/graph-drive-getitems-filter-has-no-effect
As I only need one item anyway - is there a better SDK API to get a folder by name?
Thanks!

**Comment by baywet** [comment]
You might be able to get it by name if you know the name using the indexed method (getById instead of get, and then another get after that)

**Comment by sidi7** [comment]
How do I get the ID initially? The Item ID is basically what I need.

**Comment by baywet** [comment]
What I was trying to express is that it might work by passing the directory name instead of the ID and you should try it out.

**Comment by sidi7** [comment]
Ah, okay. Thanks for the hint!

**Comment by sidi7** [comment]
Hi again @baywet 

I think this is not working

`	doc := graphClient.Drives().ByDriveId("DRIVEID").Items().ByDriveItemId("NAME")
	if err != nil {
		fmt.Printf("Error: %v\n", err)
	}

	fmt.Printf("doc: %s\n", doc)

	itemMy, err := doc.Get(context.Background(), nil)
	if err != nil {
		fmt.Printf("Error: %v\n", err)
	}

	fmt.Printf("Item: %s\n", itemMy)`

Prints: Error: Item not found

On the other hand, I got feedback that on the root drive filters might still work. But I am unable to build this request in the sdk from the docs (e.g. here both Code Snippets show the same code: https://learn.microsoft.com/en-us/graph/api/driveitem-list-children?view=graph-rest-1.0&tabs=go)

`https://graph.microsoft.com/v1.0/me/drives/driveID/root/children?$filter=name+eq+%27apps%27`

When i do

`	myRoot, err := graphClient.Drives().ByDriveId("DRIVEID").Root().Get(context.Background(), nil)
	if err != nil {
		fmt.Printf("Error: %v\n", err)
	}

	myChildren := myRoot.GetChildren()

	fmt.Printf("Len: %d\n", len(myChildren))

	for _, child := range myChildren {
		fmt.Printf("Child: %s\n", child)
	}`

Len of myChildren is 0

**Comment by baywet** [comment]
Thank you for the additional information.

The /me and /drives/id (and below) APIs should be strictly equivalent (assuming the id being passed is the one of the user's OneDrive) and give you the same results. If that's not the case, I encourage you to follow up with the support team.

As for the not found exception, it also depends on the API itself. It's not clear which operations support an item name and which only support the item id. Maybe this is something you can get clarity on with the support team as well.

Let us know if you have any additional comments or questions.

**Comment by sidi7** [comment]
Hi @baywet 
I am not using my own onedrive but a drive (Documents) on some SharePoint using Azure App Auth.

To work closer with support (and switch between Postman and SDK) it would be beneficial to extract the access token from the sdk. Is there any way to achieve this?

Thanks!

**Comment by baywet** [comment]
key as in access token?
If so, yes, on your credentials object, you should have a GetToken method [here is one of such methods](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#ClientAssertionCredential.GetToken)

**Comment by sidi7** [comment]
Pefect, that worked!

Support showed me that https://graph.microsoft.com/v1.0/drives/DRIVEID/root/children?$filter=name+eq+'NAME' works. However I can not find a way to achieve this using the SDK.
`root, err := graphClient.Drives().ByDriveId("DRIVEID").Root().ToGetRequestInformation(context.Background(), nil)`

But when I call GetChildren as mentionned above 0 are returned.

> Hi again @baywet
> 
> I think this is not working
> 
> ` doc := graphClient.Drives().ByDriveId("DRIVEID").Items().ByDriveItemId("NAME") if err != nil { fmt.Printf("Error: %v\n", err) }
> 
> ```
> fmt.Printf("doc: %s\n", doc)
> 
> itemMy, err := doc.Get(context.Background(), nil)
> if err != nil {
> 	fmt.Printf("Error: %v\n", err)
> }
> 
> fmt.Printf("Item: %s\n", itemMy)`
> ```
> 
> Prints: Error: Item not found
> 
> On the other hand, I got feedback that on the root drive filters might still work. But I am unable to build this request in the sdk from the docs (e.g. here both Code Snippets show the same code: https://learn.microsoft.com/en-us/graph/api/driveitem-list-children?view=graph-rest-1.0&tabs=go)
> 
> `https://graph.microsoft.com/v1.0/me/drives/driveID/root/children?$filter=name+eq+%27apps%27`
> 
> When i do
> 
> ` myRoot, err := graphClient.Drives().ByDriveId("DRIVEID").Root().Get(context.Background(), nil) if err != nil { fmt.Printf("Error: %v\n", err) }
> 
> ```
> myChildren := myRoot.GetChildren()
> 
> fmt.Printf("Len: %d\n", len(myChildren))
> 
> for _, child := range myChildren {
> 	fmt.Printf("Child: %s\n", child)
> }`
> ```
> 
> Len of myChildren is 0

**Comment by baywet** [comment]
Thank you for the additional information.

All query parameters are supported (or not) by the service. And their presence in the SDK is driven by the metadata the service is providing. If you feel like some query parameters are missing it could mean two things:
- The service doesn't support it in that operation, in which case it's a feature request.
- The service supports it, but it's not present in the metadata, in that case it's most likely a bug.

In both cases, it's worth having a discussion about that with support.

**Comment by sidi7** [comment]
Hm, alright.

From the doc I do not see a way to call custom endpoints like "https://graph.microsoft.com/v1.0/drives/DRIVEID/root/children?$filter=name+eq+%27NAME"

Is there a way to use the sdk client to make Get or Post requests to such endpoints?

**Comment by sidi7** [comment]
In the end this is the code that achieved the same and works for me:

`
	requestParameters := &graphdrives.ItemRootRequestBuilderGetQueryParameters{
		Expand: []string{"children"},
	}

	rootConfig := &graphdrives.ItemRootRequestBuilderGetRequestConfiguration{
		QueryParameters: requestParameters,
	}

	root, err := graphClient.Drives().ByDriveId(DRIVEID).Root().Get(context.Background(), rootConfig)
	if err != nil {
		ds.logger.Error("Could not get drive items", err)

		return "", errors.New("unable to get drive items")
	}

	children := root.GetChildren()

	ds.logger.Info("Number of Children for Root: " + strconv.Itoa(len(children)))

	for _, child := range children {
		if *child.GetName() == NAME {
			childId := *child.GetId()
			ds.logger.Info("Child Found Name: " + *child.GetName())

			return childId, nil
		}
	}

	ds.logger.Info("No Child that matches the correct name found")

	return "", nil
`
