### ISSUE TITLE
way to get json response

### ISSUE THREAD

**Issue by nagnagendra** [microsoftgraph/msgraph-sdk-go#92]
Hi,

Is there any way to get the raw JSON response for an object like applications, users, groups, drive items etc.,

**Comment by baywet** [comment]
Hi @nagnagendra 
Thanks for trying the Go SDK and for reaching out.
Yes, through a response handler
https://github.com/microsoft/kiota/blob/c2dcdc98e868b5c467b294c7f182279a6d2d4cba/abstractions/go/response_handler.go#L4

The response parameter in that case is [a net http response reference](https://pkg.go.dev/net/http#Response). When you use a response handler, it's up to your application to handle unsuccessful responses, deserialization and other aspects handle by the default response handling which is part of the client.

Once you're implemented the function, you can pass it to the chained API like this.

```Golang

user, err := client.Me.Get(nil) //uses the default response handling and gives you a deserialized user object

options: := &me.MeRequestBuilderGetOptions{
   ResponseHandler: yourResponseHandler
}
user, err := client.Me.Get(options) // uses your response handler instead.
```

Let us know if you have further questions.
